import { Activities } from './Activities';
import { professionFactor } from '../core/activities';
import { useState } from 'react';
import { ASSETS, CROPS, ITEMS, QUESTS, RECIPES, SPEEDUPS, type AssetId, type CropId, type ItemId, type RecipeId } from '../core/catalog';
import { contractNeed } from '../core/engine';
import { homeLevel, homeSpec, plotCap, regionCap, storageCap, usedStorage, queueCap, outputCap, productionFactor, upgradePrice, upgradeMs, upgradeRequirements, costText, CHAPTER_TITLES, CHAPTER_PRODUCTS, chapterReady, orderFor, recipeAllowed } from '../core/progression';
import { marketItems, marketHome, marketPrice, marketStock } from '../core/simulation';
import { ownedAt } from '../core/world';
import type { FarmCommand, FarmState } from '../core/types';
import { CropIcon, Icon, type IconName } from './Icon';
import { Goods, Progress, duration } from './shared';
export type Panel = 'build' | 'shop' | 'inventory' | 'quests' | 'orders';
export const menus: {
    id: Panel;
    label: string;
    icon: IconName;
}[] = [{ id: 'build', label: 'Xây dựng', icon: 'hammer' }, { id: 'shop', label: 'Cửa hàng', icon: 'store' }, { id: 'inventory', label: 'Kho hàng', icon: 'basket' }, { id: 'quests', label: 'Nhiệm vụ', icon: 'book' }, { id: 'orders', label: 'Đơn hàng', icon: 'package' }];
export type Confirmation = {
    title: string;
    body: string;
    command: FarmCommand;
};
type Props = {
    s: FarmState;
    panel: Panel;
    selected: string | null;
    busy: boolean;
    act: (c: FarmCommand) => Promise<boolean>;
    confirm: (c: Confirmation) => void;
    select: (id: string) => void;
    begin: (a: AssetId | 'plot', id?: string) => void;
    map: () => void;
    plant: (id?: CropId) => void;
    fish: () => void;
};
export function Panels({ s, panel, selected, busy, act, confirm, select, begin, map, plant, fish }: Props) {
    const [filter, setFilter] = useState(''), [category, setCategory] = useState('all'), [amount, setAmount] = useState(1), [batches, setBatches] = useState(1), [questTab, setQuestTab] = useState('story');
    const level = homeLevel(s), entity = s.entities.find(e => e.id === selected), plot = s.plots.find(p => p.id === selected), obstacle = s.world.obstacles.find(o => o.id === selected), bridge = s.world.bridges.find(b => b.id === selected), order = orderFor(s), home = s.entities.find(e => e.asset === 'home')!;
    const chapter = Array.from({ length: 25 }, (_, i) => i + 1).find(n => !s.claimed.includes(`chapter:${n}`)) ?? 25;
    const speed = (id: string, remaining: number) => <div className="farm-speedups">{SPEEDUPS.map(n => <button key={n} disabled={busy || !s.speedups[n]} onClick={() => confirm({ title: `Dùng phiếu ${n} phút`, body: `Còn ${duration(remaining)} → ${duration(Math.max(0, remaining - n * 60000))}. ${remaining < n * 60000 ? 'Phần thời gian dư không được hoàn.' : ''}`, command: { type: 'speedup', targetId: id, minutes: n } })}>{n < 60 ? `${n}p` : '1 giờ'} <small>×{s.speedups[n]}</small></button>)}</div>;
    if (entity) {
        const price = entity.level < 25 ? upgradePrice(entity) : null, errors = upgradeRequirements(s, entity);
        return <>
  <div className="farm-panel-lead"><Icon name={entity.asset === 'home' ? 'home' : 'hammer'} size={36}/><div><b>{ASSETS[entity.asset].kind === 'building' ? `Cấp ${entity.level}/25` : 'Trang trí'}</b><p>{ASSETS[entity.asset].description}</p></div></div>
  {entity.construction && <section className="farm-card"><h3>{entity.construction.newBuilding ? 'Đang xây' : `${entity.level} → ${entity.construction.target}`}</h3>{entity.construction.waitingFor ? <><p>Đã giữ chi phí và đội thợ. Chờ mẻ hiện tại xong.</p><button onClick={() => act({ type: 'cancel-upgrade', entityId: entity.id })}>Hủy lịch, hoàn chi phí</button></> : <><Progress start={entity.construction.startedAt} end={entity.construction.readyAt} now={s.clock}/>{speed(entity.construction.id, entity.construction.readyAt - s.clock)}</>}</section>}
  {entity.asset === 'home' && <><div className="farm-stat-grid"><span><b>{s.plots.length}/{plotCap(s)}</b>ruộng</span><span><b>{s.world.owned.length}/{regionCap(s)}</b>khu đất</span><span><b>{homeSpec(s).builderSlots}</b>đội thợ</span></div><p>{homeSpec(s).milestone}</p></>}
  {entity.asset === 'warehouse' && <p>Kho {usedStorage(s)}/{storageCap(s)}. Mỗi cấp thêm 80 chỗ; phiếu và trang trí có túi riêng.</p>}
  {!!Object.keys(entity.output).length && <section className="farm-card"><h3>Thành phẩm đang chờ</h3><Goods items={entity.output}/><button className="farm-primary" disabled={busy} onClick={() => act({ type: 'collect', entityId: entity.id })}>Nhận vào kho</button></section>}
  {entity.job && <section className="farm-card"><h3>{RECIPES[entity.job.recipe].name}</h3><Progress start={entity.job.startedAt} end={entity.job.readyAt} now={s.clock}/>{entity.job.readyAt > s.clock && speed(entity.job.id, entity.job.readyAt - s.clock)}<small>Kho tại trạm: {outputCap(entity)} sản phẩm. Đầy sẽ dừng mẻ kế.</small></section>}
  {!!entity.queue.length && <section className="farm-card"><h3>{entity.queue.length} mẻ đang chờ</h3>{entity.queue.map(j => <p key={j.id}>{RECIPES[j.recipe].name} · {duration(j.duration)}</p>)}<button onClick={() => act({ type: 'cancel-queue', entityId: entity.id })}>Hủy mẻ chờ, hoàn nguyên liệu</button></section>}
  {Object.entries(RECIPES).some(([, r]) => r.building === entity.asset) && <><label>Số mẻ mỗi lần<select value={batches} onChange={e => setBatches(Number(e.target.value))}>{Array.from({ length: queueCap(entity) }, (_, i) => <option key={i} value={i + 1}>{i + 1} mẻ</option>)}</select></label>{Object.entries(RECIPES).filter(([, r]) => r.building === entity.asset).map(([id, r]) => <section className="farm-recipe" key={id}><h3>{r.name}</h3><Goods items={r.inputs} state={s}/><p>{r.quantity} {ITEMS[r.output].name.toLowerCase()} · {duration(r.seconds * 1000 * productionFactor(entity) * professionFactor(s, id as RecipeId))}</p><button disabled={busy || !recipeAllowed(s, entity, id as RecipeId)} onClick={() => act({ type: 'produce', entityId: entity.id, recipe: id as RecipeId, quantity: batches })}>{level < r.home && !entity.legacy ? `Nhà chính ${r.home}` : entity.level < r.buildingLevel ? `Trạm cấp ${r.buildingLevel}` : `Xếp ${batches} mẻ`}</button></section>)}</>}
  {entity.asset === 'fishing_pier' && !entity.construction && <button className="farm-primary" onClick={fish}>Câu cá · trò nhớ nhịp</button>}
  {ASSETS[entity.asset].kind === 'building' && price && !entity.construction && <section className="farm-card"><h3>Nâng lên cấp {entity.level + 1}</h3><p>{entity.asset === 'home' ? 'Mở thêm quyền phát triển.' : entity.asset === 'warehouse' ? '+80 sức chứa kho.' : `Mẻ mới nhanh hơn; sức chứa ${outputCap(entity)} → ${outputCap({ ...entity, level: entity.level + 1 })}; hàng đợi ${queueCap(entity)} → ${queueCap({ ...entity, level: entity.level + 1 })}.`}</p><p>{costText(price)}</p><small>{duration(upgradeMs(entity))} · {s.entities.filter(e => e.construction).length}/{homeSpec(s).builderSlots} đội thợ đang dùng</small>{errors.map((e, i) => <p key={i} className="farm-warning">Cần: {e}</p>)}<button className="farm-primary" disabled={busy || !!errors.length} onClick={() => confirm({ title: `Nâng ${ASSETS[entity.asset].name}`, body: `${costText(price)}. ${duration(upgradeMs(entity))}. ${entity.job ? 'Chờ mẻ hiện tại; hàng đợi tạm dừng.' : 'Đã khởi công thì không hủy.'}`, command: { type: 'upgrade', entityId: entity.id } })}>Xem và nâng cấp</button></section>}
  <button disabled={!!entity.construction} onClick={() => begin(entity.asset, entity.id)}><Icon name="move"/>Chuyển vị trí</button>{ASSETS[entity.asset].kind === 'decor' && <button onClick={() => act({ type: 'store', entityId: entity.id })}>Cất vào kho trang trí</button>}
 </>;
    }
    if (plot)
        return <><CropIcon id={plot.crop ?? 'wheat'} size={52}/><h3>{plot.crop ? CROPS[plot.crop].name : 'Đất đang chờ hạt'}</h3>{plot.crop ? <><Progress start={plot.plantedAt!} end={plot.readyAt!} now={s.clock}/><button className="farm-primary" onClick={() => act({ type: 'harvest', plotId: plot.id })} disabled={busy || s.clock < plot.readyAt!}>Thu hoạch</button><button onClick={() => act({ type: 'water', plotId: plot.id })} disabled={!!plot.watered || s.clock >= plot.readyAt!}>Tưới · nhanh hơn 10%</button>{plot.readyAt! > s.clock && speed(plot.id, plot.readyAt! - s.clock)}</> : <><p>Chọn giống rồi chạm hoặc quét nhiều luống.</p><button className="farm-primary" onClick={() => plant()}>Gieo nhiều ô</button></>}</>;
    if (obstacle)
        return <><p>{obstacle.kind === 'tree' ? 'Cây già → 12 gỗ' : obstacle.kind === 'ore' ? 'Đá quặng → 8 quặng + 4 đá' : 'Đá tảng → 12 đá + 2 đất sét'}</p>{!ownedAt(s.world, obstacle.x, obstacle.z) ? <button onClick={map}>Nhận khu đất trước</button> : obstacle.cleared ? <p>Đã dọn. Vật cản này không mọc lại.</p> : obstacle.readyAt !== undefined ? <><p>{obstacle.readyAt > s.clock ? `Còn ${duration(obstacle.readyAt - s.clock)}` : 'Đã xong, tài nguyên đang chờ.'}</p><button className="farm-primary" onClick={() => act({ type: 'collect-obstacle', obstacleId: obstacle.id })} disabled={obstacle.readyAt > s.clock}>Nhận tài nguyên và đất</button>{obstacle.readyAt > s.clock && speed(obstacle.id, obstacle.readyAt - s.clock)}</> : <><p>Đội khai phá riêng, không chiếm đội thợ xây.</p><button className="farm-primary" onClick={() => confirm({ title: 'Thuê dọn vật cản', body: '10 xu · 1 phút. Nhận tài nguyên rồi giải phóng 1 ô đất.', command: { type: 'clear', obstacleId: obstacle.id, pay: 'coins' } })}>Thuê dọn · 10 xu</button><button onClick={() => confirm({ title: 'Dọn bằng dụng cụ', body: 'Tiêu 1 dụng cụ · 30 giây.', command: { type: 'clear', obstacleId: obstacle.id, pay: 'tools' } })}>Dùng 1 dụng cụ · đang có {s.inventory.tools}</button></>}</>;
    if (bridge)
        return <><p>Cần Nhà chính 4 và sở hữu hai đầu cầu.</p>{bridge.built ? <p>Cầu đã mở.</p> : bridge.readyAt ? <p>Còn {duration(bridge.readyAt - s.clock)}</p> : <button onClick={() => confirm({ title: 'Xây cầu gỗ', body: '100 xu · 6 ván · 4 đá · 5 phút.', command: { type: 'bridge', bridgeId: bridge.id } })}>Xây cầu</button>}</>;
    if (panel === 'build')
        return <><div className="farm-inline"><select aria-label="Nhóm xây dựng" value={category} onChange={e => setCategory(e.target.value)}><option value="all">Tất cả</option><option value="building">Công trình</option><option value="decor">Trang trí</option><option value="open">Đã mở</option></select><input aria-label="Tìm công trình" placeholder="Tìm công trình…" value={filter} onChange={e => setFilter(e.target.value)}/></div><button className="farm-primary" disabled={s.plots.length >= plotCap(s)} onClick={() => begin('plot')}>Thêm luống · 15 xu ({s.plots.length}/{plotCap(s)})</button><button onClick={map}>Khai phá · {s.world.owned.length}/{regionCap(s)} khu đất</button><div className="farm-shop-grid">{Object.entries(ASSETS).filter(([id, a]) => id !== 'home' && (category === 'all' || category === a.kind || category === 'open' && a.level <= level) && a.name.toLowerCase().includes(filter.toLowerCase())).map(([id, a]) => { const existing = s.entities.find(e => e.asset === id); return <button key={id} disabled={level < a.level} onClick={() => existing && a.kind === 'building' ? select(existing.id) : begin(id as AssetId)}><Icon name={a.kind === 'building' ? 'home' : 'flower'} size={28}/><b>{a.name}</b><small>{level < a.level ? `Nhà chính ${a.level}` : existing && a.kind === 'building' ? `Đã có · cấp ${existing.level}` : `${a.price} xu`}</small></button>; })}</div></>;
    if (panel === 'shop')
        return <><h3>Hạt giống</h3><p>Mua hạt khi gieo; chỉ trừ xu cho những ô đã xác nhận.</p><div className="farm-seeds">{Object.entries(CROPS).map(([id, c]) => <button key={id} disabled={level < c.level} onClick={() => plant(id as CropId)}><CropIcon id={id}/><b>{c.name}</b><small>{level < c.level ? `Nhà chính ${c.level}` : `${c.seed} xu · ${duration(c.seconds * 1000)}`}</small><small>Thu {c.yield} · bán {c.sell}/món</small></button>)}</div><h3>Vật tư của làng</h3><p>Giá cao hơn bán lại. Bổ sung sau {duration((s.market.epoch + 1) * 14400000 - s.clock)}.</p><label>Số lượng mỗi lần<input type="number" min={1} max={30} value={amount} onChange={e => setAmount(Number(e.target.value))}/></label>{marketItems.map(id => <div className="farm-row" key={id}><span><b>{ITEMS[id].name}</b><small>{marketPrice(id)} xu/món · còn {marketStock(s, id)}</small></span><button disabled={busy || level < marketHome[id]} onClick={() => act({ type: 'buy', item: id, quantity: amount, epoch: s.market.epoch })}>{level < marketHome[id] ? `Nhà chính ${marketHome[id]}` : `Mua ${amount}`}</button></div>)}</>;
    if (panel === 'inventory')
        return <><p>{usedStorage(s)}/{storageCap(s)} chỗ. Bán/giao đơn giữ lại phần đã ghim.</p><input aria-label="Tìm hàng trong kho" placeholder="Tìm hàng…" value={filter} onChange={e => setFilter(e.target.value)}/>{Object.entries(s.inventory).filter(([id, n]) => n > 0 && ITEMS[id as ItemId].name.toLowerCase().includes(filter.toLowerCase())).map(([id, n]) => <section className="farm-inventory-row" key={id}><div><i style={{ background: ITEMS[id as ItemId].color }}/><b>{ITEMS[id as ItemId].name} ×{n}</b><small>{ITEMS[id as ItemId].sell} xu/món</small></div><div className="farm-inline"><button onClick={() => act({ type: 'sell', item: id as ItemId, quantity: 1 })}>Bán 1</button><button onClick={() => confirm({ title: `Bán ${ITEMS[id as ItemId].name}`, body: `Bán ${Math.max(0, n - (s.reserve[id as ItemId] ?? 0))} món khả dụng; giữ phần dự trữ.`, command: { type: 'sell', item: id as ItemId, quantity: Math.max(0, n - (s.reserve[id as ItemId] ?? 0)) } })}>Bán phần dư</button><button onClick={() => act({ type: 'reserve', item: id as ItemId, quantity: s.reserve[id as ItemId] ? 0 : n })}>{s.reserve[id as ItemId] ? `Bỏ ghim ${s.reserve[id as ItemId]}` : 'Giữ lại'}</button></div></section>)}<h3>Túi hỗ trợ</h3><div className="farm-stat-grid">{SPEEDUPS.map(n => <span key={n}><b>×{s.speedups[n]}</b>{n} phút</span>)}</div><h3>Trang trí đã cất</h3>{s.entities.filter(e => e.stored).map(e => <button key={e.id} onClick={() => begin(e.asset, e.id)}>{ASSETS[e.asset].name} · Đặt lại</button>)}<h3>Sổ sản phẩm</h3><p>Đã biết {s.discovered.length}/{Object.keys(ITEMS).length} loại.</p><Goods items={Object.fromEntries(s.discovered.map(id => [id, s.produced[id] ?? 0]))}/></>;
    if (panel === 'orders')
        return <><section className="farm-story"><small>{order.person}</small><h3>{order.name}</h3><Goods items={order.need} state={s}/><p>Nhận {order.coins} xu · {order.xp} danh tiếng</p><button className="farm-primary" disabled={busy} onClick={() => act({ type: 'deliver' })}>Giao đơn</button><button onClick={() => act({ type: 'skip-order' })}>Đổi đơn miễn phí</button></section><h3>Hợp đồng phiên chợ</h3>{level < 12 ? <p>Mở từ Nhà chính 12. Ba chặng qua nhiều phiên.</p> : <section className="farm-card"><p>Hợp đồng {s.contract.round + 1} · chặng {s.contract.stage + 1}/3</p><Goods items={contractNeed(s)} state={s}/><p>Mỗi chặng trả 150% giá NPC; xong nhận phiếu 30 phút.</p><button onClick={() => act({ type: 'contract' })}>Giao chặng này</button></section>}</>;
    return <><div className="farm-tabs"><button aria-pressed={questTab === 'story'} onClick={() => setQuestTab('story')}>Chính tuyến</button><button aria-pressed={questTab === 'achievements'} onClick={() => setQuestTab('achievements')}>Thành tựu</button></div>{questTab === 'story' ? <><section className="farm-story"><small>CHƯƠNG {chapter}/25</small><h3>{CHAPTER_TITLES[chapter - 1]}</h3><p>{homeSpec(s).milestone}</p><ul><li>Nhà chính cấp {chapter}: {level >= chapter ? '✓' : `${level}/${chapter}`}</li><li>Thu hoạch {chapter * 3} luống: {s.stats.harvest}/{chapter * 3}</li>{CHAPTER_PRODUCTS[chapter - 1] && <li>Tự làm {ITEMS[CHAPTER_PRODUCTS[chapter - 1]!].name}: {(s.produced[CHAPTER_PRODUCTS[chapter - 1]!] ?? 0) > 0 ? '✓' : 'chưa có'}</li>}</ul><p>Thưởng {80 + chapter * 40} xu + phiếu tăng tốc.</p><button className="farm-primary" disabled={busy || s.claimed.includes(`chapter:${chapter}`) || !chapterReady(s, chapter)} onClick={() => act({ type: 'chapter', chapter })}>Nhận thưởng chương</button><button onClick={() => select(home.id)}>Chuẩn bị nâng Nhà chính</button></section><details><summary>Hành trình 25 chương</summary>{CHAPTER_TITLES.map((title, i) => <p key={title}>{s.claimed.includes(`chapter:${i + 1}`) ? '✓' : '○'} {i + 1}. {title}</p>)}</details></> : QUESTS.map(q => <section key={q.id} className="farm-card"><h3>{q.name}</h3><p>{q.description}</p><div className="farm-progress"><span style={{ width: `${Math.min(100, s.stats[q.stat] / q.target * 100)}%` }}/></div><small>{Math.min(q.target, s.stats[q.stat])}/{q.target} · {q.coins} xu + phiếu 5 phút</small><button disabled={busy || s.claimed.includes(q.id) || s.stats[q.stat] < q.target} onClick={() => act({ type: 'claim', questId: q.id })}>{s.claimed.includes(q.id) ? 'Đã nhận' : 'Nhận thưởng'}</button></section>)}<section className="farm-card"><h3>Thu gom vật liệu</h3><p>Nguồn gỗ/đá làm lại được, không tốn xu. Vùng có thế mạnh cho 6 thay vì 4 mỗi chuyến.</p>{s.gather ? <><p>{ITEMS[s.gather.item].name} · {duration(s.gather.readyAt - s.clock)}</p><button className="farm-primary" disabled={s.gather.readyAt > s.clock} onClick={() => act({ type: 'collect-gather' })}>Nhận vật liệu</button></> : <div className="farm-inline"><button onClick={() => act({ type: 'gather', item: 'wood' })}>Gom gỗ · 30s</button><button onClick={() => act({ type: 'gather', item: 'stone' })}>Gom đá · 30s</button></div>}<button className="farm-link" onClick={() => act({ type: 'help-seeds' })}>Nhờ giúp giống khi hết vốn</button></section>{level>=3&&<Activities s={s} act={act} confirm={confirm}/>}<h3>Công trình của mình</h3>{s.entities.filter(e => ASSETS[e.asset].kind === 'building').map(e => <button className="farm-building-link" key={e.id} onClick={() => select(e.id)}>{ASSETS[e.asset].name}<small>Cấp {e.level}{e.construction ? ' · đang thi công' : e.job ? ' · đang làm' : ''}</small></button>)}</>;
}


