import { lesson, know, rule, text, pic, widget, mistake } from '../../build';
import { example as ex, step as s } from '../authored';
import type { LessonBook } from '../../types';
export default {
 'g2.addsub20': lesson('g2.addsub20',{v:1,goal:'cộng, trừ qua 10 trong phạm vi 20.',
  know:[know('Tạo mốc 10',rule('Tách số để cộng đủ 10 hoặc trừ về 10. Tính tiếp phần còn lại.'),pic('groupsSVG',[{emoji:'⭐',n:8},{emoji:'⭐',n:5}]),text('8 + 5 = 8 + 2 + 3 = 13.'))],
  forms:[ex('cong','Dạng 1: Cộng qua 10',1,'Tổng phần đơn vị lớn hơn 10.',['Tách số sau để đủ 10.','Cộng tiếp phần còn lại.'],'Tính 7 + 6.',[s('Tách 6 thành 3 và 3.'),s('7 + 3 = 10; 10 + 3 = 13.')],'13.'),ex('tru','Dạng 2: Trừ qua 10',2,'Phải bớt qua mốc 10.',['Tách số trừ để về 10.','Trừ tiếp phần còn lại.'],'Tính 14 − 8.',[s('Tách 8 thành 4 và 4.'),s('14 − 4 = 10; 10 − 4 = 6.')],'6.')],
  remember:['Tách số nhưng dùng đủ các phần.','Dùng phép cộng để thử lại phép trừ.']}),
 'g2.addsub100_nc': lesson('g2.addsub100_nc',{v:1,goal:'cộng, trừ không nhớ trong phạm vi 100.',
  know:[know('Đặt tính đúng hàng',rule('Đơn vị thẳng đơn vị, chục thẳng chục. Tính từ phải sang trái.'),widget({w:'column',op:'+',a:34,b:25}),text('34 + 25 = 59.'))],
  forms:[ex('cong','Dạng 1: Cộng',1,'Cộng hai số không cần nhớ.',['Cộng hàng đơn vị.','Cộng hàng chục.'],'Tính 42 + 36.',[s('2 cộng 6 bằng 8.'),s('4 cộng 3 bằng 7.')],'78.'),ex('tru','Dạng 2: Trừ',2,'Mỗi hàng đều trừ được.',['Trừ hàng đơn vị.','Trừ hàng chục.'],'Tính 87 − 35.',[s('7 trừ 5 bằng 2.'),s('8 trừ 3 bằng 5.')],'52.',{check:'52 + 35 = 87'})],
  remember:['Đặt tính thẳng hàng.','Bắt đầu từ đơn vị.']}),
 'g2.addsub100_c': lesson('g2.addsub100_c',{v:1,goal:'cộng, trừ có nhớ trong phạm vi 100.',
  know:[know('Cộng có nhớ',rule('Cộng đơn vị được từ 10 trở lên: viết đơn vị, nhớ 1 chục.'),widget({w:'column',op:'+',a:47,b:28})),know('Trừ có nhớ',rule('Khi trừ có nhớ, cộng số nhớ vào hàng tiếp theo của số trừ.'),widget({w:'column',op:'-',a:52,b:27}))],
  forms:[ex('cong','Dạng 1: Cộng có nhớ',1,'Hàng đơn vị cộng lại đủ một chục.',['Cộng đơn vị, ghi số nhớ.','Cộng chục và số nhớ.'],'Tính 47 + 28.',[s('7 cộng 8 bằng 15, viết 5 nhớ 1.'),s('4 cộng 2 thêm 1 bằng 7.')],'75.',{replay:{w:'column',op:'+',a:47,b:28}}),ex('tru','Dạng 2: Trừ có nhớ',2,'Hàng đơn vị của số đầu nhỏ hơn số sau.',['Trừ đơn vị có nhớ.','Thêm số nhớ vào số trừ rồi trừ chục.'],'Tính 52 − 27.',[s('12 trừ 7 bằng 5, viết 5 nhớ 1.'),s('2 thêm 1 bằng 3; 5 trừ 3 bằng 2.')],'25.',{replay:{w:'column',op:'-',a:52,b:27},check:'25 + 27 = 52'})],
  mistakes:[mistake('Bạn Bi tính 52 − 27 = 35.','Kết quả đúng là 25.','Bi quên thêm số nhớ vào hàng chục của số trừ.')],remember:['Không bỏ quên số nhớ.','Thử lại phép trừ bằng phép cộng.']}),
 'g2.chain': lesson('g2.chain',{v:1,goal:'tính biểu thức có hai dấu cộng, trừ.',
  know:[know('Từ trái sang phải',rule('Biểu thức chỉ có cộng, trừ: tính từ trái sang phải.'),text('32 + 18 − 25 = 50 − 25 = 25.'))],
  forms:[ex('congtru','Dạng 1: Cộng rồi trừ',2,'Có hai dấu cộng, trừ, không có ngoặc.',['Tính hai số bên trái.','Dùng kết quả tính tiếp.'],'Tính 45 + 27 − 18.',[s('45 + 27 = 72.'),s('72 − 18 = 54.')],'54.'),ex('trucong','Dạng 2: Trừ rồi cộng',2,'Dấu trừ xuất hiện trước dấu cộng.',['Trừ trước theo thứ tự.','Cộng tiếp vào kết quả.'],'Tính 63 − 28 + 16.',[s('63 − 28 = 35.'),s('35 + 16 = 51.')],'51.')],
  mistakes:[mistake('Bạn Bi cộng 28 với 16 trước trong 63 − 28 + 16.','Phải tính 63 − 28 trước.','Cộng không được ưu tiên trước trừ.')],remember:['Cộng, trừ cùng mức ưu tiên.','Tính từ trái sang phải.']}),
 'g2.terms': lesson('g2.terms',{v:1,goal:'gọi đúng tên thành phần phép cộng, phép trừ.',
  know:[know('Phép cộng',rule('Hai số được cộng là số hạng. Kết quả là tổng.'),text('Trong 23 + 15 = 38: số hạng là 23, 15; tổng là 38.')),know('Phép trừ',rule('Số đầu là số bị trừ; số sau dấu trừ là số trừ.'),text('Trong 38 − 15 = 23: hiệu là 23.'))],
  forms:[ex('cong','Dạng 1: Gọi tên trong phép cộng',1,'Đề cho phép cộng.',['Tìm hai số trước dấu bằng.','Tìm kết quả sau dấu bằng.'],'Trong 18 + 24 = 42, tổng là số nào?',[s('Kết quả phép cộng là 42.')],'Tổng là 42.'),ex('tru','Dạng 2: Gọi tên trong phép trừ',1,'Đề cho phép trừ.',['Đọc từ trái sang phải.','Gọi tên theo vị trí.'],'Trong 50 − 17 = 33, số trừ là số nào?',[s('Số đứng sau dấu trừ là 17.')],'Số trừ là 17.')],
  remember:['Cộng: số hạng, số hạng, tổng.','Trừ: số bị trừ, số trừ, hiệu.']}),
 'g2.missing': lesson('g2.missing',{v:1,goal:'tìm thành phần còn thiếu của phép cộng, phép trừ.',needs:['g2.terms'],
  know:[know('Tìm số hạng',rule('Số hạng chưa biết bằng tổng trừ số hạng đã biết.'),text('□ + 18 = 45: 45 − 18 = 27.')),know('Tìm thành phần phép trừ',rule('Số bị trừ bằng hiệu cộng số trừ. Số trừ bằng số bị trừ trừ hiệu.'),text('□ − 8 = 12: 12 + 8 = 20.'))],
  forms:[ex('hang','Dạng 1: Số hạng',2,'Ô trống nằm trong phép cộng.',['Xác định tổng và số hạng đã biết.','Lấy tổng trừ số hạng.'],'Điền số: 26 + □ = 60.',[s('Số cần tìm:', '60 − 26 = 34')],'34.',{check:'26 + 34 = 60'}),ex('bitru','Dạng 2: Số bị trừ',2,'Ô trống đứng trước dấu trừ.',['Xác định hiệu và số trừ.','Lấy hiệu cộng số trừ.'],'Điền số: □ − 19 = 35.',[s('Số cần tìm:', '35 + 19 = 54')],'54.',{check:'54 − 19 = 35'}),ex('sotru','Dạng 3: Số trừ',2,'Ô trống đứng sau dấu trừ.',['Xác định số bị trừ và hiệu.','Lấy số bị trừ trừ hiệu.'],'Điền số: 72 − □ = 28.',[s('Số cần tìm:', '72 − 28 = 44')],'44.',{check:'72 − 44 = 28'})],
  remember:['Gọi tên ô trống trước khi chọn phép tính.','Thay số tìm được để thử lại.']}),
 'g2.compare_expr': lesson('g2.compare_expr',{v:1,goal:'so sánh giá trị hai biểu thức cộng, trừ.',
  know:[know('Tính rồi điền dấu',rule('Tính giá trị mỗi bên. So sánh hai kết quả rồi điền dấu.'),text('25 + 17 = 42; 60 − 18 = 42. Hai bên bằng nhau.'))],
  forms:[ex('ss','Dạng 1: Điền dấu',2,'Ô trống nằm giữa hai phép tính.',['Tính bên trái.','Tính bên phải rồi so sánh.'],'Điền dấu: 46 + 18 □ 90 − 27.',[s('46 + 18 = 64.'),s('90 − 27 = 63.'),s('64 > 63.')],'46 + 18 > 90 − 27.')],
  mistakes:[mistake('Bạn Bi so 46 với 90 rồi điền dấu <.','Phải tính cả hai biểu thức trước.','Số đầu không quyết định giá trị cả biểu thức.')],remember:['Tính đủ hai bên.','Dấu = khi hai kết quả bằng nhau.']}),
 'g2.word_more_less': lesson('g2.word_more_less',{v:1,goal:'giải bài toán nhiều hơn, ít hơn.',
  know:[know('Thêm phần hơn, bớt phần kém',rule('Tìm số nhiều hơn: cộng phần hơn. Tìm số ít hơn: trừ phần kém.'),text('An có 12 bút. Bình hơn 5 bút: 12 + 5 = 17 (bút).'))],
  forms:[ex('hon','Dạng 1: Nhiều hơn',2,'Biết số ít và phần hơn.',['Xác định số đã biết.','Cộng phần hơn.'],'An có 28 nhãn vở. Bình nhiều hơn An 7 nhãn. Bình có bao nhiêu?',[s('Bình có số nhãn vở là:', '28 + 7 = 35 (nhãn)')],'Đáp số: 35 nhãn vở.',{layout:'solution'}),ex('it','Dạng 2: Ít hơn',3,'Biết số nhiều và phần ít hơn.',['Xác định số đã biết.','Trừ phần ít hơn.'],'Mai có 42 viên bi. Lan ít hơn Mai 8 viên. Lan có bao nhiêu?',[s('Lan có số viên bi là:', '42 − 8 = 34 (viên)')],'Đáp số: 34 viên bi.',{layout:'solution'})],
  mistakes:[mistake('Bạn Bi thấy chữ hơn là luôn cộng.','Phải xác định đang tìm số nhiều hay số ít.','Nếu biết số nhiều, tìm số ít thì cần trừ.')],remember:['Đọc xem ai nhiều, ai ít.','Ghi lời giải và đơn vị.']}),
} satisfies LessonBook;
