import {describe,it,expect} from 'vitest';
import {newMatch,resolveTurn,validateMatch,legalActions,positionKey,score} from './engine';
import {directionFor,ROWS} from './board';
import {chooseAction} from './bot';
import {seeded} from '../HorseRace/rng';
import type {Match,Player} from './model';
export const players:Player[]=[{id:'host',name:'An',avatar:'avatar_01',kind:'human',level:'medium'},{id:'guest',name:'Bông',avatar:'avatar_02',kind:'human',level:'medium'}];
export function fixture(board:Record<number,number>,otherBank=0):Match{const s=newMatch('owner',players,'test');s.board=Array.from({length:12},(_,i)=>board[i]||0);s.banks=[{dân:50-s.board.reduce((a,b)=>a+b,0)-otherBank,quan:0},{dân:otherBank,quan:0}];s.history=[positionKey(s)];return s;}
describe('family-v1 rules',()=>{
 it('starts with 50 citizens and two mandarins, with screen-relative directions',()=>{const s=newMatch('owner',players,'id');expect(validateMatch(s)).toBe(true);expect(legalActions(s)).toHaveLength(10);expect(directionFor(2,'right')).toBe(1);expect(directionFor(8,'right')).toBe(-1);expect(directionFor(8,'left')).toBe(1);});
 it('relays from the other row and deposits into a mandarin pit',()=>{const s=fixture({4:2,7:3,8:1});const r=resolveTurn(s,{pit:4,direction:1});expect(r.events.filter(e=>e.kind==='pickup').map(e=>e.from)).toEqual([4,7]);expect(r.state.board[5]).toBe(1);expect(r.state.board[6]).toBe(1);expect(r.state.board[8]).toBe(2);expect(r.state.active).toBe(1);expect(s.board[4]).toBe(2);});
 it('captures a chain including a mandarin, without distributing that mandarin',()=>{const s=fixture({0:1,3:4,7:1,8:2});const r=resolveTurn(s,{pit:0,direction:1});expect(r.events.filter(e=>e.kind==='capture').map(e=>[e.from,e.dân,e.quan])).toEqual([[3,4,0],[5,0,1],[7,1,0]]);expect(r.state.banks[0].quan).toBe(1);expect(r.state.active).toBe(1);});
 it('stops before an empty mandarin pit instead of jumping across it',()=>{const s=fixture({0:4,6:3});s.quan[0]=false;s.banks[0].quan=1;const r=resolveTurn(s,{pit:0,direction:1});expect(r.events.filter(e=>e.kind==='capture')).toHaveLength(0);expect(r.state.board[6]).toBe(3);});
 it('stops at two empty pits',()=>{const r=resolveTurn(fixture({0:1,7:2}),{pit:0,direction:1});expect(r.events.filter(e=>e.kind==='capture')).toHaveLength(0);});
 it('circles the board and deposits back into its starting pit',()=>{const r=resolveTurn(fixture({0:13,7:1}),{pit:0,direction:1});const drops=r.events.filter(e=>e.kind==='drop');expect(drops.slice(0,13).map(e=>e.to)).toEqual([1,2,3,4,5,6,7,8,9,10,11,0,1]);});
 it('refills all five pits from exactly five captured citizens',()=>{const r=resolveTurn(fixture({0:4},5),{pit:0,direction:1});expect(r.state.phase).toBe('play');expect(ROWS[1].map(p=>r.state.board[p])).toEqual([1,1,1,1,1]);expect(r.state.banks[1].dân).toBe(0);expect(r.events.filter(e=>e.kind==='refill')).toHaveLength(5);});
 it('ends without borrowing or converting a captured mandarin, leaving middle tokens unclaimed',()=>{const s=fixture({0:4},4);s.quan[0]=false;s.banks[1].quan=1;const r=resolveTurn(s,{pit:0,direction:1});expect(r.state.reason).toBe('shortage');expect(r.state.banks[1]).toEqual({dân:4,quan:1});expect(r.state.quan[1]).toBe(true);expect(score(r.state,0)+score(r.state,1)).toBe(60);expect(validateMatch(r.state)).toBe(true);});
 it('ends when both mandarin pits are truly empty, sweeping each row to its owner',()=>{const s=fixture({8:1});s.active=1;s.quan[0]=false;s.banks[0].quan=1;const r=resolveTurn(s,{pit:8,direction:1});expect(r.state.reason).toBe('empty');expect(r.state.banks[1]).toEqual({dân:1,quan:1});expect(score(r.state,0)+score(r.state,1)).toBe(70);expect(validateMatch(r.state)).toBe(true);});
 it('does not end merely because both mandarin figures have been captured',()=>{const s=fixture({0:4,5:2,8:1});s.quan=[false,false];s.banks[0].quan=2;expect(resolveTurn(s,{pit:0,direction:1}).state.phase).toBe('play');});
 it('records an exact draw',()=>{const s=fixture({8:1,11:2},25);s.quan=[false,false];s.banks[0].quan=1;s.banks[1].quan=1;s.active=0;s.board[2]=s.board[8];s.board[8]=0;const r=resolveTurn(s,{pit:2,direction:-1});expect(r.state.reason).toBe('empty');expect(r.state.winner).toBeNull();expect([score(r.state,0),score(r.state,1)]).toEqual([35,35]);});
 it('ends the third repeated complete turn state',()=>{const s=fixture({0:4,8:1});const key=positionKey(resolveTurn(s,{pit:0,direction:1},false).state);s.history=[key,key];expect(resolveTurn(s,{pit:0,direction:1}).state.reason).toBe('repetition');});
 it('rejects wrong side, invalid direction and repeated input on ended games',()=>{const s=newMatch('owner',players,'id');expect(resolveTurn(s,{pit:7,direction:1}).state).toBe(s);expect(resolveTurn(s,{pit:0,direction:0 as 1}).state).toBe(s);const over=resolveTurn(fixture({0:4}),{pit:0,direction:1}).state;expect(resolveTurn(over,{pit:0,direction:1}).state).toBe(over);});
 it('rejects corrupted quantities, winners, owners and rules',()=>{const s=newMatch('owner',players,'id');expect(validateMatch({...s,board:[...s.board,1]})).toBe(false);expect(validateMatch({...s,owner:'wrong'},'owner')).toBe(false);expect(validateMatch({...s,rulesVersion:'other'})).toBe(false);expect(validateMatch({...s,banks:[{dân:1,quan:0},s.banks[1]]})).toBe(false);});
 it('preserves all tokens and event/search parity across seeded complete games',()=>{const rng=seeded(61789);let steps=0;for(let game=0;game<80;game++){let s=newMatch('owner',players,'random-'+game,game%2 as 0|1);for(let turn=0;turn<500&&s.phase==='play';turn++){const acts=legalActions(s),a=acts[Math.floor(rng()*acts.length)],r=resolveTurn(s,a);expect(r.state).toEqual(resolveTurn(s,a,false).state);expect(validateMatch(r.state)).toBe(true);for(const e of r.events){expect(e.position.board.reduce((a,b)=>a+b,0)+e.position.banks.reduce((a,b)=>a+b.dân,0)+e.held).toBe(50);expect(e.position.quan.filter(Boolean).length+e.position.banks.reduce((a,b)=>a+b.quan,0)).toBe(2);}s=r.state;steps++;}expect(s.phase).toBe('over');}expect(steps).toBeGreaterThan(1000);});
 it('all bot levels return a legal action without mutating the board',()=>{const s=newMatch('owner',players,'bot'),before=JSON.stringify(s);for(const level of ['easy','medium','hard'] as const){const r=chooseAction(s,level,{maxDepth:2,nodes:1000});expect(legalActions(s)).toContainEqual(r.action);}expect(JSON.stringify(s)).toBe(before);expect(chooseAction(s,'hard',{deadline:1}).action).not.toBeNull();});
});
