import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {OAnQuan} from './OAnQuanGame';
import {newMatch,positionKey} from './engine';
import type {Match,Player} from './model';
import type {StudentProfile} from '../../types';
const profile:StudentProfile={id:'o-an-quan-dev-preview',name:'Minh Anh',age:8,grade:3,avatarId:0,currentAvatarId:'avatar_01',currentThemeId:'default',stars:0,ownedAvatarIds:[],ownedThemeIds:[],ownedImageIds:[],history:[],gameHistory:[],shopDailyPhotos:[]};
const party:Player[]=[{id:'host',name:'Minh Anh',avatar:'avatar_01',kind:'human',level:'medium'},{id:'friend',name:'Bông',avatar:'avatar_02',kind:'human',level:'medium'}];
function fixture(type:string){const s=newMatch(profile.id,party,crypto.randomUUID());if(type==='capture'){s.board=[1,0,0,4,0,0,0,1,2,0,0,0];s.banks[0].dân=42;}if(type==='shortage'){s.board=[4,0,0,0,0,0,0,0,0,0,0,0];s.banks[0].dân=42;s.banks[1].dân=4;}if(type==='finish'||type==='bot-replay'){s.board=[0,0,1,0,0,0,0,0,0,0,0,2];s.quan=[false,false];s.banks=[{dân:22,quan:1},{dân:25,quan:1}];}if(type==='bot-first'||type==='bot-replay'){s.players[1]={...s.players[1],name:'Máy Trúc',kind:'bot'};s.active=s.first=type==='bot-first'?1:0;}s.history=[positionKey(s)];return s;}
function Preview(){const[run,setRun]=useState(0),[initial,setInitial]=useState<Match>(),[sound,setSound]=useState(true),[music,setMusic]=useState(false);const setup=(type:string)=>{setInitial(type==='lobby'?undefined:fixture(type));setRun(n=>n+1);};return <><details style={{position:'fixed',zIndex:100,left:'50%',top:0,transform:'translateX(-50%)',background:'#294c40',color:'#fff',padding:'4px 8px',fontSize:10,borderRadius:6}}><summary>DEV · Ô ăn quan</summary>{[['lobby','Sảnh'],['board','Bàn mới'],['capture','Ăn liên tiếp'],['shortage','Thiếu dân'],['finish','Hòa điểm'],['bot-first','Máy đi trước'],['bot-replay','Thử chơi lại với máy']].map(([id,n])=><button key={id} onClick={()=>setup(id)}>{n}</button>)}<button onClick={()=>document.querySelector('canvas')?.getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext()}>Mất WebGL</button></details><OAnQuan key={run} student={profile} initialMatch={initial} onExit={()=>setup('lobby')} complete={()=>({ok:true})} manageMusic={false} sound={{soundEnabled:sound,musicEnabled:music,toggleSound:()=>setSound(v=>!v),toggleMusic:()=>setMusic(v=>!v)}}/></>;}
if(import.meta.env.DEV)createRoot(document.getElementById('root')!).render(<Preview/>);
