import { describe, it, expect, vi } from 'vitest';
import { InteractionController, GestureAdapter, Pick } from './gesture';
function setup() { const pick = vi.fn<(x: number, y: number) => Pick>((x) => x < 50 ? { type: 'post', post: { partId: 'B', postId: 'plus' } } : { type: 'post', post: { partId: 'L', postId: 'a' } }); const adapter: GestureAdapter = { pick, board: (x, y) => [x / 100, y / 100], connect: vi.fn(), select: vi.fn(), move: vi.fn(), toggle: vi.fn(), hold: vi.fn(), preview: vi.fn(), camera: vi.fn() }; return { a: adapter, c: new InteractionController(adapter) }; }
describe('shared gesture state machine', () => {
    it('tap-tap connects once and dragging connects once', () => { const { a, c } = setup(); c.down(1, 10, 10); c.up(1, 10, 10); c.down(1, 90, 10); c.up(1, 90, 10); expect(a.connect).toHaveBeenCalledTimes(1); c.down(1, 10, 10); c.move(1, 90, 10); c.up(1, 90, 10); expect(a.connect).toHaveBeenCalledTimes(2); });
    it('second finger cancels a wire and remaining finger never commits', () => { const { a, c } = setup(); c.down(1, 10, 10); c.move(1, 30, 10); c.down(2, 50, 50); c.move(2, 60, 60); c.up(2, 60, 60); c.up(1, 90, 10); expect(a.connect).not.toHaveBeenCalled(); expect(a.camera).toHaveBeenCalled(); });
    it('hold button releases on cancel, blur adapter, and second pointer', () => { const { a, c } = setup(); a.pick = () => ({ type: 'part', id: 'K', button: true }); c.down(1, 10, 10); expect(a.hold).toHaveBeenLastCalledWith('K', true); c.cancel(); expect(a.hold).toHaveBeenLastCalledWith('K', false); c.down(1, 10, 10); c.down(2, 60, 60); expect(a.hold).toHaveBeenLastCalledWith('K', false); });
    it('part drag commits only at pointer up', () => { const { a, c } = setup(); a.pick = () => ({ type: 'part', id: 'L' }); c.down(1, 10, 10); c.move(1, 80, 80); expect(a.move).not.toHaveBeenCalled(); c.up(1, 80, 80); expect(a.move).toHaveBeenCalledTimes(1); expect(a.toggle).not.toHaveBeenCalled(); });
    it('escape/cancel rolls back pending connection', () => { const { a, c } = setup(); c.tapPost({ partId: 'B', postId: 'plus' }); c.cancel(); c.tapPost({ partId: 'L', postId: 'a' }); expect(a.connect).not.toHaveBeenCalled(); });
});
