import { describe, it, expect } from 'vitest';
import 'fake-indexeddb/auto';
import type { StudentProfile } from '../../../../types';
import { LESSONS, MISSIONS } from '../../../data/electricity/content';
import { preset } from '../engine/fixtures';
import { createRun, sampleEvidence, Run } from '../engine/evidence';
import { startSimulation, tick } from '../engine/simulation';
import { completeElectricity, archiveLegacy, claimLegacy, ProgressIO } from './progress';
import { createDocument, listDocuments, parseDocument, saveDocument, clearElectricityData } from './notebook';
function completedRun() { const spec = LESSONS[2], sim = startSimulation(preset()); let r = createRun('a', spec, sim.circuit); for (let i = 0; i < 14; i++)
    r = sampleEvidence(spec, r, sim, .02); return r; }
function ioFixture() { let profiles = [{ id: 'a', stars: 7 }, { id: 'b', stars: 12 }] as StudentProfile[], selected = 'a', fail = false; let queue = Promise.resolve(); const io: ProgressIO = { readProfiles: () => structuredClone(profiles), writeProfiles: p => { if (fail)
        throw new Error('quota'); profiles = structuredClone(p); }, isOwner: () => selected === 'a', onSaved: () => { }, lock: fn => { const result = queue.then(fn); queue = result.then(() => { }, () => { }); return result; } }; return { io, get: () => profiles, select: (id: string) => { selected = id; }, fail: () => { fail = true; }, recover: () => { fail = false; } }; }
describe('profile atomic ledger', () => {
    it('double callback and post-crash retry reward exactly once including badge', async () => { const f = ioFixture(), run = completedRun(); const results = await Promise.all([completeElectricity('a', run, f.io), completeElectricity('a', run, f.io)]); expect(results.map(r => r.earned)).toEqual([11, 0]); expect(f.get()[0].stars).toBe(18); expect(f.get()[1].stars).toBe(12); expect((await completeElectricity('a', run, f.io)).earned).toBe(0); });
    it('owner switched while lock was pending cannot receive stars', async () => { const f = ioFixture(), pending = completeElectricity('a', completedRun(), f.io); f.select('b'); expect((await pending).ok).toBe(false); expect(f.get()[0].stars).toBe(7); });
    it('quota error changes neither balance nor completion and retry works', async () => { const f = ioFixture(); f.fail(); expect((await completeElectricity('a', completedRun(), f.io)).pending).toBe(true); expect(f.get()[0].electricity).toBeUndefined(); f.recover(); expect((await completeElectricity('a', completedRun(), f.io)).earned).toBe(11); });
    it('does not reward a guest or an empty run', async () => { const f = ioFixture(); expect((await completeElectricity('guest', completedRun(), f.io)).ok).toBe(false); expect((await completeElectricity('a', createRun('a', LESSONS[2], preset('intro')), f.io)).ok).toBe(false); });
    it('mission improves 1 to 3 then repeats 3 with deltas 1,2,0', async () => { const f = ioFixture(), spec = MISSIONS[0], r = createRun('a', spec, preset('flashlight')), m = { id: spec.steps[0].id, editRevision: 1, solveRevision: 1, time: 1, circuit: preset('flashlight'), power: { L1: .25 } }; r.milestones = [m]; r.step = 1; expect((await completeElectricity('a', r, f.io)).earned).toBe(1); r.milestones = spec.steps.map(s => ({ ...m, id: s.id })); r.step = 3; r.done = true; expect((await completeElectricity('a', r, f.io)).earned).toBe(2); expect((await completeElectricity('a', r, f.io)).earned).toBe(0); });
    it('legacy malformed raw is preserved, normalized history claims only once without stars', async () => { const values = new Map([['electricity_completed_lessons', '[1,1,8,9,"2"]'], ['electricity_completed_challenges', '{bad']]); const storage = { getItem: (k: string) => values.get(k) ?? null, setItem: (k: string, v: string) => { values.set(k, v); } }; const a = archiveLegacy(storage); expect(a.lessonIds).toEqual([1, 8]); expect(a.raw.electricity_completed_challenges).toBe('{bad'); expect(values.get('electricity_completed_challenges')).toBe('{bad'); expect(archiveLegacy(storage)).toEqual(a); const f = ioFixture(); expect((await claimLegacy('a', a, f.io)).ok).toBe(true); expect(f.get()[0].stars).toBe(7); expect((await claimLegacy('b', a, { ...f.io, isOwner: () => true })).ok).toBe(false); });
    it('documents isolate owners, preserve failure state, and copy conflicting revision', async () => { const c = preset(); c.parts[1].broken = true; c.parts[0].cells![0].charge01 = .31; const doc = createDocument('test-notebook', c, 'Mạch đã thử', 'bench', true); await saveDocument(doc); const read = await listDocuments('test-notebook'); expect(read[0].circuit.parts[1].broken).toBe(true); expect(read[0].circuit.parts[0].cells![0].charge01).toBe(.31); expect(await listDocuments('different-owner')).toHaveLength(0); const copy = await saveDocument(doc); expect(copy.id).not.toBe(doc.id); await clearElectricityData('test-notebook'); expect(await listDocuments('test-notebook')).toHaveLength(0); });
    it('rejects future schema, duplicate wires, invalid coordinates and oversized import', () => { const doc = createDocument('a', preset(), 'A', 'bench', false); expect(() => parseDocument(JSON.stringify({ ...doc, schema: 2 }))).toThrow(); doc.circuit.parts[0].x = NaN; expect(() => parseDocument(JSON.stringify(doc))).toThrow(); expect(() => parseDocument(' '.repeat(128 * 1024 + 1))).toThrow(); });
});
