import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import type {StudentProfile} from '../../types';
import type {Match,Player} from './model';
import {applyMove,newMatch,roll,validateMatch} from './engine';
import {loadDraft,saveDraft,loadParty,saveParty,persistResult,clearHorseData} from './persistence';
const party:Player[]=[{id:'host',name:'An',kind:'human',color:0,level:'medium',avatar:'avatar_01'},{id:'guest',name:'Bình',kind:'human',color:2,level:'medium',avatar:'avatar_02'}];
const profile=(id='owner'):StudentProfile=>({id,name:'An',age:8,grade:3,avatarId:0,currentAvatarId:'avatar_01',currentThemeId:'default',stars:30,ownedAvatarIds:[],ownedThemeIds:[],ownedImageIds:[],history:[],gameHistory:[],shopDailyPhotos:[]});
function win(who=0):Match{const s=newMatch('owner',party,'unique-match',who);s.pieces.splice(who*4,4,61,60,59,55);s.locked.splice(who*4,4,true,true,true,false);s.finished[who]=3;s.elapsed=125400;return applyMove(roll(s,3),who*4+3);}
beforeEach(()=>{const memory=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>memory.set(k,v),removeItem:(k:string)=>memory.delete(k)});});
afterEach(()=>vi.unstubAllGlobals());
describe('shared tablet saves and results',()=>{
 it('resumes the exact rolled die and legal phase without another throw',()=>{const s=roll(newMatch('owner',party,'id'),6);expect(saveDraft(s)).toBe(true);expect(loadDraft('owner')).toEqual({match:s,error:false});expect(loadDraft('other').match).toBeNull();});
 it('rejects malformed JSON, foreign owners, and unsupported rules',()=>{for(const raw of ['{',JSON.stringify({...win(),owner:'other'}),JSON.stringify({...win(),rulesVersion:9})]){localStorage.setItem('horse-race-draft-v1:owner',raw);expect(loadDraft('owner')).toEqual({match:null,error:true});}});
 it('reports unavailable storage without crashing the game',()=>{vi.stubGlobal('localStorage',{getItem:()=>{throw Error('denied');},setItem:()=>{throw Error('full');}});expect(saveDraft(win())).toBe(false);expect(loadDraft('owner').error).toBe(true);expect(loadParty('owner')).toBeNull();expect(()=>saveParty('owner',party)).not.toThrow();});
 it('validates party IDs, colors and the human host before restoring',()=>{saveParty('owner',party);expect(loadParty('owner')).toEqual(party);for(const bad of [[party[0],{...party[1],id:'host'}],[{...party[0],kind:'bot'},party[1]],[party[0],{...party[1],color:0}],[party[0],{...party[1],id:null}]]){saveParty('owner',bad as Player[]);expect(loadParty('owner')).toBeNull();}});
 it('writes only the host profile, keeps guest names local and awards no currency',()=>{const profiles=[profile(),profile('other')],before=structuredClone(profiles),write=vi.fn();const result=persistResult(profiles,'owner',win(),write);expect(result.ok).toBe(true);expect(write).toHaveBeenCalledWith(result.profiles);expect(profiles).toEqual(before);expect(result.profiles[1]).toBe(profiles[1]);expect(result.profiles[0].stars).toBe(30);expect(result.profiles[0].gameHistory[0]).toMatchObject({gameType:'horse-race',starsEarned:0,durationSeconds:125,horseRace:{hostWon:true,winner:'An'}});expect(result.profiles[0].stats?.gameWins['horse-race']).toBe(1);});
 it('records a guest victory without giving the host a win',()=>{const result=persistResult([profile()],'owner',win(1),()=>{});expect(result.ok).toBe(true);expect(result.profiles[0].stats?.gameWins['horse-race']).toBeUndefined();expect(result.profiles[0].gameHistory[0].horseRace).toMatchObject({hostWon:false,winner:'Bình'});});
 it('is idempotent when an ended game is reopened or its save is retried',()=>{const first=persistResult([profile()],'owner',win(),()=>{}),write=vi.fn(),again=persistResult(first.profiles,'owner',win(),write);expect(again.ok).toBe(true);expect(again.profiles).toBe(first.profiles);expect(write).not.toHaveBeenCalled();expect(again.profiles[0].stats?.totalGamesPlayed).toBe(1);});
 it('publishes nothing after a failed write and can retry successfully',()=>{const profiles=[profile()],before=structuredClone(profiles);const failed=persistResult(profiles,'owner',win(),()=>{throw Error('full');});expect(failed).toEqual({ok:false,profiles});expect(profiles).toEqual(before);const retry=persistResult(profiles,'owner',win(),()=>{});expect(retry.ok).toBe(true);expect(retry.profiles[0].gameHistory).toHaveLength(1);});
 it('rejects unfinished, corrupted, unknown-profile and cross-profile results',()=>{const s=win(),write=vi.fn();for(const [owner,state] of [['other',s],['owner',{...s,phase:'roll'}],['owner',{...s,finished:[4,4]}]] as [string,Match][]){expect(persistResult([profile()],owner,state,write).ok).toBe(false);}expect(persistResult([],'owner',s,write).ok).toBe(false);expect(write).not.toHaveBeenCalled();});
 it('rejects an unlocked horse already occupying a completed target',()=>{const s=newMatch('owner',party,'id');s.pieces[0]=61;expect(validateMatch(s)).toBe(false);});
 it('clears only the deleted profile’s party, draft and preferences',()=>{saveDraft(win());saveParty('owner',party);saveParty('other',party);localStorage.setItem('horse-race-prefs:owner','{}');clearHorseData('owner');expect(loadDraft('owner').match).toBeNull();expect(loadParty('owner')).toBeNull();expect(localStorage.getItem('horse-race-prefs:owner')).toBeNull();expect(loadParty('other')).toEqual(party);});
});
