import type { AlphabetActivity, AlphabetLevel, AlphabetOutcome } from './types';
export interface LetterPractice { solved: number; independent: number; assisted: number; recent: ('independent' | 'assisted' | 'retry')[]; lastPlayedAt: string }
export interface AlphabetPracticeProgress { version: 1; letters: Partial<Record<AlphabetActivity, Record<string, LetterPractice>>>; lastLevel: Partial<Record<AlphabetActivity, AlphabetLevel>>; lastScene: Partial<Record<AlphabetActivity, string>>; completedSessions: string[] }
const empty = (): AlphabetPracticeProgress => ({ version: 1, letters: {}, lastLevel: {}, lastScene: {}, completedSessions: [] });
const activity = (value: unknown): value is AlphabetActivity => ['word','match','pick'].includes(String(value));
export function readAlphabetPractice(value: unknown): AlphabetPracticeProgress {
    if (!value || typeof value !== 'object') return empty(); const raw = value as Partial<AlphabetPracticeProgress>, clean = empty();
    for (const [key, group] of Object.entries(raw.letters || {})) if (activity(key) && group && typeof group === 'object') { const output: Record<string, LetterPractice> = {};
        for (const [id, item] of Object.entries(group)) if (/^[a-z]$/.test(id) && item && typeof item === 'object') { const p = item as LetterPractice, solved = Number.isFinite(p.solved) ? Math.max(0, Math.floor(p.solved)) : 0; output[id] = { solved, independent: Math.min(solved, Math.max(0, Math.floor(p.independent || 0))), assisted: Math.min(solved, Math.max(0, Math.floor(p.assisted || 0))), recent: Array.isArray(p.recent) ? p.recent.filter(x => ['independent','assisted','retry'].includes(x)).slice(-5) : [], lastPlayedAt: typeof p.lastPlayedAt === 'string' ? p.lastPlayedAt : '' }; } clean.letters[key] = output; }
    clean.lastLevel = Object.fromEntries(Object.entries(raw.lastLevel || {}).filter(([key,value]) => activity(key) && ['intro','practice','challenge'].includes(String(value)))) as AlphabetPracticeProgress['lastLevel'];
    clean.lastScene = Object.fromEntries(Object.entries(raw.lastScene || {}).filter(([key,value]) => activity(key) && typeof value === 'string')); clean.completedSessions = Array.isArray(raw.completedSessions) ? [...new Set(raw.completedSessions.filter(id => typeof id === 'string'))].slice(-100) : []; return clean;
}
export function recordOutcome(value: unknown, activityId: AlphabetActivity, outcome: AlphabetOutcome, at = new Date().toISOString()) {
    const progress = readAlphabetPractice(value), group = { ...(progress.letters[activityId] || {}) }, old = group[outcome.letterId] || { solved: 0, independent: 0, assisted: 0, recent: [], lastPlayedAt: '' };
    const kind: LetterPractice['recent'][number] = outcome.assisted ? 'assisted' : outcome.firstTry && outcome.correct ? 'independent' : 'retry'; group[outcome.letterId] = { solved: old.solved + (outcome.correct ? 1 : 0), independent: old.independent + (kind === 'independent' ? 1 : 0), assisted: old.assisted + (kind === 'assisted' ? 1 : 0), recent: [...old.recent, kind].slice(-5), lastPlayedAt: at };
    return { ...progress, letters: { ...progress.letters, [activityId]: group } };
}
export function completePracticeSession(value: unknown, activityId: AlphabetActivity, level: AlphabetLevel, sessionId: string, outcomes: AlphabetOutcome[], scene: string) { let progress = readAlphabetPractice(value); if (progress.completedSessions.includes(sessionId)) return progress; for (const outcome of outcomes) progress = recordOutcome(progress, activityId, outcome); return { ...progress, lastLevel: { ...progress.lastLevel, [activityId]: level }, lastScene: { ...progress.lastScene, [activityId]: scene }, completedSessions: [...progress.completedSessions, sessionId].slice(-100) }; }
export const mastered = (value: unknown, activityId: AlphabetActivity, letterId: string) => { const item = readAlphabetPractice(value).letters[activityId]?.[letterId]; return !!item && item.independent >= 3 && item.recent.slice(-2).every(x => x === 'independent'); };
