import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Html,RoundedBox} from '@react-three/drei';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {BOARD,point,lotPoint,facing,tokenPoint} from './board';
import {buildingGeometry,characterGeometry,sceneryGeometry,tramGeometry,roadGeometry} from './geometry';
import BoardCamera from './BoardCamera';
import {COLORS,type Match,type TownEvent} from './model';
export interface BoardProps {s:Match;positions:number[];selected:number|null;onPick:(id:number)=>void;intro:boolean;onIntroEnd:()=>void;paused:boolean;reduced:boolean;light:boolean;onReady:()=>void;onFailure:()=>void;motion?:TownEvent;eventId:string;duration:number;canRoll:boolean;onRoll:()=>void;action:ReactNode;view:number}
function Building({id,p}:{id:number;p:BoardProps}){
 const prop=p.s.properties[id],[shownLevel,setShownLevel]=useState(prop.level),ref=useRef<T.Group>(null),pulse=useRef<T.Mesh>(null),growth=useRef(1);
 const geo=useMemo(()=>buildingGeometry(id,shownLevel,prop.owner),[id,shownLevel,prop.owner]);useEffect(()=>()=>geo.dispose(),[geo]);
 useEffect(()=>{if(prop.level===shownLevel)return;if(p.reduced||!p.motion||p.motion.kind==='build'&&p.motion.tile===id){growth.current=p.reduced?1:0;setShownLevel(prop.level);}},[prop.level,shownLevel,p.motion,p.reduced,id]);
 useFrame((_,dt)=>{if(p.paused)return;growth.current=Math.min(1,growth.current+Math.min(dt,.05)/1.15);const u=growth.current;if(ref.current){const scale=.90+.10*(1-Math.pow(1-u,3));ref.current.scale.setScalar(scale);ref.current.position.y=Math.sin(u*Math.PI)*.07;}if(pulse.current){pulse.current.visible=u<1;pulse.current.scale.setScalar(.7+u*.7);(pulse.current.material as T.MeshBasicMaterial).opacity=(1-u)*.7;}});
 return <group position={lotPoint(id)} rotation={[0,facing(id),0]}><group ref={ref}><mesh geometry={geo} castShadow receiveShadow onClick={e=>{e.stopPropagation();if(e.delta<6&&!p.intro)p.onPick(id);}}><meshPhysicalMaterial vertexColors roughness={.72} clearcoat={.14}/></mesh></group>
 {prop.owner!==null&&<><mesh position={[-.64,.38,.58]}><cylinderGeometry args={[.024,.024,.55,6]}/><meshStandardMaterial color='#8b704f'/></mesh><mesh position={[-.52,.59,.58]}><boxGeometry args={[.25,.16,.025]}/><meshStandardMaterial color={COLORS[prop.owner]}/></mesh></>}
 <mesh ref={pulse} visible={false} rotation={[-Math.PI/2,0,0]} position={[0,.18,0]}><ringGeometry args={[.79,.87,48]}/><meshBasicMaterial color='#ffe7a0' transparent depthWrite={false}/></mesh>
 {p.selected===id&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.17,0]}><ringGeometry args={[.76,.82,48]}/><meshBasicMaterial color='#fff3ba'/></mesh>}</group>;
}
function RoadTile({id,p}:{id:number;p:BoardProps}){const prop=p.s.properties[id],geo=useMemo(()=>roadGeometry(id,prop.owner===null?undefined:COLORS[prop.owner]),[id,prop.owner]);useEffect(()=>()=>geo.dispose(),[geo]);return <group position={point(id)} rotation={[0,facing(id),0]}><mesh geometry={geo} receiveShadow onClick={e=>{e.stopPropagation();if(e.delta<6&&!p.intro)p.onPick(id);}}><meshStandardMaterial vertexColors roughness={.9}/></mesh>{p.selected===id&&<mesh position={[0,.10,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.48,.53,32]}/><meshBasicMaterial color='#dfae62'/></mesh>}{!p.intro&&<Html position={[0,.14,.45]} center zIndexRange={[6,0]}><button className={'town-pin'+(p.selected===id?' chosen':'')} onClick={()=>p.onPick(id)} aria-label={`Xem ${BOARD[id].name}`} title={BOARD[id].name}><span>{BOARD[id].icon}</span>{prop.owner!==null?<b style={{color:COLORS[prop.owner]}}>{prop.owner+1}{prop.level?' · '+prop.level+'★':''}</b>:BOARD[id].price?<small>{BOARD[id].price}</small>:null}</button></Html>}</group>;}
function Tokens(p:BoardProps){const groups=[useRef<T.Group>(null),useRef<T.Group>(null),useRef<T.Group>(null),useRef<T.Group>(null)],geos=useMemo(()=>COLORS.map((c,i)=>characterGeometry(i,c)),[]),elapsed=useRef(0);useEffect(()=>()=>geos.forEach(g=>g.dispose()),[geos]);useEffect(()=>{elapsed.current=0;},[p.eventId]);
 useFrame((_,dt)=>{if(!p.paused)elapsed.current+=Math.min(dt,.05)*1000;p.s.players.forEach((player,i)=>{const g=groups[i].current;if(!g)return;g.visible=!player.bankrupt;const pos=p.positions[i],base=tokenPoint(pos,i);let [x,y,z]=base,angle=pos===0?Math.PI/4+[-.15,.13,-.09,.20][i]:facing(pos);
 if(p.motion?.kind==='move'&&p.motion.seat===i){const path=p.motion.path!,f=Math.min(1,elapsed.current/p.duration)*(path.length-1),index=Math.min(path.length-2,Math.floor(f)),u=f-index,a=tokenPoint(path[index],i),b=tokenPoint(path[index+1],i);x=T.MathUtils.lerp(a[0],b[0],u);z=T.MathUtils.lerp(a[2],b[2],u);const tile=path[Math.min(index+1,path.length-1)];angle=tile===0?Math.PI/4:facing(tile);y+=Math.sin(u*Math.PI)*.16;}g.position.set(x,y,z);g.rotation.y=angle;});});
 return <>{p.s.players.map((_,i)=><group key={i} ref={groups[i]} scale={.7}><mesh geometry={geos[i]} castShadow receiveShadow><meshPhysicalMaterial vertexColors roughness={.5} clearcoat={.25}/></mesh></group>)}</>;
}
function Dice({value,x,p}:{value:number;x:number;p:BoardProps}){const ref=useRef<T.Group>(null),time=useRef(0);useEffect(()=>{time.current=0;},[p.eventId]);useFrame((_,dt)=>{if(!ref.current||p.paused)return;time.current+=Math.min(dt,.05);const u=Math.min(1,time.current/.75),rolling=p.motion?.kind==='dice'&&!p.reduced&&u<1;ref.current.rotation.set(rolling?(1-u)*Math.PI*4:.05,rolling?(1-u)*Math.PI*3:x*.2,rolling?Math.sin(u*Math.PI)*.7:0);ref.current.position.y=.47+(rolling?Math.sin(u*Math.PI)*.65:0);});const dots:Record<number,[number,number][]>={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[1,-1],[-1,1],[1,1]],5:[[-1,-1],[1,-1],[0,0],[-1,1],[1,1]],6:[[-1,-1],[1,-1],[-1,0],[1,0],[-1,1],[1,1]]};return <group ref={ref} position={[x,.47,3.9]} rotation={[.05,x*.2,0]}><RoundedBox args={[.72,.72,.72]} radius={.1} castShadow><meshPhysicalMaterial color='#fff2d6' roughness={.35} clearcoat={.35}/></RoundedBox>{dots[value].map(([a,b],i)=><mesh key={i} position={[a*.18,.367,b*.18]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.055,12]}/><meshBasicMaterial color='#405e58'/></mesh>)}</group>;}
function Tram({paused}:{paused:boolean}){const geo=useMemo(tramGeometry,[]),ref=useRef<T.Mesh>(null),time=useRef(0);useEffect(()=>()=>geo.dispose(),[geo]);useFrame((_,dt)=>{if(paused||!ref.current)return;time.current+=Math.min(dt,.05)*.008;const a=(time.current%1)*Math.PI*2,r=5.42,k=Math.max(Math.abs(Math.cos(a)),Math.abs(Math.sin(a)));ref.current.position.set(Math.cos(a)/k*r,.1,Math.sin(a)/k*r);ref.current.rotation.y=Math.abs(Math.cos(a))>Math.abs(Math.sin(a))?Math.PI/2:0;});return <mesh ref={ref} geometry={geo} scale={.7} castShadow><meshStandardMaterial vertexColors roughness={.6}/></mesh>;}
function Scene(p:BoardProps){const {gl,scene}=useThree(),scenery=useMemo(sceneryGeometry,[]);useEffect(()=>()=>scenery.dispose(),[scenery]);useEffect(()=>{const room=new RoomEnvironment(),gen=new T.PMREMGenerator(gl),env=gen.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.45;room.dispose();gen.dispose();return()=>{scene.environment=null;env.dispose();};},[gl,scene]);useEffect(()=>{p.onReady();},[p.s.id,p.onReady]);useEffect(()=>{const lost=(e:Event)=>{e.preventDefault();p.onFailure();};gl.domElement.addEventListener('webglcontextlost',lost);return()=>gl.domElement.removeEventListener('webglcontextlost',lost);},[gl,p.onFailure]);useEffect(()=>{if(!import.meta.env.DEV)return;const id=setInterval(()=>{gl.domElement.dataset.drawCalls=String(gl.info.render.calls);gl.domElement.dataset.triangles=String(gl.info.render.triangles);},1500);return()=>clearInterval(id);},[gl]);
 const measure=useRef({start:performance.now(),frames:0});useFrame(()=>{if(!import.meta.env.DEV)return;const m=measure.current;m.frames++;const now=performance.now();if(now-m.start>1000){gl.domElement.dataset.fps=(m.frames*1000/(now-m.start)).toFixed(1);m.start=now;m.frames=0;}});
 return <><BoardCamera {...p}/><color attach='background' args={['#e7d7b9']}/><fog attach='fog' args={['#e7d7b9',120,210]}/><ambientLight intensity={.12}/><hemisphereLight args={['#fff1d7','#6b8667',.55]}/><directionalLight position={[-10,18,8]} intensity={1.5} castShadow={!p.light} shadow-mapSize={[2048,2048]} shadow-camera-left={-14} shadow-camera-right={14} shadow-camera-top={14} shadow-camera-bottom={-14} shadow-normalBias={.025}/>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,-.69,0]} receiveShadow><planeGeometry args={[200,200]}/><meshStandardMaterial color='#d0bb97' roughness={1}/></mesh><mesh geometry={scenery} castShadow receiveShadow><meshStandardMaterial vertexColors roughness={.85}/></mesh>
 {BOARD.map(t=><Building key={t.id} id={t.id} p={p}/>)}{BOARD.map(t=><RoadTile key={t.id} id={t.id} p={p}/>)}<Tokens {...p}/><Dice value={p.s.dice[0]} x={-.47} p={p}/><Dice value={p.s.dice[1]} x={.47} p={p}/>{!p.light&&<Tram paused={p.paused||p.reduced}/>}
 {!p.intro&&p.canRoll&&<Html center position={[0,.9,4]} zIndexRange={[12,10]}><button className='town-roll' onClick={p.onRoll}>Gieo xúc xắc <span>⚄</span></button></Html>}
 </>;
}
export default function Board3D(p:BoardProps){return <><Canvas camera={{position:[17,24,28],fov:37,near:.1,far:200}} shadows={!p.light} dpr={p.light?1:[1,1.5]} frameloop={p.paused?'demand':'always'} gl={{antialias:true,powerPreference:'high-performance'}} aria-label='Sa bàn Phố Nhỏ Tỉ Phú 3D'><Scene {...p}/></Canvas>{p.action}</>;}
