export type TileKind='shop'|'station'|'utility'|'start'|'rest'|'festival'|'repair'|'community'|'chance'|'fee';
export interface Tile {id:number;name:string;icon:string;kind:TileKind;group:number;price:number;fee?:number}
export const GROUPS=[{name:'Ẩm thực',color:'#e9a077',icon:'🥐',price:200,upgrade:100,rents:[40,150,400]},{name:'Sáng tạo',color:'#e0bd60',icon:'🎨',price:240,upgrade:120,rents:[50,180,480]},{name:'Thiên nhiên',color:'#79b79b',icon:'🌿',price:280,upgrade:140,rents:[60,210,560]},{name:'Vận động',color:'#76b6cc',icon:'⚽',price:320,upgrade:160,rents:[70,240,640]},{name:'Chăm sóc',color:'#c296bb',icon:'🐾',price:360,upgrade:180,rents:[80,270,720]},{name:'Giải trí',color:'#da8d86',icon:'🎡',price:400,upgrade:200,rents:[90,300,800]}];
const names=['Bắt đầu','Tiệm bánh','Chuyện khu phố','Quán nước','Tiệm kem','Bến xe điện Đông','Nhà sách','Chăm sóc phố','Nhà tù · Thăm bạn','Xưởng vẽ','Tiệm đồ chơi','Trạm điện mặt trời','Vườn hoa','Cơ hội','Tiệm cây','Nông trại nhỏ','Rương kỳ diệu','Tiệm xe đạp','Chuyện khu phố','Sân bóng','Hồ bơi','Bến xe điện Tây','Tiệm thú cưng','Bảo dưỡng phố','Hộp bất ngờ','Phòng khám thú cưng','Tiệm làm đẹp thú cưng','Trạm nước sạch','Rạp phim','Cơ hội','Sân khấu','Khu vui chơi'];
const icons=['🏁','🥐','✉','☕','🍦','🚋','📚','🌱','🔒','🎨','🧸','☀','🌷','✦','🪴','🥕','🎁','🚲','✉','⚽','🏊','🚋','🐾','🧹','❔','🏥','🎀','💧','🎬','✦','🎭','🎡'];
const groups=[[1,3,4],[6,9,10],[12,14,15],[17,19,20],[22,25,26],[28,30,31]];
const specials:Record<number,TileKind>={0:'start',2:'community',5:'station',7:'fee',8:'rest',11:'utility',13:'chance',16:'festival',18:'community',21:'station',23:'fee',24:'repair',27:'utility',29:'chance'};
export const BOARD:Tile[]=names.map((name,id)=>{const group=groups.findIndex(g=>g.includes(id)),kind=specials[id]||'shop';return{id,name,icon:icons[id],kind,group,price:group>=0?GROUPS[group].price:kind==='station'?300:kind==='utility'?240:0,fee:id===7?200:id===23?100:undefined};});
export const LOT_SPACING=1.85;
export function lotPoint(id:number):[number,number,number]{const side=Math.floor(id/8),n=id%8,s=LOT_SPACING;return side===0?[(4-n)*s,0,4*s]:side===1?[-4*s,0,(4-n)*s]:side===2?[(n-4)*s,0,-4*s]:[4*s,0,(n-4)*s];}
// The token lane sits outside the plots. Corner tiles form an L around their lot.
export function point(id:number):[number,number,number]{const side=Math.floor(id/8),n=id%8,[x,,z]=lotPoint(id),r=9.15;if(n===0)return [[r,0,r],[-r,0,r],[-r,0,-r],[r,0,-r]][side] as [number,number,number];return side===0?[x,0,r]:side===1?[-r,0,z]:side===2?[x,0,-r]:[r,0,z];}
export function facing(id:number){return -Math.floor(id/8)*Math.PI/2;}
export function tokenPoint(id:number,seat:number):[number,number,number]{const [x,,z]=point(id);if(id===0){const slots=[[-1.45,.05],[-.50,.45],[.30,-.45],[.15,-1.45]];return[x+slots[seat][0],.12,z+slots[seat][1]];}const angle=facing(id),out=seat%2?-.25:.16,side=seat<2?-.22:.22;return[x+Math.sin(angle)*out+Math.cos(angle)*side,.12,z+Math.cos(angle)*out-Math.sin(angle)*side];}
