
import {describe,it,expect} from 'vitest';
import {createMatch,reduce,actor,validateMatch} from './engine';
import {assets,rent,canUpgrade} from './economy';
import {choose,observation} from './bot';
import {BOARD,point,lotPoint} from './board';
import {next} from './rng';
import {CARD_TEXT} from './cards';
import type {Match,Command,Player} from './model';
const party:Player[]=[{name:'An',kind:'human',skill:'medium',cash:1500,position:0},{name:'Máy',kind:'bot',skill:'medium',cash:1500,position:0}];
const fresh=(seed=42,count=2)=>{const s=createMatch('owner',Array.from({length:count},(_,i)=>({...party[i%2],name:'P'+i})),'family',seed,'test');s.first=s.active=0;return s;};
const act=(s:Match,command:Command)=>reduce(s,{id:s.id,revision:s.revision,actor:actor(s),command});
function card(s:Match,key:string){const deck=key.startsWith('chance')?'chance':'community',id=s.decks[deck].find(id=>id.startsWith(key))!;s.decks[deck]=s.decks[deck].filter(c=>c!==id);s.card=id;s.phase='card';return s;}
function cash(s:Match,seat:number,value:number){s.bank+=s.players[seat].cash-value;s.players[seat].cash=value;}
function rngFor(a:number,b:number){for(let seed=0;seed<10000;seed++){const [r,n]=next(seed),[v]=next(n);if(Math.floor(r*6)+1===a&&Math.floor(v*6)+1===b)return seed;}throw Error('dice');}
describe('Property Town simplified rules',()=>{
 it('resolves each of the 20 events once while conserving the cash ledger and full deck',()=>{for(const key of Object.keys(CARD_TEXT)){let s=card(fresh(),key);const n=act(s,{type:'card'});expect(n).not.toBe(s);expect(n.card).toBe(null);expect(validateMatch(n,'owner'),key).toBe(true);expect(act(n,{type:'card'})).toBe(n);}});
 it('has a separate 32-space road, 18 shops and six groups',()=>{expect(new Set(BOARD.map(t=>point(t.id).join(','))).size).toBe(32);expect(BOARD.filter(t=>t.kind==='shop')).toHaveLength(18);for(const t of BOARD)expect(point(t.id)).not.toEqual(lotPoint(t.id));expect(validateMatch(fresh(),'owner')).toBe(true);});
 it('starts at 1500 and rejects stale/wrong-seat/duplicate commands',()=>{const s=fresh();expect(s.players[0].cash).toBe(1500);expect(reduce(s,{id:s.id,revision:1,actor:0,command:{type:'roll'}})).toBe(s);expect(reduce(s,{id:s.id,revision:0,actor:1,command:{type:'roll'}})).toBe(s);const a={id:s.id,revision:0,actor:0,command:{type:'roll'} as Command},n=reduce(s,a);expect(reduce(n,a)).toBe(n);expect(s.revision).toBe(0);});
 it('buys then immediately passes the turn; declining never auctions',()=>{let s=fresh();s.players[0].position=1;s.phase='buy';const declined=act(s,{type:'decline'});expect(declined.properties[1].owner).toBe(null);expect(declined.active).toBe(1);s=act(s,{type:'buy'});expect(s.players[0].cash).toBe(1300);expect(s.active).toBe(1);expect(s.phase).toBe('roll');expect(assets(s,0)).toBe(1500);});
 it('allows a first expansion, caps one build per turn and requires a color set for the highest stage',()=>{let s=fresh();s.properties[1].owner=0;expect(canUpgrade(s,1,0)).toBe(true);s=act(s,{type:'upgrade',tile:1});expect(s.properties[1].level).toBe(1);expect(s.builtThisTurn).toBe(true);expect(s.active).toBe(0);expect(act(s,{type:'upgrade',tile:1})).toBe(s);s.builtThisTurn=false;expect(canUpgrade(s,1,0)).toBe(false);s.properties[3].owner=s.properties[4].owner=0;s=act(s,{type:'upgrade',tile:1});expect(s.properties[1].level).toBe(2);expect(rent(s,1)).toBe(400);expect(s.players[0].cash).toBe(1300);});
 it('awards GO once when crossing it, including a double',()=>{let s=fresh();s.players[0].position=30;s.rng=rngFor(2,2);s=act(s,{type:'roll'});expect(s.players[0].position).toBe(2);expect(s.players[0].cash).toBe(1700);expect(s.extraRoll).toBe(true);});
 it('gives an extra roll after a double and preserves the streak through buying',()=>{let s=fresh();s.players[0].position=1;s.rng=rngFor(2,2);s=act(s,{type:'roll'});expect(s.phase).toBe('buy');s=act(s,{type:'buy'});expect(s.active).toBe(0);expect(s.doubles).toBe(1);expect(s.phase).toBe('roll');s.rng=rngFor(1,2);s=act(s,{type:'roll'});expect(s.active).toBe(1);expect(s.doubles).toBe(0);});
 it('third double sends to jail without moving past GO or awarding 200',()=>{let s=fresh();s.players[0].position=30;s.doubles=2;s.rng=rngFor(2,2);s=act(s,{type:'roll'});expect(s.players[0].position).toBe(8);expect(s.players[0].jailed).toBe(true);expect(s.players[0].cash).toBe(1500);expect(s.active).toBe(1);expect(validateMatch(s,'owner')).toBe(true);});
 it('jail can be paid before rolling; a successful double escapes without bonus roll',()=>{let s=fresh();s.players[0].jailed=true;s.players[0].position=8;s.phase='jail';const paid=act(s,{type:'bail'});expect(paid.players[0].cash).toBe(1450);expect(paid.phase).toBe('roll');s.rng=rngFor(2,2);s=act(s,{type:'jail-roll'});expect(s.players[0].jailed).toBe(false);expect(s.extraRoll).toBe(false);s=act(s,{type:'decline'});expect(s.active).toBe(1);});
 it('third failed jail attempt charges 50 and advances by the dice',()=>{let s=fresh();s.players[0].jailed=true;s.players[0].position=8;s.players[0].jailAttempts=2;s.phase='jail';s.rng=rngFor(1,2);s=act(s,{type:'jail-roll'});expect(s.players[0].cash).toBe(1450);expect(s.players[0].position).toBe(11);expect(s.players[0].jailed).toBe(false);expect(validateMatch(s,'owner')).toBe(true);});
 it('eliminates only the insolvent debtor and transfers property and remaining cash to the creditor',()=>{let s=fresh(42,3);cash(s,0,30);s.properties[1].owner=1;s.properties[6].owner=0;s.players[0].position=4;s=act(card(s,'chance-2'),{type:'card'});expect(s.players[0].bankrupt).toBe(true);expect(s.properties[6].owner).toBe(1);expect(s.players[1].cash).toBe(1530);expect(s.phase).not.toBe('over');expect(s.active).toBe(1);expect(validateMatch(s,'owner')).toBe(true);});
 it('bank insolvency resets title and upgrades and declares the remaining winner',()=>{let s=fresh();cash(s,0,10);s.properties[1]={owner:0,level:2};s=act(card(s,'community-2'),{type:'card'});expect(s.properties[1]).toEqual({owner:null,level:0});expect(s.phase).toBe('over');expect(validateMatch(s,'owner')).toBe(true);});
 it('movement cards do not chain another card and all cards remain public single-use events',()=>{let s=fresh();s.players[0].position=5;s=act(card(s,'chance-2'),{type:'card'});expect(s.players[0].position).toBe(2);expect(s.card).toBe(null);expect(validateMatch(s,'owner')).toBe(true);expect(observation(s)).not.toHaveProperty('rng');expect(observation(s)).not.toHaveProperty('decks');});
 it('corner surprises draw cards and bonus dice never reset the construction limit',()=>{let s=fresh();s.players[0].position=22;s.rng=rngFor(1,1);s.builtThisTurn=true;const id=s.decks.chance.find(c=>c.startsWith('chance-6'))!;s.decks.chance=s.decks.chance.filter(c=>c!==id);s.decks.chance.push(id);s=act(s,{type:'roll'});expect(s.phase).toBe('card');expect(s.card).toBe(id);s=act(s,{type:'card'});expect(s.active).toBe(0);expect(s.bonusRolls).toBe(1);expect(s.builtThisTurn).toBe(true);s.properties[27].owner=0;s.rng=rngFor(1,2);s=act(s,{type:'roll'});expect(s.active).toBe(0);expect(s.bonusRolls).toBe(0);expect(s.builtThisTurn).toBe(true);s.properties[30].owner=0;s.rng=rngFor(1,2);s=act(s,{type:'roll'});expect(s.active).toBe(1);expect(s.builtThisTurn).toBe(false);expect(validateMatch(s,'owner')).toBe(true);});
 it('has exactly 20 unique public events and a jail event without GO payment',()=>{let s=fresh();expect([...s.decks.chance,...s.decks.community]).toHaveLength(20);s.players[0].position=29;s=act(card(s,'chance-5'),{type:'card'});expect(s.players[0].jailed).toBe(true);expect(s.players[0].cash).toBe(1500);expect(validateMatch(s,'owner')).toBe(true);});
 it('keeps valid decisions and money throughout 90 bounded simulations without imposing a round deadline',()=>{for(let seed=1;seed<=90;seed++){let s=fresh(seed,2+seed%3),steps=0;while(s.phase!=='over'&&steps++<400){const n=act(s,choose(observation(s)));expect(n,'stuck seed '+seed).not.toBe(s);s=n;expect(validateMatch(s,'owner'),'seed '+seed+' turn '+s.turn+' phase '+s.phase).toBe(true);}if(s.phase==='over')expect(s.players.filter(p=>!p.bankrupt)).toHaveLength(1);else expect(s.turn).toBeGreaterThan(0);}},60000);
});

