import {StrictMode,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PropertyTown} from './PropertyTownGame';
import {createMatch} from './engine';
import {BOARD} from './board';
import {CARD_TEXT} from './cards';
import type {Match,Player} from './model';
const party:Player[]=[{name:'Minh Anh',kind:'human',skill:'medium',cash:1500,position:0},{name:'Máy Cáo',kind:'bot',skill:'medium',cash:1500,position:0}];
function fixture(type:string){const people=['four','colors'].includes(type)?Array.from({length:4},(_,i)=>({...party[0],name:['Minh Anh','Bảo An','Khánh Linh','Gia Huy'][i]})):party;const s=createMatch('town-preview',people,'family',34);s.first=s.active=0;if(type==='colors')BOARD.forEach(t=>{if(t.price)s.properties[t.id]={owner:t.group>=0?t.group%4:t.id%4,level:t.kind==='shop'?1:0};});if(['city','stage0','stage1','stage2','build'].includes(type)){BOARD.forEach(t=>{if(t.price)s.properties[t.id]={owner:type==='build'?0:t.group>=0?t.group%2:t.id%2,level:t.kind==='shop'?(type==='city'||type==='stage2'?2:type==='stage1'?1:0):0};});s.players[0].position=1;}if(type==='buy'){s.players[0].position=1;s.phase='buy';}if(type==='bot-first')s.first=s.active=1;if(type==='jail'){s.players[0].position=8;s.players[0].jailed=true;s.phase='jail';}if(type==='card'||type.startsWith('event:')){s.phase='card';const key=type==='card'?'community-0':type.slice(6),deck=key.startsWith('community')?'community':'chance',id=s.decks[deck].find(id=>id.startsWith(key))!;s.decks[deck]=s.decks[deck].filter(c=>c!==id);s.card=id;}return s;}
function Preview(){const [initial,setInitial]=useState<Match>(),[key,setKey]=useState(0);const open=(type:string)=>{setInitial(type==='lobby'?undefined:fixture(type));setKey(k=>k+1);};return <><details className='town-dev' style={{position:'fixed',zIndex:200,left:'50%',top:0,transform:'translateX(-50%)',fontSize:10,background:'#224f46',color:'#fff',padding:'3px 8px',borderRadius:6}}><summary>DEV · Phố Nhỏ</summary>{[['lobby','Sảnh'],['board','Bàn mới'],['four','4 người xuất phát'],['colors','4 màu sở hữu'],['city','Phố nâng cấp'],['buy','Mua tiệm'],['stage0','Cấp đầu'],['stage1','Mở rộng'],['stage2','Nổi bật'],['build','Thử xây'],['jail','Nhà tù'],['card','Sự kiện'],['bot-first','Máy đi trước']].map(([id,title])=><button key={id} onClick={()=>open(id)}>{title}</button>)}<select aria-label='Thẻ sự kiện thử nghiệm' defaultValue='' onChange={e=>open('event:'+e.target.value)}><option value='' disabled>Thử 20 thẻ</option>{Object.entries(CARD_TEXT).map(([id,card])=><option key={id} value={id}>{card[0]}</option>)}</select><button onClick={()=>document.querySelector('canvas')?.getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext()}>Mất WebGL</button></details><PropertyTown key={key} owner='town-preview' name='Minh Anh' onExit={()=>open('lobby')} complete={()=>({ok:true})} initialMatch={initial}/></>;}
if(import.meta.env.DEV){const node=document.getElementById('root')!;const root=import.meta.hot?.data.root??createRoot(node);if(import.meta.hot)import.meta.hot.data.root=root;root.render(<StrictMode><Preview/></StrictMode>);}
