import { BoardGamesBack } from '../shared/BoardGamesBack';
import React,{Component,lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Bot,Check,ChevronRight,Flag,HelpCircle,Home,Pause,Play,RotateCcw,Settings2,Volume2,VolumeX,X} from 'lucide-react';
import {useStudent,useStudentActions} from '../../src/contexts/StudentContext';
import {BOARD,GROUPS} from './board';
import {DEVELOPMENTS} from './development';
import {CARD_TEXT,cardKey,cardMood} from './cards';
import {actor,createMatch,legal,partyValid,reduce,winners} from './engine';
import {assets,canUpgrade,fullGroup,rent,upgradeCost} from './economy';
import {choose,observation} from './bot';
import {loadDraft,saveDraft} from './persistence';
import {eventDuration,sound,closeAudio} from './animation';
import {ANIMALS,COLORS,type Command,type Match,type Mode,type Player,type TownEvent} from './model';
import Board2D from './Board2D';
import './town.css';
const Board3D=lazy(()=>import('./Board3D'));
const cover=`${import.meta.env.BASE_URL}co-ti-phu/art/cover.webp`;
const faces=['🐻','🦊','🐰','🐱'];
interface Prefs {sound:boolean;reduced:boolean;light:boolean;flat:boolean}
function prefsFor(owner:string):Prefs{const d={sound:true,reduced:window.matchMedia('(prefers-reduced-motion: reduce)').matches,light:false,flat:false};try{const saved=JSON.parse(localStorage.getItem(`property-town-prefs:${owner}`)||'{}');return Object.fromEntries(Object.entries(d).map(([k,v])=>[k,typeof saved[k]==='boolean'?saved[k]:v])) as unknown as Prefs;}catch{return d;}}
class Boundary extends Component<{children:React.ReactNode;fallback:React.ReactNode;onFail:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}componentDidCatch(){this.props.onFail();}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog className='town-dialog' ref={ref} onCancel={e=>{e.preventDefault();onClose();}}><header><h2>{title}</h2><button aria-label='Đóng' onClick={onClose}><X/></button></header>{children}</dialog>;}
const player=(name:string,kind:'human'|'bot'):Player=>({name,kind,skill:'medium',cash:1500,position:0});
export interface TownProps {owner:string;name:string;onExit:()=>void;complete:(owner:string,s:Match)=>{ok:boolean};initialMatch?:Match}
export function PropertyTown({owner,name,onExit,complete,initialMatch}:TownProps){
 const [s,setS]=useState<Match|null>(initialMatch||null),[draft,setDraft]=useState(()=>loadDraft(owner)),[party,setParty]=useState<Player[]>([player(name,'human'),player('Máy Cáo','bot')]),[prefs,setPrefs]=useState(()=>prefsFor(owner)),[intro,setIntro]=useState(false),[ready,setReady]=useState(false),[paused,setPaused]=useState(false),[modal,setModal]=useState<'rules'|'settings'|'log'|number|null>(null),[selected,setSelected]=useState<number|null>(null),[positions,setPositions]=useState(initialMatch?.players.map(p=>p.position)||[]),[queue,setQueue]=useState<TownEvent[]>([]),[eventIndex,setEventIndex]=useState(0),[view,setView]=useState(0),[saveError,setSaveError]=useState(false),[resultSaved,setResultSaved]=useState(false);
 const current=useRef(s),blocked=useRef(true),remain=useRef(0),event=queue[eventIndex],busy=!!event,freeze=paused||modal!==null;current.current=s;blocked.current=!ready||intro||freeze||busy;
 const onReady=useCallback(()=>setReady(true),[]),onIntroEnd=useCallback(()=>setIntro(false),[]),onFailure=useCallback(()=>{setPrefs(p=>({...p,flat:true}));setIntro(false);setReady(true);},[]);
 useEffect(()=>()=>closeAudio(),[]);
 useEffect(()=>{try{localStorage.setItem(`property-town-prefs:${owner}`,JSON.stringify(prefs));}catch{/* Preferences are optional. */}if(prefs.reduced)setIntro(false);},[prefs,owner]);
 useEffect(()=>{if(s)setSaveError(!saveDraft(s));},[s]);
 useEffect(()=>{if(!s||freeze||intro||s.phase==='over')return;const timer=setInterval(()=>setS(prev=>prev?{...prev,elapsed:prev.elapsed+10000}:prev),10000);return()=>clearInterval(timer);},[s?.id,s?.phase,freeze,intro]);
 useEffect(()=>{if(s?.phase==='over'&&!busy&&!resultSaved)setResultSaved(complete(owner,s).ok);},[s?.id,s?.phase,busy,resultSaved,owner,complete]);
 useEffect(()=>{if(!event)return;remain.current=eventDuration(event,prefs.reduced);if(prefs.sound)sound(event.kind);},[s?.revision,eventIndex]);
 useEffect(()=>{if(!event||freeze)return;let previous=performance.now();const timer=setInterval(()=>{const now=performance.now();remain.current-=Math.min(100,now-previous);previous=now;if(remain.current<=0){clearInterval(timer);if(event.kind==='move')setPositions(p=>p.map((pos,i)=>i===event.seat?event.path!.at(-1)!:pos));setEventIndex(i=>i+1);}},40);return()=>clearInterval(timer);},[event,eventIndex,freeze]);
 const dispatch=useCallback((command:Command)=>{const old=current.current;if(!old||blocked.current)return;const next=reduce(old,{id:old.id,revision:old.revision,actor:actor(old),command});if(next===old)return;current.current=next;blocked.current=next.events.length>0;setPositions(old.players.map(p=>p.position));setQueue(next.events);setEventIndex(0);setS(next);setSelected(command.type==='upgrade'?command.tile:null);if(command.type==='roll'&&prefs.sound)sound('roll');},[prefs.sound]);
 useEffect(()=>{if(!s||blocked.current||s.phase==='over'||s.players[actor(s)].kind!=='bot')return;const snap=s,requestId=`${s.id}:${s.revision}`;let worker:Worker|undefined,timeout:ReturnType<typeof setTimeout>|undefined;let live=true;const done=(command:Command)=>{if(!live)return;live=false;worker?.terminate();if(timeout)clearTimeout(timeout);const now=current.current;if(now?.id===snap.id&&now.revision===snap.revision&&!blocked.current)dispatch(legal(now,command)?command:choose(observation(now)));};const think=setTimeout(()=>{try{worker=new Worker(new URL('./bot.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.requestId===requestId&&e.data.id===snap.id&&e.data.revision===snap.revision)done(e.data.command);};worker.onerror=()=>done(choose(observation(snap)));worker.postMessage({requestId,state:observation(snap)});timeout=setTimeout(()=>done(choose(observation(snap))),2000);}catch{done(choose(observation(snap)));}},s.phase==='card'?2200:850);return()=>{live=false;clearTimeout(think);if(timeout)clearTimeout(timeout);worker?.terminate();};},[s?.id,s?.revision,s?.phase,ready,intro,freeze,busy,dispatch]);
 useEffect(()=>{if(!s||busy||intro)return;if(s.phase==='buy')setSelected(s.players[s.active].position);},[s?.revision,busy,intro]);
 function begin(resume?:Match){const match=resume||createMatch(owner,party,'family',crypto.getRandomValues(new Uint32Array(1))[0]);setS(match);current.current=match;setPositions(match.players.map(p=>p.position));setQueue([]);setEventIndex(0);setSelected(null);setPaused(false);setModal(null);setResultSaved(false);setReady(false);setIntro(!resume&&!prefs.reduced&&!prefs.flat);setDraft({match:null,error:false});}
 function lobby(){setDraft(loadDraft(owner));setS(null);setSelected(null);setQueue([]);setIntro(false);setPaused(false);}
 const guide=<div className='town-guide'><p><b>1. Gieo, đi, mua hoặc trả thuê.</b> Mỗi người có 1.500 xu. Qua Bắt đầu nhận 200 xu. Tiệm chưa có chủ: mua hoặc bỏ qua. Tiệm của người khác: tự trả tiền thuê.</p><p><b>2. Mỗi lượt xây một lần.</b> Có đất là được mở rộng cấp đầu. Sở hữu cả ba công trình cùng nhóm màu để lên cấp cao nhất. Trước khi gieo, chạm công trình của mình để xây. Gieo thêm vẫn thuộc cùng lượt, không được xây lần nữa.</p><p><b>3. Số kép và nhà tù.</b> Hai viên giống nhau được gieo thêm. Ba lần số kép liên tiếp trong một lượt: vào tù. Ở lượt trong tù, chọn nộp 50 xu hoặc thử số kép. Sau ba lần thử không thành công, nộp 50 xu rồi đi theo xúc xắc.</p><p><b>4. Người cuối cùng thắng.</b> Không đủ tiền mặt trả nợ thì phá sản; tiền còn lại và công trình chuyển cho chủ nợ. Nợ ngân hàng thì trả tài sản về ngân hàng. Những người khác tiếp tục chơi.</p><p>Đây là bản rút gọn: hai mức xây dựng, không đấu giá, thế chấp hay trao đổi tự do. Hai góc Rương kỳ diệu và Hộp bất ngờ cùng các ô thư rút từ bộ 20 sự kiện tốt/xấu. Mọi thẻ lật công khai, xử lý ngay và trả về bộ bài.</p><button className='town-primary' onClick={()=>setModal(null)}>Đã hiểu <Check size={18}/></button></div>;
 const exitCategory=()=>{const match=current.current;if(match&&!saveDraft(match)){setSaveError(true);return;}if(match?.phase==='over'&&!complete(owner,match).ok){setResultSaved(false);return;}onExit();};
 if(!s)return <main className='town town-lobby'><div className='town-cover' style={{backgroundImage:`url(${cover})`}}/><div className='town-lobby-shade'/><div className='town-category-back'><BoardGamesBack onBack={exitCategory}/></div><section className='town-title'><span className='town-eyebrow'>MỘT KHU PHỐ · NGÀN CÂU CHUYỆN</span><h1>Phố Nhỏ<br/><em>Tỉ Phú</em><i>✦</i></h1><p>Mở cửa tiệm mơ ước.<br/>Xây nên khu phố của chúng mình.</p><div className='town-tags'><span>2–4 người</span><span>Chung màn hình</span><span>Có máy chơi cùng</span></div></section><section className='town-setup'><span className='town-eyebrow'>CHUYẾN DẠO PHỐ MỚI</span><h2>Rủ cả nhà cùng chơi</h2><p className='town-setup-rule'>Mua đất → Mở rộng → Đủ màu để lên cao nhất</p><div className='town-party'>{party.map((p,i)=><div className='town-seat' key={i}><span className='town-face' style={{background:COLORS[i]}}>{faces[i]}</span><div><input aria-label={`Tên người chơi ${i+1}`} maxLength={24} value={p.name} onChange={e=>setParty(a=>a.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/><small>{ANIMALS[i]} · {i===0?'Chủ bàn':p.kind==='bot'?'Bạn máy':'Người chơi'}</small></div>{i>0&&<select aria-label={`Loại người chơi ${i+1}`} value={p.kind} onChange={e=>setParty(a=>a.map((x,j)=>i===j?{...x,kind:e.target.value as Player['kind'],name:e.target.value==='bot'?`Máy ${ANIMALS[i]}`:`Bạn ${i+1}`}:x))}><option value='human'>Bạn</option><option value='bot'>Máy</option></select>}{p.kind==='bot'&&<select aria-label={`Độ khó máy ${i+1}`} value={p.skill} onChange={e=>setParty(a=>a.map((x,j)=>i===j?{...x,skill:e.target.value as Player['skill']}:x))}><option value='easy'>Dễ</option><option value='medium'>Vừa</option><option value='hard'>Khó</option></select>}{i>=2&&<button aria-label={`Bỏ ghế ${i+1}`} onClick={()=>setParty(a=>a.filter((_,j)=>i!==j))}><X size={16}/></button>}</div>)}</div>{party.length<4&&<button className='town-add' onClick={()=>setParty(a=>[...a,player(`Bạn ${a.length+1}`,'human')])}>+ Thêm người chơi</button>}<button className='town-primary town-start' disabled={!partyValid(party)} onClick={()=>begin()}>Mở cửa khu phố <ArrowUpRight size={22}/></button>{draft.match&&<button className='town-resume' onClick={()=>begin(draft.match!)}><Play size={16}/> Tiếp tục ván đã lưu · lượt {draft.match.turn+1}</button>}{draft.error&&<p role='status'>Bản lưu cũ không đọc được. Có thể bắt đầu ván mới.</p>}<button className='town-link' onClick={()=>setModal('rules')}><HelpCircle size={16}/> Chơi thế nào?</button><small className='town-lobby-note'>Mỗi người 1.500 xu · Tự lưu sau mỗi quyết định</small></section>{modal==='rules'&&<Dialog title='Một vòng quanh khu phố' onClose={()=>setModal(null)}>{guide}</Dialog>}</main>;
 const active=actor(s),p=s.players[active],human=p.kind==='human',enabled=!blocked.current&&human,t=selected!==null?BOARD[selected]:null,prop=selected!==null?s.properties[selected]:null;
 const doButton=(label:string,command:Command,primary=true)=><button className={primary?'town-primary':'town-secondary'} disabled={!enabled||!legal(s,command)} onClick={()=>dispatch(command)}>{label}</button>;
 const propertyInfo=t&&prop?<><span className='town-eyebrow'>{GROUPS[t.group]?.name||'ĐỊA ĐIỂM'} · Ô {t.id+1}</span><h2><span>{t.icon}</span> {t.name}</h2>{t.price?<div className='town-property-values'><span>Giá mua <b>{t.price} xu</b></span><span>Tiền thuê <b>{prop.owner===null?(GROUPS[t.group]?.rents[0]||(t.kind==='station'?100:80)):rent(s,t.id)} xu</b></span><span>Chủ tiệm <b>{prop.owner===null?'Đang chờ bạn':s.players[prop.owner].name}</b></span></div>:<p>{t.kind==='start'?'Qua đây nhận 200 xu.':t.kind==='repair'?'Rút một thẻ Cơ hội ngẫu nhiên. Có thể được gieo thêm hoặc phải vào tù.':t.kind==='festival'?'Mở rương và rút một thẻ Chuyện khu phố: có quà và cả thử thách.':t.kind==='rest'?'Chỉ ghé thăm: không bị giam và không mất lượt.':t.kind==='fee'?`Đóng góp ${t.fee} xu cho khu phố.`:'Rút một câu chuyện khi ghé ô này.'}</p>}</>:null;
 const action=!intro&&!busy&&s.phase!=='over'?<div className={'town-action '+(s.phase==='card'?'town-card '+cardMood(s.card!):'')} key={`${s.revision}:${selected}`}>
 {s.phase==='card'?<><span className='town-eyebrow'>{s.card!.startsWith('community')?'CHUYỆN KHU PHỐ':'MỘT CƠ HỘI MỚI'}</span><span className='town-card-category'>{cardMood(s.card!)==='gift'?'✦ MÓN QUÀ':cardMood(s.card!)==='challenge'?'✦ THỬ THÁCH':'✦ BẤT NGỜ'}</span><div className='town-card-art'><img src={`${import.meta.env.BASE_URL}co-ti-phu/art/events/${cardKey(s.card!)}.webp`} alt=''/></div><h2>{CARD_TEXT[cardKey(s.card!)][0]}</h2><p>{CARD_TEXT[cardKey(s.card!)][1]}</p>{doButton('Nhận sự kiện', {type:'card'})}<small className='town-card-public'>Thẻ công khai · Xử lý ngay cho lượt này</small></>:
 s.phase==='jail'?<><span className='town-eyebrow'>NHÀ TÙ · LƯỢT THỬ {(p.jailAttempts||0)+1}/3</span><h2>Chọn cách ra tù</h2><p>Nộp 50 xu để gieo bình thường, hoặc thử hai viên giống nhau. Lần thử thứ ba không thành công sẽ tự nộp 50 xu.</p><div className='town-buttons'>{doButton('Nộp 50 xu',{type:'bail'})}{doButton('Thử số kép',{type:'jail-roll'},false)}</div></>:
 <>{propertyInfo}{t&&t.group>=0&&<details className='town-group-progress'><summary><b><i style={{background:GROUPS[t.group].color}}/>Nhóm {GROUPS[t.group].name} · {BOARD.filter(b=>b.group===t.group&&s.properties[b.id].owner===s.active).length}/3 của mình</b><span>Xem 3 công trình cùng màu ▾</span></summary><div>{BOARD.filter(b=>b.group===t.group).map(b=><button key={b.id} className={s.properties[b.id].owner===s.active?'owned':''} onClick={()=>setSelected(b.id)}><span>{b.icon} {s.properties[b.id].owner===s.active?'✓':''}</span>{b.name}</button>)}</div><small>Dải màu = nhóm công trình · Nền đất = người sở hữu</small></details>}
 {s.phase==='buy'&&(selected===s.players[s.active].position?<>
 <p>{s.players[s.active].cash>=BOARD[s.players[s.active].position].price?<>Còn <b>{s.players[s.active].cash-BOARD[s.players[s.active].position].price} xu</b> sau khi mua.</>:<>Cần thêm {BOARD[s.players[s.active].position].price-s.players[s.active].cash} xu để mua tiệm.</>}</p>
 <div className='town-buttons'>{doButton(`Mua · ${BOARD[s.players[s.active].position].price} xu`,{type:'buy'})}{doButton('Không mua',{type:'decline'},false)}</div>
 </>:<button className='town-primary' onClick={()=>setSelected(s.players[s.active].position)}>Về {BOARD[s.players[s.active].position].name} để quyết định</button>)}
 {s.phase==='roll'&&t&&prop?.owner===s.active&&t.kind==='shop'&&<><div className='town-building-steps'>{['Ban đầu','Mở rộng','Nổi bật'].map((label,i)=><span key={label} className={prop.level>=i?'done':''}>{prop.level>i?'✓':i+1} {label}</span>)}</div>{!s.builtThisTurn&&canUpgrade(s,t.id,s.active)?<><p>{DEVELOPMENTS[t.id]?.[prop.level+1]}</p>{doButton(`${prop.level===0?'Mở rộng':'Xây công trình nổi bật'} · ${upgradeCost(s,t.id,s.active)} xu`,{type:'upgrade',tile:t.id})}<small>Tiền thuê: {rent(s,t.id)} → {GROUPS[t.group].rents[prop.level+1]} xu · Còn {p.cash-upgradeCost(s,t.id,s.active)} xu</small></>:<p>{prop.level===2?'Đã hoàn thành công trình nổi bật!':s.builtThisTurn?'Đã nâng cấp trong lượt này. Gieo xúc xắc để tiếp tục.':!fullGroup(s,t.id,s.active)?`Cấp cao nhất cần đủ 3 công trình nhóm ${GROUPS[t.group].name} để xây. Đã có ${BOARD.filter(b=>b.group===t.group&&s.properties[b.id].owner===s.active).length}/3.`:'Chưa đủ tiền mặt để xây.'}</p>}</>}
 {t&&s.phase==='roll'&&<div className='town-buttons'>{doButton('Gieo xúc xắc',{type:'roll'})}<button className='town-secondary' onClick={()=>setSelected(null)}>Toàn cảnh</button></div>}</>}
 {!human&&<small className='town-thinking'><Bot size={14}/> {p.name} đang suy nghĩ…</small>}
 </div>:null;
 const showAction=s.phase==='roll'&&selected===null?null:action;
 const boardProps={s,positions,selected,onPick:(id:number)=>{if(!intro&&!busy){setSelected(id);}},intro,onIntroEnd,paused:freeze,reduced:prefs.reduced,light:prefs.light,onReady,onFailure,motion:event,eventId:`${s.id}:${s.revision}:${eventIndex}`,duration:event?eventDuration(event,prefs.reduced):0,canRoll:enabled&&s.phase==='roll'&&selected===null,onRoll:()=>dispatch({type:'roll'}),action:showAction,view};
 return <main className={'town town-game'+(prefs.reduced?' reduced':'')} data-phase={s.phase} data-revision={s.revision} data-active={active} data-ready={ready} data-busy={busy}>
 <div className='town-stage'>{prefs.flat?<Board2D {...boardProps}/>:<Boundary onFail={onFailure} fallback={<Board2D {...boardProps}/>}><Suspense fallback={<div className='town-loading'>Đang mở từng cửa tiệm…</div>}><Board3D {...boardProps}/></Suspense></Boundary>}</div>
 <header className='town-hud'><BoardGamesBack onBack={exitCategory}/><button aria-label='Tạm dừng' onClick={()=>setPaused(true)}><Pause size={19}/></button><div><span className='town-eyebrow'>PHỐ NHỎ TỈ PHÚ · LƯỢT {s.turn+1}</span><h1>{intro?'Chào mừng đến khu phố':busy?event!.text:s.phase==='over'?'Một khu phố, nhiều niềm vui':`${p.name}${human?' đến lượt!':' đang tính nước đi…'}`}</h1></div><button title='Về toàn cảnh' aria-label='Về toàn cảnh' onClick={()=>{setSelected(null);setView(v=>v+1);}}><Home size={19}/></button><button aria-label='Cài đặt' onClick={()=>setModal('settings')}><Settings2 size={19}/></button></header>
 <nav className='town-players' aria-label='Tài sản người chơi'>{s.players.map((x,i)=><button key={i} className={(active===i?'active':'')+(x.bankrupt?' bankrupt':'')} style={{'--seat':COLORS[i]} as React.CSSProperties} onClick={()=>setModal(i)}><span className='town-face'>{faces[i]}</span><span><b>{x.name}{x.kind==='bot'?' · Máy':''}</b><strong>{x.cash.toLocaleString('vi-VN')} <small>xu</small></strong><small>Tổng {assets(s,i).toLocaleString('vi-VN')}{x.bankrupt?' · Phá sản':x.jailed?' · Trong tù':''}</small></span></button>)}</nav>
 <footer className='town-footer'><button onClick={()=>setModal('log')}>Nhật ký khu phố</button><span role='status'>{saveError?'Chưa lưu được · hãy giữ ván mở':'✓ Ván chơi đã lưu'}</span><button aria-label={prefs.sound?'Tắt âm thanh':'Bật âm thanh'} onClick={()=>setPrefs(p=>({...p,sound:!p.sound}))}>{prefs.sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></footer>
 {intro&&<div className='town-intro'><span>CHÀO MỪNG ĐẾN PHỐ NHỎ</span><button onClick={onIntroEnd}>Vào chơi <ChevronRight size={18}/></button></div>}
 {busy&&!intro&&<div className='town-event' aria-live='polite'><span>{event!.kind==='move'?`⚄ ${s.dice[0]} + ${s.dice[1]}`:event!.kind==='money'?'✦':'🏡'}</span><p>{event!.text}</p><button onClick={()=>{setPositions(s.players.map(p=>p.position));setEventIndex(queue.length);}}>Xem nhanh</button></div>}
 {paused&&<Dialog title='Nghỉ chân một chút' onClose={()=>setPaused(false)}><p>Ván được giữ nguyên. Camera và máy cùng tạm dừng.</p><button className='town-primary' onClick={()=>setPaused(false)}><Play size={18}/> Chơi tiếp</button><button className='town-secondary' onClick={lobby}>Về sảnh · giữ bản lưu</button><button className='town-link' onClick={exitCategory}>Về Board games</button></Dialog>}
 {modal!==null&&<Dialog title={modal==='rules'?'Một vòng quanh khu phố':modal==='settings'?'Góc chơi của mình':modal==='log'?'Nhật ký khu phố':`Tài sản của ${s.players[modal].name}`} onClose={()=>setModal(null)}>{modal==='rules'?guide:modal==='settings'?<><p>Tùy chỉnh được lưu cho những ván sau.</p>{([['sound','Âm thanh'],['reduced','Giảm chuyển động'],['light','Đồ họa nhẹ'],['flat','Bàn phẳng 2D']] as const).map(([k,label])=><label className='town-setting' key={k}><span>{label}</span><input type='checkbox' checked={prefs[k]} onChange={e=>setPrefs(p=>({...p,[k]:e.target.checked}))}/></label>)}<button className='town-secondary' onClick={()=>setModal('rules')}>Xem luật chơi</button></>:modal==='log'?<ol className='town-log'>{s.log.slice().reverse().map((line,i)=><li key={i}>{line}</li>)}</ol>:<><div className='town-total'><span>Tiền mặt <b>{s.players[modal].cash} xu</b></span><span>Tổng tài sản <b>{assets(s,modal)} xu</b></span></div><div className='town-owned'>{BOARD.filter(b=>s.properties[b.id].owner===modal).map(b=><button key={b.id} onClick={()=>{setModal(null);setSelected(b.id);}}>{b.icon} {b.name}<small>Cấp {s.properties[b.id].level} · Thuê {rent(s,b.id)} xu</small></button>)}</div>{!s.properties.some(p=>p.owner===modal)&&<p>Chưa có cửa tiệm. Cả khu phố đang chờ khám phá!</p>}</>}</Dialog>}
 {s.phase==='over'&&!busy&&<Dialog title='Khu phố đã lớn lên cùng cả nhà!' onClose={lobby}><div className='town-winner'>🏆<h2>{winners(s).map(i=>s.players[i].name).join(' & ')}</h2><p>{'Người cuối cùng còn lại trong ván'}</p></div><div className='town-results'>{s.players.map((x,i)=><div key={i}><span>{faces[i]} {x.name}</span><b>{assets(s,i)} xu</b><small>{x.cash} tiền mặt + {assets(s,i)-x.cash} công trình</small></div>)}</div><p>{s.endReason}</p>{!resultSaved&&<button onClick={()=>setResultSaved(complete(owner,s).ok)}>Thử lưu kết quả lại</button>}<button className='town-primary' onClick={()=>{setParty(s.players);begin(createMatch(owner,s.players,s.mode,crypto.getRandomValues(new Uint32Array(1))[0]));setIntro(!prefs.reduced&&!prefs.flat);}}><RotateCcw size={18}/> Chơi lại cùng nhóm</button><button className='town-secondary' onClick={lobby}>Về sảnh</button></Dialog>}
 </main>;
}
export default function Entry({onExit}:{onExit:()=>void}){const {currentStudent}=useStudent(),{completePropertyTown}=useStudentActions();if(!currentStudent)return null;return <PropertyTown key={currentStudent.id} owner={currentStudent.id} name={currentStudent.name} onExit={onExit} complete={completePropertyTown}/>;}
