import { lesson, know, rule, text, pic, widget, mistake, vis } from '../../build';
import { example as ex, step as s } from '../authored';
import type { LessonBook } from '../../types';
export default {
 'g1.add10': lesson('g1.add10',{v:1,autoRead:true,goal:'cộng các số trong phạm vi 10.',
  know:[know('Cộng là thêm hoặc gộp',rule('Gộp hai nhóm, đếm tất cả để tìm tổng.'),pic('groupsSVG',[{emoji:'🍎',n:3},{emoji:'🍎',n:2}]),text('3 + 2 = 5. Đọc: ba cộng hai bằng năm.'))],
  forms:[ex('tinh','Dạng 1: Tính tổng',1,'Đề có dấu cộng.',['Bắt đầu từ số đầu.','Đếm thêm số còn lại.'],'Tính 4 + 3.',[s('Từ 4, đếm thêm: năm, sáu, bảy.')],'4 + 3 = 7.'),ex('them','Dạng 2: Thêm đồ vật',2,'Có thêm đồ vật vào nhóm.',['Đếm nhóm ban đầu.','Cộng số được thêm.'],'Có 5 quả táo. Thêm 2 quả. Có tất cả mấy quả?',[s('Phép tính:', '5 + 2 = 7')],'Trả lời: 7 quả táo.')],
  remember:['Thêm, gộp: dùng phép cộng.','Cộng với 0 giữ nguyên số đó.']}),
 'g1.add10_missing': lesson('g1.add10_missing',{v:1,autoRead:true,goal:'tìm số còn thiếu trong phép cộng.',
  know:[know('Đếm thêm đến tổng',rule('Đếm từ số đã biết đến tổng. Đếm số bước thêm.'),pic('numberLineSVG',0,10,1,[4,7]),text('4 + □ = 7. Đếm thêm 3, điền 3.'))],
  forms:[ex('sau','Dạng 1: Ô trống phía sau',2,'Số còn thiếu đứng sau dấu cộng.',['Đếm thêm đến kết quả.','Thử số vừa tìm.'],'Điền số: 6 + □ = 9.',[s('Từ 6 đến 9 thêm 3.'),s('Thử lại: 6 + 3 = 9.')],'3.'),ex('truoc','Dạng 2: Ô trống phía trước',2,'Số đầu phép cộng còn thiếu.',['Tìm phần còn thiếu của tổng.','Thay vào để thử lại.'],'Điền số: □ + 2 = 8.',[s('8 gồm 6 và 2.'),s('Thử lại: 6 + 2 = 8.')],'6.')],
  remember:['Tìm phần còn thiếu.','Thay số vào để kiểm tra.']}),
 'g1.add10_compare': lesson('g1.add10_compare',{v:1,autoRead:true,goal:'so sánh tổng với số hoặc tổng khác.',
  know:[know('Tính trước, so sánh sau',rule('Tính từng bên. So sánh các kết quả.'),pic('groupsSVG',[{emoji:'🌼',n:2},{emoji:'🌼',n:3}]),text('2 + 3 = 5. Vì 5 < 6 nên 2 + 3 < 6.'))],
  forms:[ex('so','Dạng 1: Tổng và một số',2,'Một bên là phép cộng.',['Tính tổng.','So sánh với số bên kia.'],'Điền dấu: 3 + 4 □ 8.',[s('3 + 4 = 7.'),s('7 < 8.')],'3 + 4 < 8.'),ex('tong','Dạng 2: Hai tổng',3,'Hai bên đều là phép cộng.',['Tính cả hai tổng.','So sánh hai kết quả.'],'Điền dấu: 2 + 6 □ 5 + 3.',[s('2 + 6 = 8.'),s('5 + 3 = 8.')],'2 + 6 = 5 + 3.')],
  mistakes:[mistake('Bạn Bi chỉ so 2 với 5.','Phải so kết quả cả hai tổng.','Mỗi bên còn có số được cộng thêm.')],remember:['Tính đủ mỗi bên.','Kết quả bằng nhau dùng dấu =.']}),
 'g1.sub10': lesson('g1.sub10',{v:1,autoRead:true,goal:'trừ các số trong phạm vi 10.',
  know:[know('Trừ là bớt đi',rule('Bớt một số vật. Đếm những vật còn lại.'),pic('crossedSVG','🍎',7,2),text('7 − 2 = 5. Đọc: bảy trừ hai bằng năm.'))],
  forms:[ex('tinh','Dạng 1: Tính hiệu',1,'Đề có dấu trừ.',['Bắt đầu từ số đầu.','Đếm lùi đúng số bước.'],'Tính 8 − 3.',[s('Từ 8 đếm lùi: bảy, sáu, năm.')],'8 − 3 = 5.'),ex('bot','Dạng 2: Bớt đồ vật',2,'Một số đồ vật bị lấy đi.',['Đọc số ban đầu.','Trừ số lấy đi.'],'Có 6 quả táo, ăn 2 quả. Còn mấy quả?',[s('Phép tính:', '6 − 2 = 4')],'Trả lời: 4 quả táo.')],
  remember:['Bớt đi dùng phép trừ.','Một số trừ chính nó bằng 0.']}),
 'g1.sub10_missing': lesson('g1.sub10_missing',{v:1,autoRead:true,goal:'tìm số còn thiếu trong phép trừ.',
  know:[know('Số đầu, số bớt, số còn',rule('Số ban đầu gồm số bớt và số còn lại.'),pic('crossedSVG','⭐',8,3),text('8 − 3 = 5. Gộp 5 và 3 được 8.'))],
  forms:[ex('bot','Dạng 1: Tìm số bớt',2,'Ô trống đứng sau dấu trừ.',['Xem số đầu và số còn.','Tìm số đã bớt.'],'Điền số: 9 − □ = 5.',[s('Từ 9 bớt 4 còn 5.'),s('Thử: 9 − 4 = 5.')],'4.'),ex('dau','Dạng 2: Tìm số ban đầu',2,'Ô trống đứng trước dấu trừ.',['Gộp số còn với số bớt.','Thử lại phép trừ.'],'Điền số: □ − 2 = 6.',[s('6 + 2 = 8.'),s('Thử: 8 − 2 = 6.')],'8.')],
  remember:['Tìm số đầu: gộp hai phần.','Tìm số bớt: xem đã mất bao nhiêu.']}),
 'g1.chain10': lesson('g1.chain10',{v:1,autoRead:true,goal:'tính phép tính có hai dấu trong phạm vi 10.',
  know:[know('Tính từ trái sang phải',rule('Làm phép tính đầu. Dùng kết quả tính tiếp.'),pic('numberLineSVG',0,10,1,[3,5,9]),text('3 + 6 − 4 = 9 − 4 = 5.'))],
  forms:[ex('congtru','Dạng 1: Cộng rồi trừ',2,'Có dấu cộng và dấu trừ.',['Tính từ bên trái.','Dùng kết quả làm phép tính sau.'],'Tính 4 + 5 − 2.',[s('4 + 5 = 9.'),s('9 − 2 = 7.')],'7.'),ex('tru','Dạng 2: Hai phép trừ',3,'Có hai dấu trừ.',['Trừ lần đầu.','Lấy kết quả trừ tiếp.'],'Tính 9 − 3 − 2.',[s('9 − 3 = 6.'),s('6 − 2 = 4.')],'4.')],
  mistakes:[mistake('Bạn Bi tính 3 − 2 trước trong 9 − 3 − 2.','Tính 9 − 3 trước.','Phải tính theo thứ tự từ trái sang phải.')],remember:['Bắt đầu từ bên trái.','Giữ dấu phép tính còn lại.']}),
 'g1.write_eq': lesson('g1.write_eq',{v:1,autoRead:true,goal:'viết phép tính phù hợp với tranh.',
  know:[know('Tranh kể chuyện thêm, bớt',rule('Gộp hoặc thêm: cộng. Bớt hoặc đi khỏi: trừ.'),pic('crossedSVG','🍎',6,2),text('Có 6 quả, bớt 2 quả. Viết 6 − 2 = 4.'))],
  forms:[ex('gop','Dạng 1: Tranh gộp nhóm',2,'Có hai nhóm được gộp lại.',['Đếm từng nhóm.','Viết phép cộng.'],'Viết phép tính theo tranh.',[s('Nhóm đầu có 3. Nhóm sau có 4.')],'3 + 4 = 7.',{visual:vis('groupsSVG',[{emoji:'🌼',n:3},{emoji:'🌼',n:4}])}),ex('bot','Dạng 2: Tranh bớt đi',3,'Một số vật bị gạch đi.',['Đếm cả nhóm ban đầu.','Trừ số bị gạch.'],'Viết phép tính theo tranh.',[s('Có 8 sao, gạch đi 3 sao.')],'8 − 3 = 5.',{visual:vis('crossedSVG','⭐',8,3)})],
  remember:['Quan sát điều đang xảy ra.','Phép tính phải đúng với câu chuyện.']}),
 'g1.addsub100': lesson('g1.addsub100',{v:1,autoRead:true,goal:'cộng, trừ không nhớ trong phạm vi 100.',
  know:[know('Thẳng chục, thẳng đơn vị',rule('Viết thẳng hàng. Tính đơn vị trước, chục sau.'),widget({w:'column',op:'+',a:23,b:14}),text('23 + 14 = 37.'))],
  forms:[ex('cong','Dạng 1: Cộng không nhớ',1,'Cộng hai số, không cần nhớ.',['Cộng hàng đơn vị.','Cộng hàng chục.'],'Tính 42 + 35.',[s('2 cộng 5 bằng 7.'),s('4 cộng 3 bằng 7.')],'77.'),ex('tru','Dạng 2: Trừ không nhớ',2,'Trừ hai số, không cần nhớ.',['Trừ hàng đơn vị.','Trừ hàng chục.'],'Tính 68 − 24.',[s('8 trừ 4 bằng 4.'),s('6 trừ 2 bằng 4.')],'44.'),ex('tron','Dạng 3: Cộng, trừ số tròn chục',3,'Hai số có đơn vị bằng 0.',['Tính số chục.','Viết thêm 0 ở hàng đơn vị.'],'Tính 70 − 30.',[s('7 chục trừ 3 chục còn 4 chục.')],'40.')],
  mistakes:[mistake('Bạn Bi viết 5 dưới hàng chục khi cộng 42 + 5.','Viết 5 dưới chữ số 2.','Đơn vị phải thẳng đơn vị.')],remember:['Đơn vị trước, chục sau.','Viết thẳng hàng.']}),
 'g1.addsub20': lesson('g1.addsub20',{v:1,autoRead:true,goal:'cộng, trừ không qua 10 trong phạm vi 20.',
  know:[know('Giữ nguyên một chục',rule('Cộng, trừ các đơn vị. Giữ nguyên một chục.'),pic('tensOnesSVG',1,3),text('13 + 4 = 17. 17 − 4 = 13.'))],
  forms:[ex('cong','Dạng 1: Cộng',1,'Cộng thêm đơn vị, chưa đủ chục mới.',['Cộng phần đơn vị.','Ghép lại với một chục.'],'Tính 12 + 5.',[s('2 + 5 = 7.'),s('1 chục và 7 đơn vị là 17.')],'17.'),ex('tru','Dạng 2: Trừ',2,'Bớt đơn vị, còn ít nhất một chục.',['Trừ phần đơn vị.','Giữ nguyên một chục.'],'Tính 18 − 6.',[s('8 − 6 = 2.'),s('1 chục và 2 đơn vị là 12.')],'12.')],
  remember:['Tính phần đơn vị.','Nhớ giữ một chục.']}),
 'g1.carry20': lesson('g1.carry20',{v:1,autoRead:true,goal:'cộng, trừ qua 10 bằng cách tách số.',
  know:[know('Làm đủ 10 trước',rule('Tách số để tạo 10. Tính tiếp phần còn lại.'),pic('groupsSVG',[{emoji:'⭐',n:8},{emoji:'⭐',n:5}]),text('8 + 5 = 8 + 2 + 3 = 13.'))],
  forms:[ex('cong','Dạng 1: Cộng qua 10',2,'Phần đơn vị cộng lại vượt 10.',['Tách số sau để đủ 10.','Cộng phần còn lại.'],'Tính 9 + 4.',[s('Tách 4 thành 1 và 3.'),s('9 + 1 = 10.'),s('10 + 3 = 13.')],'13.'),ex('tru','Dạng 2: Trừ qua 10',2,'Cần bớt qua mốc 10.',['Bớt về 10.','Bớt tiếp phần còn lại.'],'Tính 13 − 5.',[s('Tách 5 thành 3 và 2.'),s('13 − 3 = 10.'),s('10 − 2 = 8.')],'8.')],
  mistakes:[mistake('Bạn Bi tính 9 + 4 = 10.','Còn phải cộng thêm 3, được 13.','Tách số nhưng phải dùng đủ cả hai phần.')],remember:['Mốc 10 giúp tính nhanh.','Dùng đủ các phần đã tách.']}),
} satisfies LessonBook;
