import { lesson, know, rule, text, pic, widget, explore, vis, mistake } from '../../build';
import { example as ex, step as s } from '../authored';
import type { LessonBook } from '../../types';
export default {
 'g1.count5': lesson('g1.count5',{v:1,autoRead:true,goal:'đếm, đọc và viết số từ 0 đến 5.',
  hook:{md:'Có mấy quả táo?',visual:vis('countingSVG','🍎',4),answer:'Có 4 quả táo.'},
  know:[know('Mỗi vật đếm một lần',rule('Chạm từng vật và đếm. Số cuối cho biết tất cả.'),pic('countingSVG','🍎',4),text('Đếm: một, hai, ba, bốn. Có 4 quả táo.')),know('Số 0',rule('Không có vật nào thì dùng số 0.'),pic('countingSVG','🍎',0),text('Rổ không có táo: 0 quả.'))],
  forms:[ex('dem','Dạng 1: Đếm đồ vật',1,'Đề hỏi có bao nhiêu vật.',['Chạm mỗi vật một lần.','Nói số cuối và viết số.'],'Đếm các bông hoa.',[s('Một, hai, ba.'),s('Viết số 3.')],'Trả lời: 3 bông hoa.',{visual:vis('countingSVG','🌼',3)})],
  mistakes:[mistake('Bạn Bi đếm một quả hai lần.','Mỗi quả chỉ đếm một lần.','Có thể chỉ tay để tránh đếm lặp.')],remember:['Mỗi vật đếm một lần.','Không có vật: số 0.']}),
 'g1.compare5': lesson('g1.compare5',{v:1,autoRead:true,goal:'so sánh các số trong phạm vi 5.',
  know:[know('Nhiều hơn, ít hơn',rule('Ghép mỗi vật nhóm này với một vật nhóm kia.'),pic('groupsSVG',[{emoji:'🍎',n:3,label:'3'},{emoji:'🍐',n:5,label:'5'}]),text('3 ít hơn 5. Viết 3 < 5.'))],
  forms:[ex('dau','Dạng 1: Điền dấu',1,'Điền dấu giữa hai số.',['So sánh hai số.','Chọn dấu <, > hoặc =.'],'Điền dấu: 4 □ 2.',[s('4 lớn hơn 2.'),s('Dấu mở rộng quay về số lớn.')],'4 > 2.'),ex('bang','Dạng 2: Hai nhóm bằng nhau',2,'Hai nhóm có cùng số vật.',['Đếm từng nhóm.','Cùng số lượng thì dùng dấu =.'],'Hai nhóm đều có 3 bông hoa.',[s('Hai nhóm cùng có 3 bông hoa.')],'3 = 3.')],
  mistakes:[mistake('Bạn Bi viết 2 > 5.','Viết đúng: 2 < 5.','Miệng rộng của dấu quay về số lớn.')],remember:['Đầu nhọn quay về số bé.','Bằng nhau dùng dấu =.']}),
 'g1.order5': lesson('g1.order5',{v:1,autoRead:true,goal:'sắp thứ tự các số từ 0 đến 5.',
  know:[know('Mỗi bước thêm một',rule('Đếm xuôi: mỗi số sau thêm 1.'),pic('numberLineSVG',0,5,1,[2,3]),text('0; 1; 2; 3; 4; 5. Đếm ngược thì bớt 1.'))],
  forms:[ex('day','Dạng 1: Điền số thiếu',1,'Dãy đếm còn thiếu một số.',['Đọc các số đã có.','Đếm tiếp theo đúng chiều.'],'Điền số: 1; 2; □; 4; 5.',[s('Sau 2 là 3.')],'3.'),ex('sap','Dạng 2: Xếp từ bé đến lớn',2,'Đề yêu cầu sắp xếp số.',['Chọn số bé nhất trước.','Xếp các số còn lại.'],'Xếp 4; 1; 3 từ bé đến lớn.',[s('1 bé nhất. 3 bé hơn 4.')],'1; 3; 4.')],
  remember:['Đếm xuôi thêm 1.','Đếm ngược bớt 1.']}),
 'g1.count10': lesson('g1.count10',{v:1,autoRead:true,goal:'đếm, đọc và viết số từ 0 đến 10.',needs:['g1.count5'],
  know:[know('Đếm đến mười',rule('Đếm tiếp sau 5: sáu, bảy, tám, chín, mười.'),pic('countingSVG','⭐',10,{perRow:5}),text('Mười viết là 10.'))],
  forms:[ex('dem','Dạng 1: Đếm và viết số',1,'Đề hỏi số lượng đồ vật.',['Đếm lần lượt, không bỏ sót.','Viết số vừa đếm.'],'Có bao nhiêu ngôi sao?',[s('Hàng trên có 5 sao.'),s('Đếm tiếp: sáu, bảy, tám.')],'Trả lời: 8 ngôi sao.',{visual:vis('countingSVG','⭐',8,{perRow:5})})],
  mistakes:[mistake('Bạn Bi đếm đến chín rồi viết 10.','Chín viết là 9.','Số viết phải khớp số vừa đọc.')],remember:['Đếm cả hai hàng.','Mười viết là 10.']}),
 'g1.compare10': lesson('g1.compare10',{v:1,autoRead:true,goal:'so sánh, tìm số lớn nhất và bé nhất đến 10.',
  know:[know('Nhìn dãy số',rule('Trong dãy đếm xuôi, số đứng sau lớn hơn.'),pic('numberLineSVG',0,10,1,[6,9]),text('9 đứng sau 6. Vậy 9 > 6.'))],
  forms:[ex('ss','Dạng 1: So sánh',1,'Điền dấu giữa hai số.',['Đọc hai số.','So theo dãy đếm.'],'Điền dấu: 7 □ 10.',[s('7 đứng trước 10.')],'7 < 10.'),ex('nhat','Dạng 2: Tìm số lớn nhất, bé nhất',2,'Có một nhóm số.',['So sánh từng số.','Chọn số theo yêu cầu.'],'Trong 6; 9; 4, số nào lớn nhất, bé nhất?',[s('4 < 6 < 9.')],'Lớn nhất: 9. Bé nhất: 4.')],
  remember:['Đọc đúng yêu cầu lớn nhất hay bé nhất.','Số 10 lớn hơn các số từ 0 đến 9.']}),
 'g1.split10': lesson('g1.split10',{v:1,autoRead:true,goal:'tách và gộp các số trong phạm vi 10.',
  know:[know('Một nhóm thành hai nhóm',rule('Tách nhóm thành hai phần. Gộp hai phần được cả nhóm.'),pic('groupsSVG',[{emoji:'🍎',n:4,label:'4'},{emoji:'🍎',n:3,label:'3'}]),text('7 gồm 4 và 3. 4 + 3 = 7.'))],
  forms:[ex('tach','Dạng 1: Tìm phần còn thiếu',1,'Biết cả nhóm và một phần.',['Đếm số đã tách.','Đếm phần còn lại.'],'8 gồm 5 và mấy?',[s('Từ 5 đếm thêm 3 thì được 8.')],'8 gồm 5 và 3.'),ex('gop','Dạng 2: Gộp hai phần',2,'Biết hai nhóm nhỏ.',['Đếm nhóm đầu.','Đếm tiếp nhóm sau.'],'Gộp 6 que với 4 que.',[s('6 + 4 = 10.')],'Trả lời: 10 que.')],
  remember:['Tách không làm mất vật nào.','Gộp là lấy tất cả hai nhóm.']}),
 'g1.numbers20': lesson('g1.numbers20',{v:1,autoRead:true,goal:'đọc số đến 20 bằng chục và đơn vị.',
  know:[know('Một chục và các đơn vị',rule('10 đơn vị là 1 chục.'),pic('tensOnesSVG',1,4),text('14 gồm 1 chục và 4 đơn vị. Đọc: mười bốn.')),know('Số 20',pic('tensOnesSVG',2,0),text('20 gồm 2 chục. Đọc: hai mươi.'))],
  forms:[ex('doc','Dạng 1: Đọc, viết số',1,'Đề cho số chục và đơn vị.',['Viết số chục trước.','Viết số đơn vị sau.'],'1 chục và 7 đơn vị là số nào?',[s('Viết 1 rồi viết 7.')],'17: mười bảy.'),ex('ss','Dạng 2: So sánh',2,'Hai số đều có một chục.',['So số chục.','Cùng chục thì so đơn vị.'],'So sánh 13 và 18.',[s('Cùng 1 chục. 3 đơn vị ít hơn 8 đơn vị.')],'13 < 18.')],
  mistakes:[mistake('Bạn Bi viết 1 chục 7 đơn vị thành 71.','Số đúng là 17.','Chữ số chục đứng trước chữ số đơn vị.')],remember:['Chục đứng trước, đơn vị đứng sau.','20 có 2 chục và 0 đơn vị.']}),
 'g1.numbers100': lesson('g1.numbers100',{v:1,autoRead:true,goal:'đọc, viết các số đến 100.',
  know:[know('Đọc chục rồi đơn vị',rule('Đọc số chục trước, số đơn vị sau.'),pic('tensOnesSVG',3,5),text('35 gồm 3 chục và 5 đơn vị. Đọc: ba mươi lăm.')),know('Các số tròn chục',pic('tensOnesSVG',4,0),text('40 đọc là bốn mươi. 100 đọc là một trăm.'))],
  forms:[ex('viet','Dạng 1: Viết số',1,'Đề cho số chục và đơn vị.',['Xác định chục.','Xác định đơn vị rồi viết số.'],'6 chục và 2 đơn vị là số nào?',[s('Chục là 6, đơn vị là 2.')],'62.'),ex('doc','Dạng 2: Đọc số',2,'Đề cho số cần đọc.',['Đọc hàng chục.','Đọc hàng đơn vị.'],'Đọc số 51.',[s('5 chục đọc là năm mươi.'),s('Chữ số 1 ở đây đọc là mốt.')],'Năm mươi mốt.')],
  remember:['Số tròn chục tận cùng bằng 0.','100 là một trăm.']}),
 'g1.compare100': lesson('g1.compare100',{v:1,autoRead:true,goal:'so sánh, sắp xếp các số đến 100.',
  know:[know('So chục trước',rule('So chục trước. Cùng chục thì so đơn vị.'),pic('tensOnesSVG',4,2),text('42 > 39 vì 4 chục nhiều hơn 3 chục.'))],
  forms:[ex('ss','Dạng 1: Điền dấu',1,'Đề cho hai số.',['So hàng chục.','Nếu bằng nhau, so hàng đơn vị.'],'So sánh 56 và 59.',[s('Cùng 5 chục. 6 < 9.')],'56 < 59.'),ex('sap','Dạng 2: Sắp xếp',2,'Đề cho ba số cần xếp.',['Tìm số bé nhất.','Xếp tiếp các số còn lại.'],'Xếp tăng dần: 72; 27; 70.',[s('27 bé nhất. 70 < 72.')],'27; 70; 72.')],
  mistakes:[mistake('Bạn Bi nói 39 > 42 vì 9 > 2.','39 < 42.','Phải so hàng chục trước.')],remember:['Chục trước, đơn vị sau.','100 lớn hơn mọi số có hai chữ số.']}),
 'g1.neighbors100': lesson('g1.neighbors100',{v:1,autoRead:true,goal:'tìm số liền trước và liền sau.',
  know:[know('Hai người hàng xóm',rule('Liền trước bớt 1. Liền sau thêm 1.'),pic('numberLineSVG',27,32,1,[29,30,31]),text('Trước 30 là 29. Sau 30 là 31.'))],
  forms:[ex('truoc','Dạng 1: Số liền trước',1,'Đề hỏi số đứng ngay trước.',['Đọc số đã cho.','Bớt đi 1.'],'Số liền trước 60 là số nào?',[s('60 − 1 = 59.')],'59.'),ex('sau','Dạng 2: Số liền sau',1,'Đề hỏi số đứng ngay sau.',['Đọc số đã cho.','Thêm 1.'],'Số liền sau 99 là số nào?',[s('99 + 1 = 100.')],'100.')],
  remember:['Liền trước bé hơn 1.','Liền sau lớn hơn 1.']}),
} satisfies LessonBook;
