import { lesson, know, rule, text, pic, vis, mistake } from '../../build';
import { example as ex, step as s } from '../authored';
import type { LessonBook } from '../../types';
export default {
 'g1.shapes2d': lesson('g1.shapes2d',{v:1,autoRead:true,goal:'nhận biết hình tròn, vuông, tam giác, chữ nhật.',
  know:[know('Nhìn đường bao',pic('shapesRowSVG',[{kind:'circle',color:'blue'},{kind:'triangle',color:'green'},{kind:'square',color:'red'},{kind:'rectangle',color:'yellow'}]),rule('Hình tròn có đường bao cong. Tam giác có ba cạnh.'),text('Hình vuông, chữ nhật có bốn cạnh.')),know('Vuông và chữ nhật',pic('shapeSVG','square'),text('Hình vuông có bốn cạnh bằng nhau.'))],
  forms:[ex('chon','Dạng 1: Tìm hình',1,'Đề yêu cầu gọi tên hình.',['Nhìn đường bao.','Đếm cạnh nếu có.'],'Hình này có tên là gì?',[s('Có ba cạnh.')],'Hình tam giác.',{visual:vis('shapeSVG','triangle')}),ex('dem','Dạng 2: Đếm hình',2,'Đề hỏi có mấy hình cùng loại.',['Tìm đúng loại hình.','Đếm từng hình một lần.'],'Có mấy hình tròn?',[s('Đếm được ba hình.')],'3 hình tròn.',{visual:vis('shapesGridSVG','circle',3)})],
  remember:['Nhìn đường bao để nhận hình.','Xoay hình không đổi tên hình.']}),
 'g1.shapes3d': lesson('g1.shapes3d',{v:1,autoRead:true,goal:'nhận biết khối lập phương và khối hộp chữ nhật.',
  know:[know('Khối lập phương',pic('solidSVG','cube'),rule('Khối lập phương giống một con xúc xắc.')),know('Khối hộp chữ nhật',pic('solidSVG','box'),text('Khối hộp chữ nhật giống một hộp giày.'))],
  forms:[ex('nhan','Dạng 1: Gọi tên khối',1,'Đề cho hình một khối.',['Nhìn toàn bộ khối.','Liên hệ đồ vật quen thuộc.'],'Gọi tên khối trong hình.',[s('Khối có dạng hộp giày.')],'Khối hộp chữ nhật.',{visual:vis('solidSVG','box')})],
  remember:['Xúc xắc: khối lập phương.','Hộp giày: khối hộp chữ nhật.']}),
 'g1.position': lesson('g1.position',{v:1,autoRead:true,goal:'nói vị trí của vật so với vật khác.',
  know:[know('So với vật nào?',rule('Chọn vật làm mốc trước khi nói vị trí.'),pic('positionSceneSVG','🐱','above'),text('Mèo ở phía trên chiếc bàn.')),know('Trái và phải',pic('positionSceneSVG','🐱','left'),text('Nhìn từ phía em, mèo ở bên trái bàn.'))],
  forms:[ex('tren','Dạng 1: Trên, dưới, trái, phải',1,'Hỏi vị trí một vật so với vật mốc.',['Tìm vật mốc.','Nhìn theo phía của em.'],'Mèo ở đâu so với bàn?',[s('Mèo nằm phía dưới bàn.')],'Phía dưới bàn.',{visual:vis('positionSceneSVG','🐱','below')}),ex('giua','Dạng 2: Trước, sau, ở giữa',2,'Các bạn xếp thành một hàng.',['Xác định đầu hàng.','So vị trí các bạn.'],'Từ lá cờ: chó, mèo, thỏ. Ai ở giữa?',[s('Mèo đứng sau chó và trước thỏ.')],'Bạn mèo.',{visual:vis('rowSVG',['🐶','🐱','🐰'],{flag:true})})],
  remember:['Luôn chọn vật làm mốc.','Nhìn đúng phía được yêu cầu.']}),
 'g1.length_cm': lesson('g1.length_cm',{v:1,autoRead:true,goal:'đo độ dài bằng thước có vạch xăng-ti-mét.',
  know:[know('Bắt đầu từ vạch 0',rule('Đặt đầu vật ở vạch 0. Đọc vạch tại đầu kia.'),pic('rulerSVG',5),text('Vật dài 5 cm. Đọc: năm xăng-ti-mét.'))],
  forms:[ex('do','Dạng 1: Đọc thước',1,'Một đầu vật trùng vạch 0.',['Tìm vạch đầu còn lại.','Đọc số kèm cm.'],'Vật trong hình dài bao nhiêu?',[s('Đầu kia ở vạch 7.')],'7 cm.',{visual:vis('rulerSVG',7)}),ex('ve','Dạng 2: Đo đoạn thẳng',2,'Cần đo một đoạn thẳng.',['Đặt vạch 0 trùng đầu đoạn.','Giữ thước thẳng theo đoạn.'],'Đầu đoạn ở 0, cuối đoạn ở 4.',[s('Đọc số 4 trên thước.')],'4 cm.')],
  mistakes:[mistake('Bạn Bi đặt đầu vật ở mép thước.','Đặt ở vạch 0.','Mép thước có thể không trùng vạch 0.')],remember:['Đặt đúng vạch 0.','Ghi đơn vị cm.']}),
 'g1.length_compare': lesson('g1.length_compare',{v:1,autoRead:true,goal:'nhận ra vật dài hơn, ngắn hơn.',
  know:[know('Đặt chung một đầu',rule('Đặt hai vật chung một đầu để so sánh.'),pic('sizePairSVG','long',true),text('Vật vươn xa hơn thì dài hơn.'))],
  forms:[ex('ss','Dạng 1: So độ dài',1,'Đề hỏi vật nào dài hơn.',['Đặt cùng điểm bắt đầu.','So đầu còn lại.'],'Dây đỏ dài 8 cm, dây xanh dài 5 cm.',[s('8 > 5.')],'Dây đỏ dài hơn.')],
  remember:['So từ cùng một đầu.','Số đo lớn hơn thì dài hơn.']}),
 'g1.length_ops': lesson('g1.length_ops',{v:1,autoRead:true,goal:'cộng, trừ độ dài có đơn vị cm.',
  know:[know('Tính số, giữ đơn vị',rule('Cộng, trừ các số đo cùng đơn vị cm.'),pic('polylineSVG',[3,4]),text('3 cm thêm 4 cm được 7 cm.'))],
  forms:[ex('cong','Dạng 1: Cộng độ dài',2,'Ghép hai đoạn lại.',['Cộng hai số đo.','Ghi cm sau kết quả.'],'Dây dài 5 cm, nối thêm 3 cm.',[s('Phép tính:', '5 + 3 = 8 (cm)')],'Trả lời: 8 cm.'),ex('tru','Dạng 2: Bớt độ dài',2,'Cắt bớt một đoạn.',['Trừ phần bị cắt.','Ghi cm sau kết quả.'],'Dây dài 9 cm, cắt đi 4 cm.',[s('Phép tính:', '9 − 4 = 5 (cm)')],'Trả lời: 5 cm.')],
  remember:['Cùng đơn vị mới tính.','Đừng quên cm.']}),
 'g1.clock': lesson('g1.clock',{v:1,autoRead:true,goal:'đọc giờ đúng trên đồng hồ.',
  know:[know('Kim dài chỉ 12',rule('Giờ đúng: kim dài chỉ 12. Kim ngắn chỉ số giờ.'),pic('clockSVG',7,0),text('Đồng hồ chỉ 7 giờ.'))],
  forms:[ex('doc','Dạng 1: Đọc giờ',1,'Kim dài chỉ số 12.',['Nhìn kim ngắn.','Đọc số giờ.'],'Đồng hồ chỉ mấy giờ?',[s('Kim ngắn chỉ số 9.')],'9 giờ.',{visual:vis('clockSVG',9,0)}),ex('chon','Dạng 2: Chọn đồng hồ',2,'Đề cho một giờ cần tìm.',['Kim dài phải chỉ 12.','Kim ngắn chỉ đúng số giờ.'],'Đồng hồ 3 giờ có hai kim thế nào?',[s('Kim dài chỉ 12. Kim ngắn chỉ 3.')],'Kim dài: 12; kim ngắn: 3.')],
  mistakes:[mistake('Bạn Bi đọc 12 giờ vì kim dài chỉ 12.','Đọc số kim ngắn chỉ.','Kim dài chỉ 12 cho biết đang là giờ đúng.')],remember:['Kim ngắn cho biết giờ.','Giờ đúng: kim dài chỉ 12.']}),
 'g1.weekday': lesson('g1.weekday',{v:1,autoRead:true,goal:'nhớ thứ tự các ngày trong tuần.',
  know:[know('Một tuần có bảy ngày',rule('Thứ Hai, Ba, Tư, Năm, Sáu, Bảy, Chủ nhật.'),pic('calendarDaySVG',5,10,1),text('Sau Chủ nhật lại đến thứ Hai.'))],
  forms:[ex('mai','Dạng 1: Ngày mai',1,'Đề hỏi thứ của ngày mai.',['Tìm thứ hôm nay.','Đọc thứ ngay sau.'],'Hôm nay thứ Sáu. Ngày mai là thứ mấy?',[s('Sau thứ Sáu là thứ Bảy.')],'Thứ Bảy.'),ex('qua','Dạng 2: Hôm qua',2,'Đề hỏi thứ của hôm qua.',['Tìm thứ hôm nay.','Đọc thứ ngay trước.'],'Hôm nay thứ Hai. Hôm qua là thứ mấy?',[s('Trước thứ Hai là Chủ nhật.')],'Chủ nhật.')],
  remember:['Một tuần có 7 ngày.','Sau Chủ nhật là thứ Hai.']}),
 'g1.calendar_day': lesson('g1.calendar_day',{v:1,autoRead:true,goal:'đọc thứ, ngày và tháng trên tờ lịch.',
  know:[know('Ba thông tin trên lịch',rule('Đọc riêng thứ, ngày và tháng.'),pic('calendarDaySVG',5,10,1),text('Thứ Hai, ngày 5, tháng 10.'))],
  forms:[ex('doc','Dạng 1: Đọc tờ lịch',1,'Đề cho một tờ lịch.',['Tìm chữ ghi thứ.','Đọc số ngày và tháng.'],'Tờ lịch ghi ngày nào?',[s('Thứ Sáu. Ngày 9. Tháng 10.')],'Thứ Sáu, ngày 9 tháng 10.',{visual:vis('calendarDaySVG',9,10,5)})],
  remember:['Thứ khác với ngày.','Đọc cả tháng khi trả lời.']}),
 'g1.daytime': lesson('g1.daytime',{v:1,autoRead:true,goal:'nhận biết các buổi trong ngày.',
  know:[know('Một ngày của em',rule('Các buổi lần lượt: sáng, trưa, chiều, tối.'),pic('dayPartSVG','morning'),text('Buổi sáng, em thức dậy và ăn sáng.')),know('Khi trời tối',pic('dayPartSVG','night'),text('Buổi tối, em chuẩn bị đi ngủ.'))],
  forms:[ex('buoi','Dạng 1: Chọn buổi phù hợp',1,'Đề kể một hoạt động trong ngày.',['Đọc dấu hiệu thời gian.','Chọn buổi phù hợp.'],'Em ăn trưa sau giờ học sáng. Đó là buổi nào?',[s('Ăn trưa vào buổi trưa.')],'Buổi trưa.')],
  remember:['Sau sáng là trưa, rồi chiều.','Sau chiều là tối.']}),
 'g1.word10': lesson('g1.word10',{v:1,autoRead:true,goal:'giải bài toán thêm, bớt trong phạm vi 10.',
  know:[know('Đọc chuyện rồi chọn phép tính',rule('Thêm: cộng. Bớt: trừ.'),pic('groupsSVG',[{emoji:'🍎',n:4},{emoji:'🍎',n:2}]),text('4 quả thêm 2 quả: 4 + 2 = 6.'))],
  forms:[ex('them','Dạng 1: Thêm vào',2,'Đề hỏi có tất cả sau khi thêm.',['Tìm số ban đầu và số thêm.','Cộng rồi trả lời.'],'Lan có 3 bút. Mẹ cho thêm 4 bút. Lan có mấy bút?',[s('Phép tính:', '3 + 4 = 7')],'Trả lời: Lan có 7 bút.'),ex('bot','Dạng 2: Bớt đi',3,'Đề hỏi còn lại sau khi bớt.',['Tìm số ban đầu và số bớt.','Trừ rồi trả lời.'],'Có 9 con chim. 3 con bay đi. Còn mấy con?',[s('Phép tính:', '9 − 3 = 6')],'Trả lời: Còn 6 con chim.')],
  remember:['Tìm điều đề hỏi.','Trả lời kèm tên đồ vật.']}),
 'g1.word100': lesson('g1.word100',{v:1,autoRead:true,goal:'giải bài toán cộng, trừ trong phạm vi 100.',
  know:[know('Số lớn hơn, cách làm quen thuộc',rule('Thêm hoặc gộp thì cộng. Bớt đi thì trừ.'),pic('tensOnesSVG',2,4),text('24 thêm 13: 24 + 13 = 37.'))],
  forms:[ex('gop','Dạng 1: Tìm tất cả',2,'Đề cho hai nhóm, hỏi tất cả.',['Tìm số của hai nhóm.','Cộng và trả lời.'],'Có 23 bút đỏ và 15 bút xanh. Có tất cả mấy bút?',[s('Phép tính:', '23 + 15 = 38')],'Trả lời: Có 38 bút.'),ex('con','Dạng 2: Tìm còn lại',3,'Đề cho số ban đầu và số lấy đi.',['Xác định số bị lấy đi.','Trừ và trả lời.'],'Có 48 quyển vở. Đã phát 26 quyển. Còn bao nhiêu quyển?',[s('Phép tính:', '48 − 26 = 22')],'Trả lời: Còn 22 quyển vở.')],
  remember:['Chọn phép tính theo câu chuyện.','Đọc lại câu hỏi trước khi trả lời.']}),
} satisfies LessonBook;
