// ============================================================================
//  Danh mục kỹ năng Ôn Luyện theo Chương trình Toán GDPT 2018 (docs/study-wow-plan.md mục 7).
//  Topic = thẻ hiển thị (giữ id cũ để tương thích lịch sử / MathRacing); Skill = đơn vị luyện tập.
// ============================================================================
import { Grade } from '../../types';
import type { Level, OpTag, SkillDef, Strand, Term } from './types';

export interface TopicMeta {
    id: string;
    grade: Grade;
    title: string;
    description: string;
    strand: Strand;
    icon: string;      // tên icon lucide-react
    order: number;
    advanced?: boolean;
}

type Flags = { advanced?: boolean; ops?: OpTag[] };
type Row = [id: string, topicId: string, strand: Strand, term: Term, title: string, levels: Level[], flags?: Flags];

const A = { advanced: true } as const;
const add: Flags = { ops: ['addition'] }, sub: Flags = { ops: ['subtraction'] }, addsub: Flags = { ops: ['addition', 'subtraction'] };
const mul: Flags = { ops: ['multiplication'] }, div: Flags = { ops: ['division'] }, muldiv: Flags = { ops: ['multiplication', 'division'] };
const geo: Flags = { ops: ['geometry'] }, frac: Flags = { ops: ['fractions'] };

const ROWS: Record<Grade, Row[]> = {
    [Grade.Preschool]: [
        ['mn.count', 'mn_counting', 'number', 1, 'Đếm đến 10', [1]],
        ['mn.numeral', 'mn_counting', 'number', 1, 'Nhận biết số 0–10', [1]],
        ['mn.more_less', 'mn_counting', 'number', 1, 'Nhiều hơn – ít hơn – bằng nhau', [1, 2]],
        ['mn.ordinal', 'mn_counting', 'number', 1, 'Số thứ tự', [2]],
        ['mn.combine', 'mn_counting', 'number', 1, 'Gộp – tách nhóm', [2]],
        ['mn.pattern', 'mn_counting', 'number', 1, 'Quy luật sắp xếp', [2, 3]],
        ['mn.shapes2d', 'mn_shapes', 'geometry', 1, 'Hình tròn, vuông, tam giác, chữ nhật', [1, 2], geo],
        ['mn.shapes3d', 'mn_shapes', 'geometry', 1, 'Khối cầu, trụ, vuông, chữ nhật', [1], geo],
        ['mn.size', 'mn_shapes', 'measurement', 1, 'To – nhỏ, cao – thấp, dài – ngắn', [1]],
        ['mn.position', 'mn_shapes', 'geometry', 1, 'Trên – dưới, trước – sau, trái – phải', [1, 2]],
        ['mn.colors', 'mn_colors', 'explore', 1, 'Màu sắc', [1]],
        ['mn.daytime', 'mn_time', 'explore', 1, 'Buổi trong ngày, hôm qua – hôm nay – ngày mai', [1, 2]],
    ],
    [Grade.Grade1]: [
        ['g1.count5', 'g1_numbers_5', 'number', 1, 'Đếm, đọc, viết số 0–5', [1]],
        ['g1.compare5', 'g1_numbers_5', 'number', 1, 'So sánh các số trong phạm vi 5', [1, 2]],
        ['g1.order5', 'g1_numbers_5', 'number', 1, 'Thứ tự các số, điền dãy số', [1, 2]],
        ['g1.count10', 'g1_numbers_10', 'number', 1, 'Đếm, đọc, viết số 0–10', [1]],
        ['g1.compare10', 'g1_numbers_10', 'number', 1, 'So sánh, số lớn nhất, bé nhất', [1, 2]],
        ['g1.split10', 'g1_numbers_10', 'number', 1, 'Mấy và mấy (tách – gộp số)', [1, 2]],
        ['g1.add10', 'g1_addition_10', 'number', 1, 'Phép cộng trong phạm vi 10', [1, 2], add],
        ['g1.add10_missing', 'g1_addition_10', 'number', 1, 'Tìm số trong phép cộng', [2], add],
        ['g1.add10_compare', 'g1_addition_10', 'number', 1, 'So sánh tổng', [2, 3], add],
        ['g1.sub10', 'g1_subtraction_10', 'number', 1, 'Phép trừ trong phạm vi 10', [1, 2], sub],
        ['g1.sub10_missing', 'g1_subtraction_10', 'number', 1, 'Tìm số trong phép trừ', [2], sub],
        ['g1.chain10', 'g1_subtraction_10', 'number', 1, 'Tính có hai dấu phép tính', [2, 3], addsub],
        ['g1.write_eq', 'g1_subtraction_10', 'number', 1, 'Viết phép tính theo tranh', [2, 3], addsub],
        ['g1.shapes2d', 'g1_geometry', 'geometry', 1, 'Hình vuông, tròn, tam giác, chữ nhật', [1, 2], geo],
        ['g1.shapes3d', 'g1_geometry', 'geometry', 1, 'Khối lập phương, khối hộp chữ nhật', [1], geo],
        ['g1.position', 'g1_geometry', 'geometry', 1, 'Vị trí: trên, dưới, trái, phải, trước, sau, ở giữa', [1, 2], geo],
        ['g1.numbers20', 'g1_numbers_20', 'number', 2, 'Các số 11–20: chục và đơn vị, so sánh', [1, 2]],
        ['g1.numbers100', 'g1_numbers_100', 'number', 2, 'Số đến 100: đọc, viết, chục – đơn vị', [1, 2]],
        ['g1.compare100', 'g1_numbers_100', 'number', 2, 'So sánh, sắp xếp các số trong phạm vi 100', [1, 2]],
        ['g1.neighbors100', 'g1_numbers_100', 'number', 2, 'Số liền trước, số liền sau', [1]],
        ['g1.addsub100', 'g1_add_sub_100', 'number', 2, 'Cộng, trừ không nhớ trong phạm vi 100', [1, 2, 3], addsub],
        ['g1.addsub20', 'g1_operations_20', 'number', 2, 'Cộng, trừ không qua 10 trong phạm vi 20', [1, 2], addsub],
        ['g1.carry20', 'g1_operations_20', 'number', 2, 'Cộng, trừ qua 10 trong phạm vi 20', [2], { ...A, ...addsub }],
        ['g1.length_cm', 'g1_length', 'measurement', 2, 'Đo độ dài bằng thước (cm)', [1, 2]],
        ['g1.length_compare', 'g1_length', 'measurement', 2, 'Dài hơn, ngắn hơn', [1]],
        ['g1.length_ops', 'g1_length', 'measurement', 2, 'Cộng, trừ số đo độ dài (cm)', [2], addsub],
        ['g1.clock', 'g1_clock', 'measurement', 2, 'Xem giờ đúng', [1, 2]],
        ['g1.weekday', 'g1_time', 'measurement', 2, 'Các ngày trong tuần', [1, 2]],
        ['g1.calendar_day', 'g1_time', 'measurement', 2, 'Xem lịch tờ hằng ngày', [1]],
        ['g1.daytime', 'g1_time', 'measurement', 2, 'Các buổi trong ngày', [1]],
        ['g1.word10', 'g1_word_problems', 'number', 1, 'Bài toán thêm, bớt trong phạm vi 10', [2, 3], addsub],
        ['g1.word100', 'g1_word_problems', 'number', 2, 'Bài toán có lời văn trong phạm vi 100', [2, 3], addsub],
    ],
    [Grade.Grade2]: [
        ['g2.addsub20', 'g2_add_sub_20', 'number', 1, 'Phép cộng, phép trừ (qua 10) trong phạm vi 20', [1, 2], addsub],
        ['g2.addsub100_nc', 'g2_add_sub_no_carry', 'number', 1, 'Cộng, trừ không nhớ trong phạm vi 100', [1, 2], addsub],
        ['g2.addsub100_c', 'g2_add_sub_carry', 'number', 1, 'Cộng, trừ có nhớ trong phạm vi 100', [1, 2, 3], addsub],
        ['g2.chain', 'g2_add_sub_carry', 'number', 1, 'Tính có hai dấu phép tính', [2], addsub],
        ['g2.terms', 'g2_arithmetic_advanced', 'number', 1, 'Số hạng – tổng, số bị trừ – số trừ – hiệu', [1], addsub],
        ['g2.missing', 'g2_arithmetic_advanced', 'number', 1, 'Tìm số hạng, số bị trừ, số trừ', [2], addsub],
        ['g2.compare_expr', 'g2_arithmetic_advanced', 'number', 1, 'Điền dấu >, <, =', [2], addsub],
        ['g2.word_more_less', 'g2_arithmetic_advanced', 'number', 1, 'Bài toán về nhiều hơn, ít hơn', [2, 3], addsub],
        ['g2.kg', 'g2_units_measure', 'measurement', 1, 'Ki-lô-gam: nặng hơn, nhẹ hơn', [1, 2]],
        ['g2.liter', 'g2_units_measure', 'measurement', 1, 'Lít', [1, 2]],
        ['g2.length', 'g2_units_measure', 'measurement', 2, 'Đề-xi-mét, mét, ki-lô-mét', [1, 2]],
        ['g2.clock', 'g2_time_calendar', 'measurement', 1, 'Xem đồng hồ (kim phút chỉ số 3, số 6)', [1, 2]],
        ['g2.hours_day', 'g2_time_calendar', 'measurement', 1, 'Ngày – giờ, giờ – phút', [1, 2]],
        ['g2.calendar_month', 'g2_time_calendar', 'measurement', 1, 'Ngày – tháng, xem lịch tháng', [1, 2]],
        ['g2.points_lines', 'g2_geometry_basic', 'geometry', 1, 'Điểm, đoạn thẳng, đường thẳng, đường cong, ba điểm thẳng hàng', [1, 2], geo],
        ['g2.polyline', 'g2_geometry_basic', 'geometry', 1, 'Đường gấp khúc, độ dài đường gấp khúc', [1, 2], geo],
        ['g2.quadrilateral', 'g2_geometry_basic', 'geometry', 1, 'Hình tứ giác', [1, 2], geo],
        ['g2.shapes3d', 'g2_geometry_basic', 'geometry', 2, 'Khối trụ, khối cầu', [1], geo],
        ['g2.mul_meaning', 'g2_multiplication', 'number', 2, 'Phép nhân: thừa số, tích', [1, 2], mul],
        ['g2.mul_table', 'g2_multiplication', 'number', 2, 'Bảng nhân 2, bảng nhân 5', [1, 2], mul],
        ['g2.mul_table34', 'g2_multiplication', 'number', 2, 'Bảng nhân 3, bảng nhân 4', [1, 2], { ...A, ...mul }],
        ['g2.div_meaning', 'g2_division', 'number', 2, 'Phép chia: số bị chia, số chia, thương', [1, 2], div],
        ['g2.div_table', 'g2_division', 'number', 2, 'Bảng chia 2, bảng chia 5', [1, 2], div],
        ['g2.div_table34', 'g2_division', 'number', 2, 'Bảng chia 3, 4; tìm số bị chia', [2], { ...A, ...div }],
        ['g2.numbers1000', 'g2_numbers_1000', 'number', 2, 'Số đến 1000: trăm – chục – đơn vị, số tròn trăm', [1, 2]],
        ['g2.compare1000', 'g2_numbers_1000', 'number', 2, 'So sánh, sắp xếp các số đến 1000', [1, 2]],
        ['g2.addsub1000', 'g2_add_sub_1000', 'number', 2, 'Cộng, trừ trong phạm vi 1000', [1, 2, 3], addsub],
        ['g2.money', 'g2_money', 'measurement', 2, 'Tiền Việt Nam (100, 200, 500, 1000 đồng)', [1, 2]],
        ['g2.money_big', 'g2_money', 'measurement', 2, 'Tiền Việt Nam đến 50 000 đồng', [2], A],
        ['g2.tally', 'g2_statistics', 'statistics', 2, 'Thu thập, kiểm đếm số liệu', [1, 2]],
        ['g2.pictograph', 'g2_statistics', 'statistics', 2, 'Biểu đồ tranh', [1, 2]],
        ['g2.chance', 'g2_probability', 'probability', 2, 'Chắc chắn, có thể, không thể', [1, 2]],
    ],
    [Grade.Grade3]: [
        ['g3.mul_tables', 'g3_multiplication', 'number', 1, 'Bảng nhân 3, 4, 6, 7, 8, 9', [1, 2], mul],
        ['g3.mul_1digit', 'g3_multiplication', 'number', 1, 'Nhân số có hai, ba chữ số với số có một chữ số', [1, 2, 3], mul],
        ['g3.times_more', 'g3_multiplication', 'number', 1, 'Gấp một số lên nhiều lần', [2, 3], mul],
        ['g3.mul_2digit', 'g3_multiplication', 'number', 1, 'Nhân với số có hai chữ số', [2], { ...A, ...mul }],
        ['g3.div_tables', 'g3_division', 'number', 1, 'Bảng chia 3, 4, 6, 7, 8, 9', [1, 2], div],
        ['g3.div_1digit', 'g3_division', 'number', 1, 'Chia cho số có một chữ số, phép chia có dư', [1, 2, 3], div],
        ['g3.times_less', 'g3_division', 'number', 1, 'Giảm một số đi nhiều lần', [2, 3], div],
        ['g3.how_many_times', 'g3_division', 'number', 1, 'Số lớn gấp mấy lần số bé', [2, 3], div],
        ['g3.expression', 'g3_expressions', 'number', 1, 'Biểu thức số, thứ tự thực hiện', [1, 2, 3], muldiv],
        ['g3.missing', 'g3_expressions', 'number', 1, 'Tìm thừa số, số bị chia, số chia', [2], muldiv],
        ['g3.unit_fraction', 'g3_fractions', 'number', 1, 'Một phần hai, một phần ba, … một phần chín', [1], frac],
        ['g3.fraction_of', 'g3_fractions', 'number', 1, 'Tìm một phần mấy của một số', [2, 3], frac],
        ['g3.fraction_ab', 'g3_fractions', 'number', 1, 'Phân số a/b', [2], { ...A, ...frac }],
        ['g3.midpoint', 'g3_geometry', 'geometry', 1, 'Điểm ở giữa, trung điểm của đoạn thẳng', [1, 2], geo],
        ['g3.circle', 'g3_geometry', 'geometry', 1, 'Hình tròn: tâm, bán kính, đường kính', [1, 2], geo],
        ['g3.right_angle', 'g3_geometry', 'geometry', 1, 'Góc vuông, góc không vuông', [1], geo],
        ['g3.polygon', 'g3_geometry', 'geometry', 1, 'Hình tam giác, hình tứ giác: đỉnh, cạnh, góc', [1, 2], geo],
        ['g3.rect_square', 'g3_geometry', 'geometry', 1, 'Hình chữ nhật, hình vuông', [1], geo],
        ['g3.solids', 'g3_geometry', 'geometry', 1, 'Khối lập phương, khối hộp chữ nhật', [1, 2], geo],
        ['g3.small_units', 'g3_measurements', 'measurement', 1, 'Mi-li-mét, gam, mi-li-lít', [1, 2, 3]],
        ['g3.temperature', 'g3_measurements', 'measurement', 1, 'Nhiệt độ (°C)', [1]],
        ['g3.numbers10000', 'g3_numbers', 'number', 2, 'Các số đến 10 000', [1, 2]],
        ['g3.numbers100000', 'g3_numbers', 'number', 2, 'Các số đến 100 000', [1, 2]],
        ['g3.compare', 'g3_numbers', 'number', 2, 'So sánh, sắp xếp các số', [1, 2]],
        ['g3.round', 'g3_numbers', 'number', 2, 'Làm tròn số', [2]],
        ['g3.roman', 'g3_numbers', 'number', 2, 'Chữ số La Mã', [1, 2]],
        ['g3.addsub100000', 'g3_arithmetic', 'number', 2, 'Cộng, trừ trong phạm vi 100 000', [1, 2, 3], addsub],
        ['g3.muldiv_big', 'g3_arithmetic', 'number', 2, 'Nhân, chia số có nhiều chữ số với số có một chữ số', [1, 2], muldiv],
        ['g3.perimeter', 'g3_area', 'geometry', 2, 'Chu vi hình tam giác, tứ giác, hình chữ nhật, hình vuông', [1, 2, 3], geo],
        ['g3.area_cm2', 'g3_area', 'measurement', 2, 'Diện tích: xăng-ti-mét vuông, hình chữ nhật, hình vuông', [1, 2, 3], geo],
        ['g3.clock_minute', 'g3_time', 'measurement', 2, 'Xem đồng hồ chính xác đến từng phút', [1, 2]],
        ['g3.month_year', 'g3_time', 'measurement', 2, 'Tháng – năm', [1, 2]],
        ['g3.duration', 'g3_time', 'measurement', 2, 'Khoảng thời gian', [2, 3]],
        ['g3.money', 'g3_money', 'measurement', 2, 'Tiền Việt Nam (đến 100 000 đồng)', [1, 2, 3]],
        ['g3.data_table', 'g3_statistics', 'statistics', 2, 'Bảng số liệu', [1, 2]],
        ['g3.bar_chart', 'g3_statistics', 'statistics', 2, 'Biểu đồ cột', [2], A],
        ['g3.chance', 'g3_probability', 'probability', 2, 'Khả năng xảy ra của một sự kiện', [1, 2]],
        ['g3.word_2step', 'g3_word_problems', 'number', 2, 'Bài toán giải bằng hai bước tính', [2, 3]],
        ['g3.sum_diff', 'g3_word_problems', 'number', 2, 'Tìm hai số khi biết tổng và hiệu', [3], A],
    ],
    [Grade.Grade4]: [
        ['g4.read_write', 'g4_large_numbers', 'number', 1, 'Đọc, viết số đến lớp triệu', [1, 2]],
        ['g4.place_class', 'g4_large_numbers', 'number', 1, 'Hàng và lớp, giá trị của chữ số', [1, 2]],
        ['g4.compare', 'g4_large_numbers', 'number', 1, 'So sánh, sắp xếp số có nhiều chữ số', [1, 2]],
        ['g4.round', 'g4_large_numbers', 'number', 1, 'Làm tròn số đến hàng trăm nghìn', [2]],
        ['g4.even_odd', 'g4_large_numbers', 'number', 1, 'Số chẵn, số lẻ', [1, 2]],
        ['g4.addsub', 'g4_add_sub', 'number', 1, 'Cộng, trừ số có nhiều chữ số', [1, 2, 3], addsub],
        ['g4.properties_add', 'g4_add_sub', 'number', 1, 'Tính chất giao hoán, kết hợp của phép cộng', [2, 3], add],
        ['g4.letter_expr', 'g4_add_sub', 'number', 1, 'Biểu thức chứa chữ', [2], addsub],
        ['g4.angle_types', 'g4_angles', 'geometry', 1, 'Góc nhọn, góc vuông, góc tù, góc bẹt', [1], geo],
        ['g4.angle_measure', 'g4_angles', 'geometry', 1, 'Đo góc, đơn vị đo góc (độ)', [2], geo],
        ['g4.angle_compare', 'g4_angles', 'geometry', 1, 'So sánh các góc', [2], geo],
        ['g4.perp_parallel', 'g4_lines', 'geometry', 1, 'Hai đường thẳng vuông góc, song song', [1, 2], geo],
        ['g4.mass', 'g4_units', 'measurement', 1, 'Yến, tạ, tấn', [1, 2]],
        ['g4.area_units', 'g4_units', 'measurement', 1, 'Đề-xi-mét vuông, mét vuông, mi-li-mét vuông', [1, 2]],
        ['g4.time_units', 'g4_units', 'measurement', 1, 'Giây, thế kỉ', [1, 2]],
        ['g4.mul', 'g4_multiplication', 'number', 2, 'Nhân với số có một, hai chữ số', [1, 2, 3], mul],
        ['g4.mul10', 'g4_multiplication', 'number', 2, 'Nhân với 10, 100, 1000; nhân số tròn chục', [1, 2], mul],
        ['g4.properties_mul', 'g4_multiplication', 'number', 2, 'Tính chất của phép nhân', [2, 3], mul],
        ['g4.div', 'g4_division', 'number', 2, 'Chia cho số có một, hai chữ số', [1, 2, 3], div],
        ['g4.div10', 'g4_division', 'number', 2, 'Chia cho 10, 100, 1000', [1, 2], div],
        ['g4.expr', 'g4_parentheses', 'number', 2, 'Biểu thức có dấu ngoặc', [2, 3], muldiv],
        ['g4.average', 'g4_average', 'number', 2, 'Số trung bình cộng', [2, 3]],
        ['g4.sum_diff', 'g4_word_problems', 'number', 2, 'Tìm hai số khi biết tổng và hiệu', [2, 3]],
        ['g4.unit_rate', 'g4_word_problems', 'number', 2, 'Bài toán liên quan đến rút về đơn vị', [2, 3]],
        ['g4.word_multi', 'g4_word_problems', 'number', 2, 'Bài toán giải bằng hai, ba bước tính', [3]],
        ['g4.fraction_concept', 'g4_fractions', 'number', 2, 'Khái niệm phân số', [1], frac],
        ['g4.fraction_equiv', 'g4_fractions', 'number', 2, 'Tính chất cơ bản, rút gọn phân số', [1, 2], frac],
        ['g4.fraction_common', 'g4_fractions', 'number', 2, 'Quy đồng mẫu số', [2], frac],
        ['g4.fraction_compare', 'g4_fractions', 'number', 2, 'So sánh phân số', [1, 2], frac],
        ['g4.frac_addsub', 'g4_fraction_ops', 'number', 2, 'Cộng, trừ phân số', [1, 2], frac],
        ['g4.frac_mul', 'g4_fraction_ops', 'number', 2, 'Phép nhân phân số', [1, 2], frac],
        ['g4.frac_div', 'g4_fraction_ops', 'number', 2, 'Phép chia phân số', [2], frac],
        ['g4.fraction_of', 'g4_fraction_ops', 'number', 2, 'Tìm phân số của một số', [2, 3], frac],
        ['g4.frac_addsub_any', 'g4_fraction_ops', 'number', 2, 'Cộng, trừ phân số khác mẫu số', [2], { ...A, ...frac }],
        ['g4.para_rhombus_id', 'g4_geometry_2d', 'geometry', 2, 'Hình bình hành, hình thoi', [1, 2], geo],
        ['g4.rect_word', 'g4_geometry_2d', 'geometry', 2, 'Chu vi, diện tích hình chữ nhật, hình vuông', [2, 3], geo],
        ['g4.para_area', 'g4_para_rhombus', 'geometry', 2, 'Diện tích hình bình hành, hình thoi', [2], { ...A, ...geo }],
        ['g4.data_series', 'g4_statistics', 'statistics', 2, 'Dãy số liệu thống kê', [1, 2]],
        ['g4.bar_chart', 'g4_statistics', 'statistics', 2, 'Biểu đồ cột', [1, 2, 3]],
        ['g4.events', 'g4_statistics', 'probability', 2, 'Số lần xuất hiện của một sự kiện', [1, 2]],
        ['g4.sequence', 'g4_patterns', 'number', 1, 'Dãy số theo quy luật', [2, 3]],
        ['g4.divisibility', 'g4_divisibility', 'number', 2, 'Dấu hiệu chia hết cho 2, 3, 5, 9', [2], A],
    ],
    [Grade.Grade5]: [
        ['g5.decimal_fraction', 'g5_fractions', 'number', 1, 'Phân số thập phân', [1], frac],
        ['g5.mixed_number', 'g5_fractions', 'number', 1, 'Hỗn số', [1, 2], frac],
        ['g5.frac_addsub', 'g5_fractions', 'number', 1, 'Cộng, trừ phân số khác mẫu số', [1, 2], frac],
        ['g5.frac_muldiv', 'g5_fractions', 'number', 1, 'Nhân, chia phân số', [1, 2], frac],
        ['g5.frac_compare', 'g5_fractions', 'number', 1, 'So sánh phân số', [1, 2], frac],
        ['g5.decimal_read', 'g5_numbers', 'number', 1, 'Số thập phân: đọc, viết, hàng', [1, 2]],
        ['g5.decimal_compare', 'g5_numbers', 'number', 1, 'So sánh, sắp xếp số thập phân', [1, 2]],
        ['g5.decimal_round', 'g5_numbers', 'number', 1, 'Làm tròn số thập phân', [2]],
        ['g5.measure_decimal', 'g5_numbers', 'measurement', 1, 'Viết số đo đại lượng dưới dạng số thập phân', [2]],
        ['g5.dec_addsub', 'g5_decimal_ops', 'number', 1, 'Cộng, trừ số thập phân', [1, 2], addsub],
        ['g5.dec_mul', 'g5_decimal_ops', 'number', 1, 'Nhân số thập phân', [1, 2], mul],
        ['g5.dec_div', 'g5_decimal_ops', 'number', 1, 'Chia số thập phân', [1, 2], div],
        ['g5.dec_shift', 'g5_decimal_ops', 'number', 1, 'Nhân, chia số thập phân với 10, 100, 1000; 0,1; 0,01', [1, 2], muldiv],
        ['g5.area_units_big', 'g5_measurements', 'measurement', 1, 'Héc-ta, ki-lô-mét vuông và các đơn vị đo diện tích', [1, 2]],
        ['g5.volume_units', 'g5_measurements', 'measurement', 2, 'Xăng-ti-mét khối, đề-xi-mét khối, mét khối', [1, 2]],
        ['g5.ratio', 'g5_ratios', 'number', 1, 'Tỉ số', [1, 2]],
        ['g5.percent', 'g5_ratios', 'number', 1, 'Tỉ số phần trăm', [1, 2, 3]],
        ['g5.map_scale', 'g5_ratios', 'measurement', 1, 'Tỉ lệ bản đồ', [2, 3]],
        ['g5.sum_diff_ratio', 'g5_ratios', 'number', 1, 'Tìm hai số khi biết tổng (hiệu) và tỉ số', [3]],
        ['g5.interest', 'g5_ratios', 'number', 1, 'Lãi suất, tăng rồi giảm phần trăm', [3], A],
        ['g5.triangle_area', 'g5_geometry', 'geometry', 2, 'Diện tích hình tam giác', [1, 2], geo],
        ['g5.trapezoid_area', 'g5_geometry', 'geometry', 2, 'Diện tích hình thang', [1, 2], geo],
        ['g5.circle', 'g5_geometry', 'geometry', 2, 'Hình tròn: đường kính, chu vi, diện tích', [1, 2, 3], geo],
        ['g5.solid_area', 'g5_geometry', 'geometry', 2, 'Diện tích xung quanh, diện tích toàn phần', [2, 3], geo],
        ['g5.volume', 'g5_geometry', 'geometry', 2, 'Thể tích hình hộp chữ nhật, hình lập phương', [1, 2, 3], geo],
        ['g5.nets', 'g5_geometry', 'geometry', 2, 'Hình khai triển', [1], geo],
        ['g5.para_area', 'g5_geometry', 'geometry', 2, 'Diện tích hình bình hành', [2], { ...A, ...geo }],
        ['g5.time_addsub', 'g5_time_ops', 'measurement', 2, 'Cộng, trừ số đo thời gian', [1, 2]],
        ['g5.time_muldiv', 'g5_time_ops', 'measurement', 2, 'Nhân, chia số đo thời gian', [2]],
        ['g5.motion', 'g5_word_problems', 'number', 2, 'Vận tốc, quãng đường, thời gian', [1, 2, 3]],
        ['g5.motion_two', 'g5_word_problems', 'number', 2, 'Hai chuyển động: gặp nhau, đuổi kịp', [3]],
        ['g5.work_together', 'g5_word_problems', 'number', 2, 'Làm chung một công việc', [3], A],
        ['g5.stream', 'g5_word_problems', 'number', 2, 'Chuyển động trên dòng nước', [3], A],
        ['g5.expr', 'g5_parentheses', 'number', 1, 'Biểu thức có dấu ngoặc', [2, 3], muldiv],
        ['g5.pie_chart', 'g5_statistics', 'statistics', 2, 'Biểu đồ hình quạt tròn', [1, 2]],
        ['g5.bar_read', 'g5_statistics', 'statistics', 2, 'Đọc biểu đồ cột', [1, 2]],
        ['g5.chance_ratio', 'g5_statistics', 'probability', 2, 'Tỉ số mô tả số lần lặp lại của một khả năng', [2]],
    ],
};

export const SKILLS: SkillDef[] = (Object.entries(ROWS) as unknown as [string, Row[]][]).flatMap(([g, rows]) =>
    rows.map(([id, topicId, strand, term, title, levels, flags]) => ({ id, grade: Number(g) as Grade, topicId, strand, term, title, levels, ...flags })));

const M = (id: string, grade: Grade, title: string, description: string, strand: Strand, icon: string, order: number, advanced?: boolean): TopicMeta =>
    ({ id, grade, title, description, strand, icon, order, advanced });

/** Thẻ chủ đề (thứ tự hiển thị trong mạch theo `order`). */
export const TOPIC_META: TopicMeta[] = [
    M('mn_counting', Grade.Preschool, 'Đếm và số', 'Đếm, nhận biết số, nhiều – ít, quy luật', 'number', 'Calculator', 1),
    M('mn_shapes', Grade.Preschool, 'Hình và vị trí', 'Hình, khối, to – nhỏ, trên – dưới', 'geometry', 'Shapes', 2),
    M('mn_colors', Grade.Preschool, 'Màu sắc', 'Nhận biết các màu cơ bản', 'explore', 'Palette', 3),
    M('mn_time', Grade.Preschool, 'Thời gian', 'Sáng, trưa, chiều, tối; hôm qua, hôm nay', 'explore', 'Sun', 4),

    M('g1_numbers_5', Grade.Grade1, 'Các số đến 5', 'Đếm, so sánh, thứ tự', 'number', 'Hash', 1),
    M('g1_numbers_10', Grade.Grade1, 'Các số đến 10', 'Đếm, so sánh, mấy và mấy', 'number', 'Hash', 2),
    M('g1_addition_10', Grade.Grade1, 'Phép cộng trong phạm vi 10', 'Cộng bằng hình và số', 'number', 'Plus', 3),
    M('g1_subtraction_10', Grade.Grade1, 'Phép trừ trong phạm vi 10', 'Trừ, tính có hai dấu, viết phép tính', 'number', 'Minus', 4),
    M('g1_word_problems', Grade.Grade1, 'Bài toán có lời văn', 'Thêm, bớt, gộp lại, còn lại', 'number', 'BookOpen', 5),
    M('g1_numbers_20', Grade.Grade1, 'Các số đến 20', 'Chục và đơn vị', 'number', 'Hash', 6),
    M('g1_numbers_100', Grade.Grade1, 'Các số đến 100', 'Đọc, viết, so sánh', 'number', 'Hash', 7),
    M('g1_operations_20', Grade.Grade1, 'Cộng, trừ trong phạm vi 20', 'Không qua 10', 'number', 'Calculator', 8),
    M('g1_add_sub_100', Grade.Grade1, 'Cộng, trừ trong phạm vi 100', 'Không nhớ', 'number', 'Calculator', 9),
    M('g1_geometry', Grade.Grade1, 'Hình phẳng, khối, vị trí', 'Nhận dạng hình, khối, định hướng', 'geometry', 'Shapes', 10),
    M('g1_length', Grade.Grade1, 'Độ dài', 'Xăng-ti-mét, dài hơn – ngắn hơn', 'measurement', 'Ruler', 11),
    M('g1_clock', Grade.Grade1, 'Xem đồng hồ', 'Giờ đúng', 'measurement', 'Clock', 12),
    M('g1_time', Grade.Grade1, 'Ngày trong tuần', 'Thứ, ngày, buổi trong ngày', 'measurement', 'CalendarDays', 13),

    M('g2_add_sub_20', Grade.Grade2, 'Cộng, trừ qua 10 (phạm vi 20)', 'Bảng cộng, bảng trừ', 'number', 'Calculator', 1),
    M('g2_add_sub_no_carry', Grade.Grade2, 'Cộng, trừ không nhớ (phạm vi 100)', 'Ôn tập, tìm số', 'number', 'Plus', 2),
    M('g2_add_sub_carry', Grade.Grade2, 'Cộng, trừ có nhớ (phạm vi 100)', 'Đặt tính, tính có hai dấu', 'number', 'Plus', 3),
    M('g2_arithmetic_advanced', Grade.Grade2, 'Thành phần phép tính & bài toán', 'Tìm số, điền dấu, nhiều hơn – ít hơn', 'number', 'BookOpen', 4),
    M('g2_multiplication', Grade.Grade2, 'Phép nhân', 'Bảng nhân 2, 5', 'number', 'X', 5),
    M('g2_division', Grade.Grade2, 'Phép chia', 'Bảng chia 2, 5', 'number', 'Divide', 6),
    M('g2_numbers_1000', Grade.Grade2, 'Các số đến 1000', 'Trăm, chục, đơn vị; so sánh', 'number', 'Hash', 7),
    M('g2_add_sub_1000', Grade.Grade2, 'Cộng, trừ trong phạm vi 1000', 'Không nhớ và có nhớ', 'number', 'Calculator', 8),
    M('g2_geometry_basic', Grade.Grade2, 'Hình học', 'Đoạn thẳng, đường gấp khúc, tứ giác, khối', 'geometry', 'Shapes', 9),
    M('g2_units_measure', Grade.Grade2, 'Khối lượng, dung tích, độ dài', 'kg, lít, dm, m, km', 'measurement', 'Scale', 10),
    M('g2_time_calendar', Grade.Grade2, 'Thời gian & lịch', 'Đồng hồ, ngày – giờ, lịch tháng', 'measurement', 'Clock', 11),
    M('g2_money', Grade.Grade2, 'Tiền Việt Nam', 'Nhận biết, đổi tiền, mua bán', 'measurement', 'Coins', 12),
    M('g2_statistics', Grade.Grade2, 'Kiểm đếm & biểu đồ tranh', 'Thu thập, đọc biểu đồ tranh', 'statistics', 'BarChart3', 13),
    M('g2_probability', Grade.Grade2, 'Có thể, chắc chắn, không thể', 'Làm quen với khả năng xảy ra', 'probability', 'Dices', 14),

    M('g3_multiplication', Grade.Grade3, 'Phép nhân', 'Bảng nhân, nhân với số có một chữ số, gấp lên', 'number', 'X', 1),
    M('g3_division', Grade.Grade3, 'Phép chia', 'Bảng chia, chia có dư, giảm đi, gấp mấy lần', 'number', 'Divide', 2),
    M('g3_expressions', Grade.Grade3, 'Biểu thức số', 'Thứ tự thực hiện, tìm thành phần', 'number', 'Brackets', 3),
    M('g3_fractions', Grade.Grade3, 'Một phần mấy', 'Nhận biết, tìm một phần mấy của một số', 'number', 'PieChart', 4),
    M('g3_numbers', Grade.Grade3, 'Các số đến 100 000', 'Đọc, viết, so sánh, làm tròn, số La Mã', 'number', 'Hash', 5),
    M('g3_arithmetic', Grade.Grade3, 'Cộng, trừ, nhân, chia số lớn', 'Phạm vi 100 000', 'number', 'Calculator', 6),
    M('g3_word_problems', Grade.Grade3, 'Bài toán hai bước', 'Gấp, giảm, mua bán', 'number', 'BookOpen', 7),
    M('g3_geometry', Grade.Grade3, 'Hình học', 'Trung điểm, hình tròn, góc vuông, khối', 'geometry', 'Shapes', 8),
    M('g3_area', Grade.Grade3, 'Chu vi & diện tích', 'Hình chữ nhật, hình vuông, cm²', 'geometry', 'Ruler', 9),
    M('g3_measurements', Grade.Grade3, 'Đo lường', 'mm, g, ml, nhiệt độ', 'measurement', 'Scale', 10),
    M('g3_time', Grade.Grade3, 'Thời gian', 'Đồng hồ đến phút, tháng – năm', 'measurement', 'Clock', 11),
    M('g3_money', Grade.Grade3, 'Tiền Việt Nam', 'Đến 100 000 đồng, tiền trả lại', 'measurement', 'Coins', 12),
    M('g3_statistics', Grade.Grade3, 'Bảng số liệu', 'Đọc, so sánh số liệu', 'statistics', 'BarChart3', 13),
    M('g3_probability', Grade.Grade3, 'Khả năng xảy ra', 'Chắc chắn, có thể, không thể', 'probability', 'Dices', 14),

    M('g4_large_numbers', Grade.Grade4, 'Số có nhiều chữ số', 'Đọc, viết, hàng – lớp, làm tròn, chẵn – lẻ', 'number', 'Hash', 1),
    M('g4_add_sub', Grade.Grade4, 'Phép cộng, phép trừ', 'Tính chất, biểu thức chứa chữ', 'number', 'Plus', 2),
    M('g4_multiplication', Grade.Grade4, 'Phép nhân', 'Nhân với số có hai chữ số, tính chất', 'number', 'X', 3),
    M('g4_division', Grade.Grade4, 'Phép chia', 'Chia cho số có hai chữ số', 'number', 'Divide', 4),
    M('g4_parentheses', Grade.Grade4, 'Biểu thức có ngoặc', 'Tính giá trị biểu thức', 'number', 'Brackets', 5),
    M('g4_patterns', Grade.Grade4, 'Dãy số theo quy luật', 'Tìm quy luật, điền số', 'number', 'ListOrdered', 6),
    M('g4_average', Grade.Grade4, 'Số trung bình cộng', 'Tìm trung bình cộng', 'number', 'Sigma', 7),
    M('g4_word_problems', Grade.Grade4, 'Giải toán', 'Tổng – hiệu, rút về đơn vị', 'number', 'BookOpen', 8),
    M('g4_fractions', Grade.Grade4, 'Phân số', 'Khái niệm, rút gọn, quy đồng, so sánh', 'number', 'PieChart', 9),
    M('g4_fraction_ops', Grade.Grade4, 'Phép tính với phân số', 'Cộng, trừ, nhân, chia phân số', 'number', 'PieChart', 10),
    M('g4_angles', Grade.Grade4, 'Góc', 'Góc nhọn, vuông, tù, bẹt; đo góc', 'geometry', 'Triangle', 11),
    M('g4_lines', Grade.Grade4, 'Vuông góc & song song', 'Hai đường thẳng vuông góc, song song', 'geometry', 'Compass', 12),
    M('g4_geometry_2d', Grade.Grade4, 'Hình bình hành, hình thoi & diện tích', 'Nhận biết hình, chu vi, diện tích', 'geometry', 'Shapes', 13),
    M('g4_units', Grade.Grade4, 'Đơn vị đo', 'Yến, tạ, tấn; m², dm², mm²; giây, thế kỉ', 'measurement', 'Scale', 14),
    M('g4_statistics', Grade.Grade4, 'Thống kê & xác suất', 'Dãy số liệu, biểu đồ cột, số lần xuất hiện', 'statistics', 'BarChart3', 15),
    M('g4_divisibility', Grade.Grade4, 'Dấu hiệu chia hết', 'Chia hết cho 2, 3, 5, 9', 'number', 'Sparkles', 90, true),
    M('g4_para_rhombus', Grade.Grade4, 'Diện tích hình bình hành, hình thoi', 'Nâng cao', 'geometry', 'Sparkles', 91, true),

    M('g5_fractions', Grade.Grade5, 'Phân số', 'Phân số thập phân, hỗn số, phép tính', 'number', 'PieChart', 1),
    M('g5_numbers', Grade.Grade5, 'Số thập phân', 'Đọc, viết, so sánh, làm tròn', 'number', 'Hash', 2),
    M('g5_decimal_ops', Grade.Grade5, 'Phép tính với số thập phân', 'Cộng, trừ, nhân, chia', 'number', 'Calculator', 3),
    M('g5_parentheses', Grade.Grade5, 'Biểu thức', 'Biểu thức có dấu ngoặc', 'number', 'Brackets', 4),
    M('g5_ratios', Grade.Grade5, 'Tỉ số & phần trăm', 'Tỉ số, phần trăm, tỉ lệ bản đồ', 'number', 'Percent', 5),
    M('g5_word_problems', Grade.Grade5, 'Chuyển động đều', 'Vận tốc, quãng đường, thời gian', 'number', 'BookOpen', 6),
    M('g5_geometry', Grade.Grade5, 'Hình học', 'Tam giác, hình thang, hình tròn, hình khối', 'geometry', 'Box', 7),
    M('g5_measurements', Grade.Grade5, 'Đơn vị đo diện tích, thể tích', 'ha, km², cm³, dm³, m³', 'measurement', 'Scale', 8),
    M('g5_time_ops', Grade.Grade5, 'Số đo thời gian', 'Cộng, trừ, nhân, chia', 'measurement', 'Clock', 9),
    M('g5_statistics', Grade.Grade5, 'Thống kê & xác suất', 'Biểu đồ quạt tròn, biểu đồ cột, tỉ số khả năng', 'statistics', 'BarChart3', 10),
];

export const skillById = (id: string): SkillDef | undefined => SKILL_MAP.get(id);
export const SKILL_MAP = new Map(SKILLS.map(s => [s.id, s]));
export const skillsOfTopic = (topicId: string): SkillDef[] => SKILLS.filter(s => s.topicId === topicId);
export const topicMeta = (topicId: string): TopicMeta | undefined => TOPIC_META.find(t => t.id === topicId);
export const STRAND_LABEL: Record<Strand, string> = {
    number: 'Số và phép tính', geometry: 'Hình học', measurement: 'Đo lường',
    statistics: 'Thống kê', probability: 'Xác suất', explore: 'Khám phá',
};
