import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStudent, useStudentActions } from '../contexts/StudentContext';
import { Grade } from '../../types';
import { ContentSpec, FAULTS, LESSONS, MISSIONS, SOURCES } from '../data/electricity/content';
import { CHALLENGES } from '../data/electricityData';
import { LEGACY_CONTENT } from '../components/electricity/legacy/adapter';
import { CircuitThumbnail } from '../components/electricity/ui/CircuitThumbnail';
import { Workshop } from '../components/electricity/ui/Workshop';
import { Conductors, FruitLab, GeneratorLab, House, MagnetLab, PowerJourney, SafetyRoom, StaticLab } from '../components/electricity/ui/Activities';
import { Compare } from '../components/electricity/ui/Compare';
import { archiveLegacy, LegacyArchive } from '../components/electricity/progress/progress';
import { CircuitDocument, deleteDocument, listDocuments, parseDocument, saveDocument } from '../components/electricity/progress/notebook';
import { PartGlyph } from '../components/electricity/flat/FlatBench';
import { newPart } from '../components/electricity/engine/circuit';
import '../components/electricity/ui/electricity.css';
type Screen = 'home' | 'lessons' | 'missions' | 'faults' | 'labs' | 'notebook' | 'legacy' | 'sources' | 'house' | 'safety' | 'journey' | 'compare';
const BADGES: Record<string, string> = { firstLight: 'Ánh sáng đầu tiên', sorter: 'Nhà phân loại', designer: 'Người đọc sơ đồ', detective: 'Thám tử tài ba', inventor: 'Nhà sáng chế', energyKeeper: 'Người giữ năng lượng', explorer: 'Nhà khám phá' };
function ElectricityExperience() {
    const navigate = useNavigate(), { currentStudent, students } = useStudent(), { claimElectricityLegacy } = useStudentActions(), owner = currentStudent?.id ?? 'guest';
    const [screen, setScreen] = useState<Screen>('home'), [work, setWork] = useState<{
        spec?: ContentSpec;
        document?: CircuitDocument;
        practice?: boolean;
        key: number;
    } | null>(null), [lab, setLab] = useState('materials'), [documents, setDocuments] = useState<CircuitDocument[]>([]), [archive, setArchive] = useState<LegacyArchive | null>(null), [message, setMessage] = useState('');
    const progress = currentStudent?.electricity, completed = LESSONS.filter(l => progress?.completions[`lesson:${l.id}`]).length;
    useEffect(() => { try {
        setArchive(archiveLegacy(localStorage));
    }
    catch {
        setMessage('Thành tích cũ vẫn được giữ; hiện chưa đọc hoặc lưu được kho lịch sử.');
    } }, []);
    useEffect(() => { if (screen === 'notebook')
        void listDocuments(owner).then(setDocuments).catch(() => setMessage('Sổ chưa mở được. Mạch đang làm vẫn có thể tải dưới dạng JSON.')); }, [screen, owner]);
    useEffect(() => { const previous = document.title; document.title = 'Xưởng Ánh Sáng · Điện & Mạch Điện'; return () => { document.title = previous; }; }, []);
    if (currentStudent?.grade === Grade.Preschool)
        return <main className="electricity-world"><section className="ew-preschool"><h1>Xưởng Ánh Sáng dành cho lớp 1–5</h1><p>Chọn một hoạt động phù hợp trong sảnh khám phá nhé.</p><button onClick={() => navigate('/science')}>Về sảnh khoa học</button></section></main>;
    const start = (spec?: ContentSpec, document?: CircuitDocument, practice = false) => setWork({ spec, document, practice, key: Date.now() });
    if (work)
        return <main className="electricity-world"><Workshop key={work.key} owner={owner} grade={currentStudent?.grade ?? 3} spec={work.spec} initialDocument={work.document} practice={work.practice} onBack={() => setWork(null)}/></main>;
    const rows = screen === 'lessons' ? LESSONS : screen === 'missions' ? MISSIONS : FAULTS;
    const importFile = async (file: File) => { try {
        const doc = parseDocument(await file.text());
        const next = { ...doc, id: crypto.randomUUID(), ownerId: owner, revision: 1 };
        await saveDocument(next);
        setDocuments(await listDocuments(owner));
        setMessage('Đã nhập mạch vào sổ của hồ sơ này.');
    }
    catch (e) {
        setMessage((e as Error).message);
    } };
    const claim = async () => { if (!archive || owner === 'guest')
        return; const result = await claimElectricityLegacy(owner, archive); setMessage(result.ok ? 'Đã nhận thông tin lịch sử. Sao đang có được giữ nguyên.' : result.pending ? 'Chưa lưu được. Thử lại sau nhé.' : 'Kho lịch sử này đã được nhận hoặc hồ sơ đã thay đổi.'); };
    const claimed = archive?.claimedOwner || students.find(p => p.electricity?.legacy?.snapshotId === archive?.snapshotId)?.id;
    return <main className="electricity-world"><div className="ew-shell"><header className="ew-shell-header"><button className="ew-back" onClick={() => screen === 'home' ? navigate('/science') : setScreen('home')}>← {screen === 'home' ? 'Sảnh khoa học' : 'Về xưởng'}</button><button className="ew-wordmark" onClick={() => setScreen('home')}><span className="ew-brand-mark">✳</span> Xưởng Ánh Sáng</button><button className="ew-profile-chip" onClick={() => setScreen('notebook')}>{currentStudent?.name ?? 'Khách khám phá'} <span>· {completed}/13 bài</span></button></header>
 {screen === 'home' ? <>
  <section className="ew-hero"><div className="ew-hero-copy"><span className="ew-eyebrow">Điện & mạch điện / Xưởng 01</span><h1>Một sợi dây.<br />Một điều <em>kỳ diệu.</em></h1><p>Tự tay thắp sáng, nhìn dòng điện chuyển động và tìm hiểu điều xảy ra bên trong.</p><div className="ew-hero-actions"><button className="ew-primary" onClick={() => start(LESSONS[2])}>{progress?.introDone ? 'Thắp đèn lần nữa' : 'Thắp bóng đầu tiên'} <span>↗</span></button><button className="ew-text-link" onClick={() => start()}>Vào bàn tự do →</button></div><div className="ew-hero-caption"><span>01 — NỐI MẠCH</span><i /><span>02 — QUAN SÁT</span><i /><span>03 — KHÁM PHÁ</span></div></div><div className="ew-hero-art"><svg viewBox="0 0 780 610" role="img" aria-label="Bàn đồ chơi màu kem với pin, bóng đèn sáng và dây đồng"><defs><radialGradient id="hero-lamp"><stop stopColor="#ffe1a0" stopOpacity=".8"/><stop offset="1" stopColor="#f0cf87" stopOpacity="0"/></radialGradient><pattern id="hero-holes" width="28" height="28" patternUnits="userSpaceOnUse"><circle cx="14" cy="14" r="1.5" fill="#b3a384" opacity=".45"/></pattern><filter id="hero-glow"><feGaussianBlur stdDeviation="12"/></filter></defs><g transform="translate(15 35) rotate(-7 380 270)"><rect x="20" y="45" width="715" height="510" rx="40" fill="#cbb895"/><rect x="20" y="25" width="715" height="510" rx="40" fill="#eee2c7"/><rect x="40" y="45" width="675" height="465" rx="25" fill="url(#hero-holes)"/><circle cx="540" cy="210" r="205" fill="url(#hero-lamp)"/><path d="M140 330V110H450V210" stroke="#b36350" strokeWidth="16" fill="none" strokeLinejoin="round"/><path d="M610 210H667V442H140V365" stroke="#417b73" strokeWidth="16" fill="none" strokeLinejoin="round"/><g transform="translate(160 350)"><PartGlyph part={newPart('battery', 'B', 0, 0)}/></g><g transform="translate(530 210) scale(1.2)"><PartGlyph part={newPart('bulb', 'L', 0, 0)} brightness={.8} scope="hero"/></g><text x="365" y="495" textAnchor="middle" fill="#7f745b" fontSize="14" letterSpacing="3">TÒ MÒ LÀ ĐIỂM KHỞI ĐẦU</text></g></svg><span className="ew-art-note">Cắm vào trí tò mò của mình.</span></div></section>
  <section className="ew-destinations"><button className="ew-destination ew-journey-card" onClick={() => setScreen('lessons')}><span className="ew-destination-number">01 / HÀNH TRÌNH</span><h2>Từ tia sáng đầu tiên<br />đến cả một ngôi nhà.</h2><p>13 khám phá có hướng dẫn</p><span className="ew-destination-arrow">↗</span><div className="ew-progress-track"><i style={{ width: `${completed / 13 * 100}%` }}/></div></button><div className="ew-destination-stack"><button className="ew-destination" onClick={() => setScreen('labs')}><span className="ew-destination-number">02 / PHÒNG THÍ NGHIỆM</span><h2>Thử một điều bất ngờ.</h2><p>Vật dẫn · trái cây · nam châm · tĩnh điện · máy phát</p><span className="ew-destination-arrow">↗</span></button><button className="ew-destination" onClick={() => setScreen('missions')}><span className="ew-destination-number">03 / SÁNG CHẾ</span><h2>Làm đồ có ích.</h2><p>12 nhiệm vụ · nhiều cách giải</p><span className="ew-destination-arrow">↗</span></button></div></section>
  <nav className="ew-explore-links"><button onClick={() => setScreen('faults')}><span>⌕</span><b>Thám tử mạch điện</b><small>12 vụ việc cần chứng cứ</small></button><button onClick={() => setScreen('house')}><span>⌂</span><b>Ngôi nhà của mình</b><small>Giữ ánh sáng, tiết kiệm điện</small></button><button onClick={() => setScreen('compare')}><span>⑂</span><b>Hai cách nối</b><small>Đặt nối tiếp và song song cạnh nhau</small></button><button onClick={() => setScreen('notebook')}><span>▤</span><b>Sổ sáng chế</b><small>Lưu lại điều vừa khám phá</small></button></nav>
  <div className="ew-badge-shelf">{Object.entries(BADGES).map(([id, name]) => <span key={id} className={progress?.badges.includes(id) ? 'earned' : ''}>{progress?.badges.includes(id) ? '✦' : '◇'} {name}</span>)}</div>
 </> : ['lessons', 'missions', 'faults'].includes(screen) ? <section className="ew-catalog"><span className="ew-eyebrow">{screen === 'lessons' ? '13 khám phá · tự chọn nhịp của mình' : screen === 'missions' ? '12 sáng chế · kiểm từng trạng thái' : '12 vụ việc · quan sát, suy luận, sửa chữa'}</span><h1>{screen === 'lessons' ? 'Hành trình ánh sáng' : screen === 'missions' ? 'Làm điều mình nghĩ ra' : 'Có chuyện gì với mạch này?'}</h1><div className="ew-content-list">{rows.map((s, i) => { const best = progress?.completions[`${s.kind}:${s.id}`]?.best; return <button key={s.id} onClick={() => start(s)}><span className="ew-content-index">{String(i + 1).padStart(2, '0')}</span><span><h2>{s.title}</h2><p>{s.intro}</p></span><span className="ew-content-tail">{best ? '★'.repeat(best) : '↗'}</span></button>; })}</div></section> : screen === 'labs' ? <section><div className="ew-page-intro"><span className="ew-eyebrow">Năm bàn thí nghiệm</span><h1>Cứ thử. Rồi nhìn thật kỹ.</h1></div><nav className="ew-lab-tabs">{[['materials', 'Vật dẫn điện'], ['fruit', 'Pin trái cây'], ['magnet', 'Nam châm điện'], ['static', 'Tĩnh điện'], ['generator', 'Máy phát']].map(([id, name]) => <button key={id} aria-pressed={lab === id} onClick={() => setLab(id)}>{name}</button>)}</nav><div key={lab}>{lab === 'materials' ? <Conductors onEvidence={() => { }}/> : lab === 'fruit' ? <FruitLab /> : lab === 'magnet' ? <MagnetLab /> : lab === 'static' ? <StaticLab /> : <GeneratorLab />}</div><p className="ew-lab-footer">Muốn ghi nhận bài học? <button onClick={() => start(LESSONS[6])}>Làm bài Vật nào dẫn điện →</button></p></section> : screen === 'house' ? <><nav className="ew-lab-tabs"><button onClick={() => setScreen('safety')}>Tìm mối nguy</button><button onClick={() => setScreen('journey')}>Điện từ đâu đến?</button><button onClick={() => start(LESSONS[11])}>Nhận nhiệm vụ tiết kiệm</button></nav><House onEvidence={() => { }}/></> : screen === 'safety' ? <SafetyRoom all onEvidence={() => { }}/> : screen === 'journey' ? <PowerJourney onEvidence={() => { }}/> : screen === 'compare' ? <Compare onClose={() => setScreen('home')}/> : screen === 'notebook' ? <section className="ew-notebook"><div className="ew-page-intro"><span className="ew-eyebrow">Sổ của {currentStudent?.name ?? 'khách'}</span><h1>Những ý tưởng đã thành hình.</h1><p>{documents.length}/12 sáng chế · Mạch giữ nguyên pin đã dùng và linh kiện đang hỏng.</p><label className="ew-file-label">Nhập mạch JSON<input type="file" accept=".json,application/json" onChange={e => { const file = e.target.files?.[0]; if (file)
            void importFile(file); e.target.value = ''; }}/></label></div>{documents.length ? <div className="ew-notebook-grid">{documents.map(doc => <article key={doc.id}><button className="ew-notebook-preview" onClick={() => start(undefined, doc)}><CircuitThumbnail circuit={doc.circuit} title={doc.title}/><h2>{doc.title}</h2></button><p>{new Date(doc.updatedAt).toLocaleDateString('vi-VN')} · {doc.circuit.parts.length} linh kiện</p><button onClick={async () => { await deleteDocument(doc.id, owner); setDocuments(await listDocuments(owner)); }}>Xóa bản lưu</button></article>)}</div> : <div className="ew-empty"><span>▤</span><h2>Trang đầu đang chờ một sáng chế.</h2><p>Lắp mạch, đặt tên rồi lưu lại từ bàn tự do.</p><button className="ew-primary" onClick={() => start()}>Mở bàn tự do →</button></div>}</section> : screen === 'legacy' ? <section className="ew-catalog"><span className="ew-eyebrow">Kho trên máy · giữ nguyên thành tích</span><h1>Những khám phá trước đây.</h1><p>Đã làm {archive?.lessonIds.length ?? 0}/8 bài và {archive?.challengeIds.length ?? 0}/15 thử thách bản cũ. Luyện thêm không phát sao mới.</p>{archive && <><p>Thành tích cũ dùng chung trên máy. Đưa vào hồ sơ chỉ nhận thông tin lịch sử; sao đang có được giữ nguyên.</p><button disabled={owner === 'guest' || !!claimed} onClick={() => void claim()}>{claimed ? 'Kho lịch sử đã được nhận' : `Đưa vào hồ sơ ${currentStudent?.name ?? 'đang chọn'}`}</button></>}<h2>8 bài cũ · tiếp tục bằng trải nghiệm mới</h2><div className="ew-legacy-grid">{['Dòng điện', 'Mạch kín và hở', 'Nguồn điện', 'Công tắc', 'Lắp mạch', 'Nối tiếp', 'Song song', 'So sánh'].map((label, i) => <button key={label} onClick={() => start(LESSONS[[2, 3, 5, 4, 2, 9, 10, 10][i]], undefined, true)}>{archive?.lessonIds.includes(i + 1) ? '✓ ' : ''}{i + 1}. {label}</button>)}</div><h2>15 đề luyện thêm</h2><div className="ew-legacy-grid">{CHALLENGES.map(c => { return <button key={c.id} onClick={() => start(LEGACY_CONTENT.find(s => s.id === `legacy-${c.id}`), undefined, true)}>{archive?.challengeIds.includes(c.id) ? '✓ ' : ''}{c.title}</button>; })}</div></section> : <section className="ew-sources"><span className="ew-eyebrow">Dành cho phụ huynh</span><h1>Điều mô hình nói và không nói.</h1><p>Bàn sử dụng mô hình DC giáo dục theo Ohm và Kirchhoff. Thông số pin, bóng, LED, nội trở và các ngưỡng hỏng là mẫu hiệu chuẩn; không phải dự báo chính xác cho mọi linh kiện thật.</p><p>Chuyển động electron, lực hút kẹp, tĩnh điện và tay quay được minh họa. Ngôi nhà dùng công suất và lịch giả định, không phải hóa đơn điện thực tế. Hoạt động về điện nhà chỉ dạy tránh chạm và báo người lớn.</p><ul>{SOURCES.map(s => <li key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a></li>)}</ul><p>Kiến thức lõi theo Khoa học 5; đo điện, tĩnh điện, nối tiếp/song song và cảm ứng là phần khám phá thêm THCS.</p></section>}
 {message && <p role="status" className="ew-status">{message}</p>}<footer className="ew-shell-footer"><span>Học bằng cách tự tay thử.</span><div><button onClick={() => setScreen('legacy')}>Thành tích cũ trên máy</button><button onClick={() => setScreen('sources')}>Mô hình & nguồn kiến thức</button></div></footer></div></main>;
}
export function ElectricityPage() { const { currentStudent } = useStudent(); return <ElectricityExperience key={currentStudent?.id ?? 'guest'}/>; }
