import React, { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronRight, Flag, Gauge, HelpCircle, Home, LockKeyhole, Pause, Play, RotateCcw, Settings2, Sparkles, Star, Trophy, Volume2, VolumeX, X, Zap } from 'lucide-react';
import type { StudentProfile } from '../../../types';
import { activeQuestion, answerNow, chooseLane, createSession, finishDistance, rankOf, readSeconds, recordOf, useNitro } from './engine';
import { RaceMotion } from './motion';
import { RIVAL_SKILLS } from './rivals';
import { clearDraft, progressOf, readConfig, readDisplay, readDraft, saveConfig, saveDraft } from './progress';
import { APPROACH, Config, Difficulty, GATE, KARTS, LEVELS, MISSIONS, PACES, REGIONS, SEGMENT, Session, normalizeConfig, raceQuestionCount } from './model';
import { questionsFor, syllabus } from './questions';
import { useRacingSound } from './useRacingSound';
import { musicManager } from '../../../services/musicManager';
import { MusicTrack } from '../../../services/musicConfig';
import { cancelSpeech, speak } from '../../../src/utils/speech';
import World2D from './World2D';
import './racing.css';
const World3D = lazy(() => import('./World3D'));
type Award = { ok: boolean; earned: number; bonusStars?: number; achievementNames?: string[] };
interface Props { student: StudentProfile; difficulty?: Difficulty; complete: (id: string, s: Session) => Award; onBack: () => void; onLegacy?: () => void; soundEnabled: boolean; toggleSound: () => void; preview?: boolean; initialSession?: Session; onMetrics?: (text: string) => void }
const timeLabel = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
class RenderBoundary extends React.Component<{ children: React.ReactNode; fallback: React.ReactNode; onError: () => void }, { failed: boolean }> {
    state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; }
    componentDidCatch() { this.props.onError(); }
    render() { return this.state.failed ? this.props.fallback : this.props.children; }
}
function Dialog({ title, children, close }: { title: string; children: React.ReactNode; close?: () => void }) {
    const ref = useRef<HTMLDivElement>(null);
    useEffect(() => {
        const prior = document.activeElement as HTMLElement | null, el = ref.current!;
        el.querySelector<HTMLButtonElement>('button')?.focus();
        const key = (e: KeyboardEvent) => { if (e.key === 'Escape' && close) { e.preventDefault(); e.stopPropagation(); close(); }
            if (e.key === 'Tab') { const nodes = [...el.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, [tabindex="0"]')].filter(n => n.offsetParent !== null); const first = nodes[0], last = nodes[nodes.length - 1]; if (!nodes.length) { e.preventDefault(); return; } if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
        }; el.addEventListener('keydown', key); return () => { el.removeEventListener('keydown', key); prior?.focus({ preventScroll: true }); };
    }, [close]);
    return <div className="rc-overlay"><section className="rc-dialog" role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="rc-dialog-head"><h2>{title}</h2>{close && <button className="rc-icon" aria-label="Đóng" onClick={close}><X size={21}/></button>}</div>{children}</section></div>;
}
export function RacingCup({ student, difficulty, complete, onBack, onLegacy, soundEnabled, toggleSound, preview, initialSession, onMetrics }: Props) {
    const [config, setConfig] = useState(() => preview ? normalizeConfig({ difficulty }, student.grade) : readConfig(student.id, student.grade, difficulty));
    const sample = useMemo(() => questionsFor(config, 3759, 1)[0], [config.grade, config.difficulty]);
    const [draft, setDraft] = useState(() => preview ? { session: null as Session | null, corrupt: false } : readDraft(student.id));
    const live = useRef<Session | null>(initialSession ? structuredClone(initialSession) : null), [view, setView] = useState<Session | null>(live.current);
    const motion = useRef(new RaceMotion()), uiAt = useRef(0);
    const [display] = useState(() => preview ? { flat: false, low: false, reduced: null } : readDisplay(student.id));
    const [award, setAward] = useState<Award | null>(null), [help, setHelp] = useState(false), [flat, setFlat] = useState(display.flat), [low, setLow] = useState(display.low);
    const [reduced, setReduced] = useState(() => display.reduced ?? (typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches));
    const [metrics, setMetrics] = useState('');
    const listeningRef = useRef(false), speechTimer = useRef<ReturnType<typeof setTimeout> | null>(null), [listening, setListening] = useState(false);
    const stopListening = useCallback(() => { listeningRef.current = false; setListening(false); if (speechTimer.current) clearTimeout(speechTimer.current); cancelSpeech(); }, []);
    const [saveWarning, setSaveWarning] = useState(false), [renderWarning, setRenderWarning] = useState(false);
    const attempt = useRef(''), completedId = useRef(''), completeRef = useRef(complete), lastSaved = useRef(0); completeRef.current = complete;
    const progress = progressOf(student), finished = Object.keys(progress.missions).length, stars = Object.values(progress.missions).reduce((a, b) => a + b, 0);
    const cfg = view?.config || config, region = REGIONS.find(r => r.id === cfg.region)!, mission = MISSIONS[cfg.mission];
    const sync = useCallback(() => { const s = live.current; setView(s ? { ...s, racers: s.racers.map(r => ({ ...r })), answers: [...s.answers] } : null); }, []);
    const persistDraft = useCallback(() => { if (live.current && live.current.id !== completedId.current && !preview) setSaveWarning(!saveDraft(live.current)); }, [preview]);
    const pause = useCallback(() => { if (live.current?.phase === 'racing') { stopListening(); live.current.paused = true; persistDraft(); sync(); } }, [persistDraft, sync, stopListening]);
    const resume = useCallback(() => { if (live.current) { live.current.paused = false; sync(); } }, [sync]);
    const rendererFailed = useCallback(() => { setFlat(true); setRenderWarning(true); pause(); }, [pause]);
    useRacingSound(view, soundEnabled && !listening);
    useEffect(() => () => { if (speechTimer.current) clearTimeout(speechTimer.current); cancelSpeech(); }, []);
    useEffect(() => { if (preview) return; musicManager.playTrack(MusicTrack.SPEED_MATH); return () => { musicManager.setPaused(false); musicManager.resumeRouteMusic(); }; }, [preview]);
    useEffect(() => { if (!preview) musicManager.setPaused(!!view && (view.paused || view.phase !== 'racing' || listening)); }, [preview, view?.paused, view?.phase, listening]);
    useEffect(() => { if (!preview) saveConfig(student.id, config); }, [config, student.id, preview]);
    useEffect(() => { if (!preview) try { localStorage.setItem(`racing-display-v2:${student.id}`, JSON.stringify({ flat, low, reduced })); } catch {} }, [student.id, preview, flat, low, reduced]);
    const onFrame = useCallback((now: number) => {
        const s = live.current, before = s?.fx, running = s?.phase === 'racing' && !s.paused && !listeningRef.current;
        const frame = motion.current.advance(s, now, listeningRef.current);
        if (s && running) {
            if (motion.current.stalled || s.fx !== before || now - lastSaved.current > 4000) { persistDraft(); lastSaved.current = now; }
            if (motion.current.stalled || now - uiAt.current > 90 || s.fx !== before || s.phase === 'finished') { sync(); uiAt.current = now; }
        }
        return frame;
    }, [persistDraft, sync]);
    useEffect(() => {
        const hidden = () => { if (document.hidden) pause(); }; window.addEventListener('blur', pause); document.addEventListener('visibilitychange', hidden); window.addEventListener('pagehide', persistDraft);
        return () => { window.removeEventListener('blur', pause); document.removeEventListener('visibilitychange', hidden); window.removeEventListener('pagehide', persistDraft); persistDraft(); };
    }, [pause, persistDraft]);
    const saveResult = useCallback(() => {
        const s = live.current; if (!s || s.phase !== 'finished') return;
        let result: Award; try { result = completeRef.current(student.id, structuredClone(s)); } catch { result = { ok: false, earned: 0 }; }
        setAward(result); if (result.ok) { completedId.current = s.id; if (!preview) clearDraft(student.id); setDraft({ session: null, corrupt: false }); setSaveWarning(false); }
    }, [student.id, preview]);
    useEffect(() => { if (view?.phase === 'finished' && attempt.current !== view.id) { attempt.current = view.id; saveResult(); } }, [view?.phase, view?.id, saveResult]);
    const move = useCallback((direction: number) => { const s = live.current; if (s) { chooseLane(s, Math.max(0, Math.min(2, s.racers[0].target + direction))); sync(); } }, [sync]);
    const select = useCallback((lane: number, id: number) => { if (live.current) { stopListening(); chooseLane(live.current, lane, id); persistDraft(); sync(); } }, [persistDraft, sync, stopListening]);
    const submit = useCallback((id: number) => { const s = live.current; if (s) { stopListening(); answerNow(s, id); persistDraft(); sync(); } }, [persistDraft, sync, stopListening]);
    const nitro = useCallback(() => { if (live.current) { useNitro(live.current); sync(); } }, [sync]);
    useEffect(() => {
        const key = (e: KeyboardEvent) => {
            const s = live.current; if (!s || s.phase !== 'racing' || s.paused || help) return;
            if ((e.target as HTMLElement).closest('input,select,textarea')) return;
            if (e.key === 'Enter' && (e.target as HTMLElement).closest('button,summary')) return;
            if (['ArrowLeft', 'ArrowRight', 'a', 'A', 'd', 'D', '1', '2', '3', ' ', 'Escape', 'Enter'].includes(e.key)) e.preventDefault();
            if (e.repeat) return;
            if (['ArrowLeft', 'a', 'A'].includes(e.key)) move(-1); else if (['ArrowRight', 'd', 'D'].includes(e.key)) move(1);
            else if (['1', '2', '3'].includes(e.key) && activeQuestion(s) >= 0) select(Number(e.key) - 1, activeQuestion(s));
            else if (e.key === 'Enter') submit(activeQuestion(s));
            else if (e.key === ' ') nitro(); else if (e.key === 'Escape') pause();
        }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
    }, [move, select, submit, nitro, pause, help]);
    const change = (patch: Partial<Config>) => setConfig(c => normalizeConfig({ ...c, ...patch }, student.grade));
    const start = (next = config, seed = Math.floor(Math.random() * 2147483647), questionVersion: 1 | 2 = 2) => {
        let c = normalizeConfig(next, student.grade); if (c.mode === 'campaign' && c.mission && !progress.missions[c.mission - 1]) c = { ...c, mission: Math.min(finished, 11), region: MISSIONS[Math.min(finished, 11)].region };
        if (KARTS[c.kart].unlock > finished) c.kart = 0;
        setConfig(c); live.current = createSession(c, seed, crypto.randomUUID(), student.id, questionVersion); setAward(null); attempt.current = ''; lastSaved.current = 0; setHelp(false); persistDraft(); sync();
    };
    const toGarage = () => { stopListening(); const s = live.current; if (s) { if (s.phase === 'racing') s.paused = true; if (s.phase !== 'finished' || !award?.ok) { persistDraft(); setDraft({ session: structuredClone(s), corrupt: false }); } setConfig(s.config); } live.current = null; sync(); };
    const restore = () => { if (draft.session) { live.current = structuredClone(draft.session); attempt.current = ''; setAward(null); sync(); } };
    const qi = view ? activeQuestion(view) : -1, question = qi >= 0 ? view!.questions[qi] : null, me = view?.racers[0];
    const result = view?.phase === 'finished' ? recordOf(view) : null;
    const remaining = view?.answerRush ? Math.max(0, view.answerRush.duration - (view.elapsed - view.answerRush.startedAt)) : view && qi >= 0 ? Math.max(0, (qi * SEGMENT + GATE - view.racers[0].distance) / ((GATE - APPROACH) / readSeconds(view, qi))) : 0;
    const listen = () => { if (listeningRef.current) { stopListening(); return; } const s = live.current, i = s ? activeQuestion(s) : -1; if (!s || i < 0 || s.answerRush) return;
        listeningRef.current = true; setListening(true);
        const text = s.questions[i].text.replaceAll('+', ' cộng ').replaceAll('−', ' trừ ').replaceAll('-', ' trừ ').replaceAll(':', ' chia ').replaceAll('/', ' phần ').replaceAll('%', ' phần trăm ').replaceAll('×', ' nhân ').replaceAll('÷', ' chia ').replaceAll('=', ' bằng ').replaceAll('?', ' bao nhiêu ');
        const done = () => { listeningRef.current = false; setListening(false); if (speechTimer.current) clearTimeout(speechTimer.current); };
        if (!speak(text, { lang: 'vi-VN', onEnd: done, onError: done })) done();
        speechTimer.current = setTimeout(stopListening, 12000);
    };
    const sceneProps = { live, onFrame, region: cfg.region, kart: cfg.kart, reduced, garage: !view, onMetrics: preview ? setMetrics : onMetrics };
    const scene = flat ? <World2D {...sceneProps}/> : <RenderBoundary onError={rendererFailed} fallback={<World2D {...sceneProps}/>}><Suspense fallback={<div className="rc-scene-loading"><Sparkles/><span>Đang chuẩn bị đường đua…</span></div>}><World3D {...sceneProps} low={low} onUnavailable={rendererFailed}/></Suspense></RenderBoundary>;
    const touch = useRef<{ x: number; y: number } | null>(null);
    return <div className={`racing-cup rc-${cfg.region} ${view ? 'rc-in-race' : 'rc-in-garage'} ${reduced ? 'rc-reduced' : ''}`}>
        {import.meta.env.DEV && preview && <output className="rc-dev-metrics" data-testid="racing-metrics">{flat ? 'Canvas 2D' : metrics}</output>}
        {!view ? <>
            <header className="rc-topbar"><button className="rc-back" onClick={onBack}><ArrowLeft size={18}/><span>Trò chơi</span></button><div className="rc-brand"><Flag size={19}/><span>ĐƯỜNG ĐUA THẦN TỐC</span></div><div className="rc-top-actions"><span className="rc-star-count"><Star size={16} fill="currentColor"/>{stars}<small>/ 36</small></span><button className="rc-icon" aria-label={soundEnabled ? 'Tắt hiệu ứng âm thanh' : 'Bật hiệu ứng âm thanh'} onClick={toggleSound}>{soundEnabled ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button><button className="rc-icon" aria-label="Hướng dẫn chơi" onClick={() => setHelp(true)}><HelpCircle size={19}/></button></div></header>
            <main className="rc-garage">
                <section className="rc-showroom"><div className="rc-hero-copy"><span className="rc-eyebrow">TÍNH THẬT CHẮC · LÁI THẬT VUI</span><h1>Cúp Sao Băng<span>Mỗi đáp án, một lần bứt phá.</span></h1></div><div className="rc-kart-stage">{scene}</div><div className="rc-kart-label"><span className="rc-small-label">KART CỦA EM</span><h2>{KARTS[config.kart].name}</h2><span>Một người bạn. Cả một hành trình.</span></div><div className="rc-kart-picker" aria-label="Chọn ngoại hình xe">{KARTS.map((k, i) => <button key={k.name} aria-label={k.name + (finished < k.unlock ? ` · Mở sau ${k.unlock} chặng` : '')} aria-pressed={config.kart === i} disabled={finished < k.unlock} style={{ '--kart-color': k.color } as React.CSSProperties} onClick={() => change({ kart: i })}>{finished < k.unlock ? <LockKeyhole size={15}/> : config.kart === i ? <Check size={17}/> : null}</button>)}</div><div className="rc-showroom-note"><Sparkles size={15}/>Đúng phép tính · Đầy nitro · Vượt lên nào!</div></section>
                <section className="rc-setup"><div className="rc-setup-title"><span className="rc-eyebrow">SẴN SÀNG XUẤT PHÁT</span><span className="rc-grade">Lớp {student.grade}</span></div>
                    <div className="rc-mode-tabs" role="group" aria-label="Chế độ chơi">{([{ id: 'campaign', name: 'Hành trình' }, { id: 'quick', name: 'Đua nhanh' }, { id: 'practice', name: 'Luyện toán' }] as const).map(m => <button key={m.id} aria-pressed={config.mode === m.id} onClick={() => change({ mode: m.id, review: undefined, waitForChoice: m.id === 'practice' })}>{m.name}</button>)}</div>
                    <div className="rc-setup-section"><div className="rc-label-row"><h3>Độ khó toán</h3><span>Theo lớp {student.grade}</span></div><div className="rc-choice-grid" role="group" aria-label="Độ khó toán">{LEVELS.map(l => <button key={l.id} aria-pressed={config.difficulty === l.id} onClick={() => change({ difficulty: l.id })}><span>{l.name}</span><small>{l.caption}</small></button>)}</div><p className="rc-syllabus" data-testid="racing-syllabus"><Check size={15}/>{syllabus(config.grade, config.difficulty)}</p><p className="rc-rival-note">{config.mode === 'practice' ? 'Luyện toán không có đối thủ.' : RIVAL_SKILLS[config.difficulty].description}</p><p className="rc-sample" data-testid="racing-sample"><span>Ví dụ</span>{sample.text}</p></div>
                    <div className="rc-setup-section"><div className="rc-label-row"><h3>Nhịp đua</h3><span>Đổi nhịp, giữ mức toán</span></div><div className="rc-pace-grid" role="group" aria-label="Nhịp đua">{PACES.map((p, i) => <button key={p.id} aria-pressed={config.pace === p.id} onClick={() => change({ pace: p.id })}><span>{Array.from({ length: i + 1 }, (_, j) => <i key={j}/>)}</span>{p.name}<small>Ít nhất {p.seconds} giây/câu</small></button>)}</div></div>
                    <div className="rc-setup-section"><div className="rc-label-row"><h3>{config.mode === 'campaign' ? 'Chặng đua' : 'Chọn đường đua'}</h3><span>{config.mode === 'campaign' ? `${finished}/12 hoàn thành` : 'Ba vùng đất đang chờ'}</span></div><div className="rc-regions">{REGIONS.map((r, i) => <button key={r.id} aria-pressed={config.region === r.id} disabled={config.mode === 'campaign' && i > 0 && !progress.missions[i * 4 - 1]} onClick={() => change({ region: r.id, mission: i * 4 })}><span className={'rc-region-art rc-region-' + r.id}><i/><b/><em/>{config.mode === 'campaign' && i > 0 && !progress.missions[i * 4 - 1] && <LockKeyhole size={18}/>}</span><span>{r.short}</span></button>)}</div>
                    {config.mode === 'campaign' && <div className="rc-missions" aria-label="Các chặng">{MISSIONS.filter(m => m.region === config.region).map(m => <button key={m.id} disabled={m.id > 0 && !progress.missions[m.id - 1]} aria-pressed={config.mission === m.id} aria-label={`Chặng ${m.id + 1}: ${m.name}${m.id > 0 && !progress.missions[m.id - 1] ? ' · Chưa mở' : ''}`} onClick={() => change({ mission: m.id })}><span>{m.cup ? <Trophy size={19}/> : String(m.id + 1).padStart(2, '0')}</span><div>{m.name}<small>{[1, 2, 3].map(i => <Star size={10} key={i} fill={(progress.missions[m.id] || 0) >= i ? 'currentColor' : 'none'}/>)}</small></div>{m.id > 0 && !progress.missions[m.id - 1] ? <LockKeyhole size={14}/> : <ChevronRight size={15}/>}</button>)}</div>}</div>
                    <details className="rc-options"><summary><Settings2 size={16}/>Hỗ trợ & hình ảnh</summary><label><input type="checkbox" checked={config.waitForChoice} disabled={config.mode === 'practice'} onChange={e => change({ waitForChoice: e.target.checked })}/>Chờ em chọn đáp án <small>Dừng trước cổng, không cần vội</small></label><label><input type="checkbox" checked={config.autoNitro} onChange={e => change({ autoNitro: e.target.checked })}/>Tự dùng nitro khi đầy</label><label><input type="checkbox" checked={reduced} onChange={e => setReduced(e.target.checked)}/>Giảm chuyển động</label><label>Đồ họa<select aria-label="Chất lượng đồ họa" value={flat ? 'flat' : low ? 'low' : 'standard'} onChange={e => { setFlat(e.target.value === 'flat'); setLow(e.target.value === 'low'); }}><option value="standard">3D tiêu chuẩn</option><option value="low">3D tiết kiệm</option><option value="flat">2D nhẹ</option></select></label></details>
                    {draft.session && <button className="rc-resume-draft" onClick={restore}><Play size={18}/><span>Tiếp tục ván đang dở<small>{LEVELS.find(l => l.id === draft.session!.config.difficulty)?.name} · {PACES.find(p => p.id === draft.session!.config.pace)?.name} · {draft.session.answers.length}/{draft.session.questions.length} câu</small></span><ChevronRight size={18}/></button>}
                    {draft.corrupt && <p role="status" className="rc-notice">Ván lưu chưa đọc được. Em có thể bắt đầu ván mới; thành tích đã lưu vẫn còn.</p>}
                    <button className="rc-primary rc-start" onClick={() => start()}><Flag size={21}/><span>{draft.session ? 'Đua ván mới' : config.mode === 'practice' ? 'Bắt đầu luyện toán' : 'Cùng xuất phát!'}<small>{LEVELS.find(l => l.id === config.difficulty)!.name} · {PACES.find(p => p.id === config.pace)!.name} · {raceQuestionCount(config)} cổng toán</small></span><ArrowRight size={22}/></button>
                    <p className="rc-reward-note">{config.mode === 'campaign' ? 'Hoàn thành nhận sao. Tính chính xác để nhận đến 3 sao.' : 'Chơi thoải mái, lưu kỷ lục riêng. Không cộng sao thưởng.'}</p>
                </section>
            </main><footer className="rc-footer"><span>12 chặng đua · 3 vùng đất · Một tay lái là em</span>{onLegacy && <button onClick={onLegacy}>Mở phiên bản cũ</button>}</footer>
        </> : <>
            <div className="rc-race-scene" aria-hidden="true" onPointerDown={e => { touch.current = { x: e.clientX, y: e.clientY }; }} onPointerUp={e => { const t = touch.current; touch.current = null; if (t && Math.abs(e.clientX - t.x) > 35 && Math.abs(e.clientX - t.x) > Math.abs(e.clientY - t.y)) move(e.clientX > t.x ? 1 : -1); }} onPointerCancel={() => { touch.current = null; }}>{scene}</div>
            <header className="rc-hud"><div className="rc-hud-left"><button className="rc-icon" aria-label="Tạm dừng" onClick={pause}><Pause size={20}/></button><div><span className="rc-small-label">{config.mode === 'practice' ? 'LUYỆN TOÁN' : region.short.toUpperCase()}</span><strong>{cfg.mode === 'campaign' ? mission.name : cfg.mode === 'quick' ? 'Đua nhanh' : 'Tay lái toán học'}</strong></div></div><div className="rc-rank"><Trophy size={19}/><strong>{cfg.mode === 'practice' ? '∞' : rankOf(view)}</strong><span>{cfg.mode === 'practice' ? 'Thư thả' : '/ 4'}</span></div><button className="rc-icon" aria-label={soundEnabled ? 'Tắt hiệu ứng âm thanh' : 'Bật hiệu ứng âm thanh'} onClick={toggleSound}>{soundEnabled ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button></header>
            <div className="rc-progress-track" aria-label={`Đã hoàn thành ${view.answers.length} trên ${view.questions.length} câu`}><i style={{ width: Math.min(100, me!.distance / finishDistance(view) * 100) + '%' }}/>{view.questions.map((q, i) => <span key={i} className={view.answers[i] ? view.answers[i].correct ? 'is-correct' : 'is-miss' : ''} style={{ left: (i * SEGMENT + GATE) / finishDistance(view) * 100 + '%' }}/>)}</div>
            <section className="rc-question-panel" aria-label="Câu hỏi hiện tại"><div className="rc-question-meta"><span>{LEVELS.find(l => l.id === cfg.difficulty)!.name} · Lớp {cfg.grade}</span><span>{question ? `Cổng ${qi + 1}/${view.questions.length}` : `${view.answers.length}/${view.questions.length} câu`}<span className="rc-time"> · {timeLabel(view.elapsed)}</span></span></div><div className={question ? 'rc-equation' + (question.text.length > 36 ? ' rc-equation-long' : '') : 'rc-drive-title'}>{question ? question.text : view.answers.length === view.questions.length ? 'Vạch đích ở phía trước!' : view.elapsed < 4 ? 'Cùng lên đường nào!' : 'Lái khéo · Tích năng lượng'}</div><p>{question ? view.answerRush ? 'Đã chốt đáp án · Đang tăng tốc tới trạm!' : listening ? 'Đang nghe · Đồng hồ và xe đã dừng.' : cfg.waitForChoice ? 'Chạm đáp án hoặc nhấn 1 · 2 · 3 để chọn.' : `Chọn làn đáp án · còn ${remaining.toFixed(1)} giây` : 'Tránh cọc tiêu, nhặt tinh thể vàng để nạp nitro.'}</p>{question && <><button className="rc-listen" aria-label={listening ? 'Dừng nghe câu hỏi' : 'Nghe câu hỏi'} disabled={!!view.answerRush} onClick={listen}><Volume2 size={13}/>{listening ? 'Dừng' : 'Nghe'}</button><div className="rc-question-timer"><i style={{ width: Math.min(100, remaining / (view.answerRush?.duration ?? readSeconds(view, qi)) * 100) + '%' }}/></div></>}</section>
            <div className="rc-side-info"><span><Gauge size={16}/>{PACES.find(p => p.id === cfg.pace)!.name}</span>{me!.combo >= 2 && <span className="rc-combo"><Sparkles size={16}/>{me!.combo} câu đúng liên tiếp</span>}<span>{cfg.mode === 'practice' ? 'Không có đối thủ' : 'Đối thủ · ' + LEVELS.find(l => l.id === cfg.difficulty)!.name}</span></div>
            <div className={'rc-feedback ' + (view.lastCorrect === false ? 'rc-feedback-warm' : '')} role="status" aria-live="polite">{qi < 0 && view.elapsed < view.feedbackUntil ? view.feedback : ''}</div>
            <div className="rc-race-bottom"><div className="rc-answers" role="group" aria-label="Chọn làn đáp án">{question ? question.options.map((v, lane) => <button key={`${qi}:${lane}`} aria-pressed={me!.target === lane} disabled={!!view.answerRush} onClick={() => select(lane, qi)}><kbd>{lane + 1}</kbd><strong className={String(v).length > 5 ? 'rc-answer-wide' : undefined}>{v}</strong><span>{me!.target === lane ? view.answerRush ? 'Đã chốt' : !view.selected ? 'Chạm để chọn' : 'Làn đã chọn' : ['Làn trái', 'Làn giữa', 'Làn phải'][lane]}</span></button>) : <div className="rc-driving-hint"><Flag size={18}/>{view.answers.length === view.questions.length ? 'Dùng nitro để bứt phá về đích!' : 'Cổng toán tiếp theo đang đến. Sẵn sàng nhé!'}</div>}</div>
            <button className="rc-submit" aria-label="Trả lời ngay" aria-keyshortcuts="Enter" disabled={!question || !view.selected || !!view.answerRush || view.paused || view.phase !== 'racing'} onClick={() => submit(qi)}><Check size={19}/><span>{view.answerRush ? 'Đang tới trạm!' : 'Trả lời ngay'}<small>{view.answerRush ? 'Đã khóa đáp án' : question && view.selected ? 'Chốt ' + question.options[me!.target] + ' · Enter' : question ? 'Chọn đáp án trước nhé' : 'Sẵn sàng cho câu tiếp theo'}</small></span><ArrowRight size={19}/></button><div className="rc-controls"><button className="rc-steer" aria-label="Chuyển làn trái" disabled={!!view.answerRush} onClick={() => move(-1)}><ArrowLeft/><kbd>← / A</kbd></button><button className={'rc-nitro ' + (me!.energy >= 100 ? 'is-full' : '')} aria-label={`Nitro ${me!.energy}%${view.queuedBoost ? ', đã hẹn dùng sau cổng' : ''}`} disabled={me!.energy < 100 || me!.boost > 0 || view.queuedBoost} onClick={nitro}><i style={{ width: `${me!.energy}%` }}/><Zap size={20} fill={me!.energy >= 100 ? 'currentColor' : 'none'}/><span>{view.queuedBoost ? 'Sẵn sàng sau cổng' : me!.boost > 0 ? 'Đang bứt tốc!' : me!.energy >= 100 ? 'Bứt tốc!' : `Nitro ${me!.energy}%`}<small>{me!.energy >= 100 ? 'SPACE' : 'Tính đúng để nạp đầy'}</small></span></button><button className="rc-steer" aria-label="Chuyển làn phải" disabled={!!view.answerRush} onClick={() => move(1)}><ArrowRight/><kbd>→ / D</kbd></button></div></div>
            {view.phase === 'ready' && <Dialog title="Một chặng đua đang chờ em"><span className="rc-dialog-eyebrow">{region.name}</span><div className="rc-how"><div><span>1</span><p><strong>Chọn làn</strong>Dùng ← →, A/D hoặc hai nút mũi tên.</p></div><div><span>2</span><p><strong>Tính rồi chọn</strong>Chọn đáp án, rồi bấm Trả lời ngay hoặc Enter để tăng tốc tới trạm. Có thể tiếp tục suy nghĩ nếu chưa chắc.</p></div><div><span>3</span><p><strong>Bứt tốc</strong>Tính đúng để nạp nitro. Thanh đầy, bấm ⚡ hoặc Space.</p></div></div><div className="rc-config-summary"><strong>{LEVELS.find(l => l.id === cfg.difficulty)!.name} · {PACES.find(p => p.id === cfg.pace)!.name}</strong><span>{syllabus(cfg.grade, cfg.difficulty)}</span>{cfg.waitForChoice && <span>Đường đua sẽ chờ em chọn đáp án.</span>}</div><button className="rc-primary" onClick={() => { live.current!.phase = 'racing'; persistDraft(); sync(); }}><Play size={20}/>Lên đường!</button><button className="rc-text-button" onClick={toGarage}>Đổi cấu hình</button></Dialog>}
            {view.paused && view.phase === 'racing' && <Dialog title="Nghỉ một chút nhé" close={resume}><p>Xe và đồng hồ đang dừng. Mọi đáp án và năng lượng đều được giữ lại.</p><div className="rc-config-summary"><strong>{LEVELS.find(l => l.id === cfg.difficulty)!.name} · {PACES.find(p => p.id === cfg.pace)!.name}</strong><span>{syllabus(cfg.grade, cfg.difficulty)}</span></div>{renderWarning && <p className="rc-notice">Đã chuyển sang đồ họa nhẹ để tiếp tục ván.</p>}<label className="rc-check-line"><input type="checkbox" checked={reduced} onChange={e => setReduced(e.target.checked)}/>Giảm chuyển động</label><button className="rc-primary" onClick={resume}><Play size={20}/>Tiếp tục đua</button><button className="rc-secondary" onClick={toGarage}><Home size={18}/>Về garage · Giữ ván dở</button></Dialog>}
            {result && <Dialog title={result.rank === 1 && cfg.mode !== 'practice' ? 'Một chặng đua thật tuyệt!' : 'Em đã về đích!'}><div className="rc-result-trophy"><Trophy size={54}/><div>{[1, 2, 3].map(i => <Star key={i} size={30} fill={i <= result.stars ? 'currentColor' : 'none'} style={{ opacity: i <= result.stars ? 1 : .28 }}/>)}</div></div><p className="rc-result-caption">{cfg.mode === 'practice' ? 'Từng phép tính, thêm một chút tự tin.' : `${region.name} · Vị trí ${result.rank}/4`}</p><div className="rc-result-stats"><div><strong>{result.correct}/{result.total}</strong><span>Câu chính xác</span></div><div><strong>{timeLabel(view.elapsed)}</strong><span>Thời gian đua</span></div><div><strong>{result.bestCombo}</strong><span>Chuỗi tốt nhất</span></div></div><div className="rc-result-config">Lớp {cfg.grade} · Toán {LEVELS.find(l => l.id === cfg.difficulty)!.name.toLowerCase()} · {PACES.find(p => p.id === cfg.pace)!.name}{cfg.waitForChoice ? ' · Chờ chọn' : ''}</div>
                {award?.ok ? <div className="rc-award"><Star size={20}/><span>{cfg.mode === 'campaign' ? award.earned ? `+${award.earned} sao mới vào hồ sơ` : 'Đã lưu thành tích · Sao tốt nhất được giữ lại' : 'Đã lưu kết quả luyện tập'}{(award.bonusStars || 0) > 0 && <small>Thành tích mới: +{award.bonusStars} sao</small>}</span></div> : <div className="rc-notice" role="alert">{award ? 'Chưa lưu được kết quả. Thành tích đang được giữ để thử lại.' : 'Đang lưu thành tích…'}{award && <button className="rc-secondary" onClick={saveResult}>Thử lưu lại</button>}</div>}
                {result.review.length > 0 && <details className="rc-review"><summary>Cùng nhớ lại {result.review.length} phép tính</summary>{result.review.map((q, i) => <p key={i}><Check size={15}/>{q.explanation}</p>)}<button className="rc-secondary" disabled={!award?.ok} onClick={() => start({ ...cfg, mode: 'practice', waitForChoice: true, review: result.review.map(q => q.id) }, view.seed, view.questionVersion ?? 1)}>Luyện lại các câu này</button></details>}
                <div className="rc-result-actions">{cfg.mode === 'campaign' && cfg.mission < 11 && <button className="rc-primary" disabled={!award?.ok} onClick={() => start({ ...cfg, mission: cfg.mission + 1 })}>Chặng tiếp theo<ArrowRight size={18}/></button>}<button className="rc-secondary" disabled={!award?.ok} onClick={() => start(cfg)}><RotateCcw size={17}/>Chơi lại · Cùng độ khó</button><button className="rc-text-button" onClick={toGarage}>Về garage</button></div>
            </Dialog>}
        </>}
        {saveWarning && <div className="rc-save-warning" role="status">Chưa lưu được ván dở trên thiết bị. Giữ trang mở để tiếp tục.</div>}
        {help && <Dialog title="Tay lái toán học" close={() => setHelp(false)}><div className="rc-how"><div><span>1</span><p><strong>Toán và tốc độ chọn riêng</strong>Chọn Dễ, Trung bình hoặc Khó theo lớp. Nhịp đua quyết định tốc độ và thời gian đọc.</p></div><div><span>2</span><p><strong>Tính đúng, xe bứt lên</strong>Đúng nhận 25 năng lượng. Đủ 100, dùng nitro bằng Space hoặc nút tia chớp.</p></div><div><span>3</span><p><strong>Cứ thử, cứ tiến bộ</strong>Sai không bị loại. Mỗi chặng có đến 3 sao: hoàn thành, đúng 70%, đúng 90%.</p></div></div><p>Đua nhanh và luyện toán không cộng tiền sao. Xe mở thêm sau 4 và 8 chặng; mọi xe có cùng tốc độ.</p><button className="rc-primary" onClick={() => setHelp(false)}>Em hiểu rồi</button></Dialog>}
    </div>;
}
