import type { Lesson, Step } from '../model';
const line = (notes: number[]): Step[] => notes.map(midi => ({ pitches: [midi], beats: 1 }));
export const LESSONS: Lesson[] = [
    { id:'learn-1',title:'Xin chào, phím đàn!',subtitle:'Một chạm, một âm thanh',icon:'👋',instruction:'Chạm vào phím Đô đang sáng. Nhả tay rồi thử thêm hai lần nhé.',tip:'Trên máy tính, phím A cũng chơi được nốt Đô.',steps:line([60,60,60]) },
    { id:'learn-2',title:'Giữ một nốt thật êm',subtitle:'Nhấn, giữ… rồi nhả',icon:'🌱',instruction:'Giữ phím Đô một chút, rồi nhả tay. Mình thử với Rê và Mi nữa nhé.',tip:'Thả lỏng bàn tay. Với organ, tiếng ngân theo thời gian em giữ phím.',steps:[60,62,64].map(m=>({pitches:[m],beats:2,holdMs:600})),demonstration:'hand' },
    { id:'learn-3',title:'Tìm nhà của Đô',subtitle:'Bên trái hai phím đen',icon:'🏡',instruction:'Tìm nhóm hai phím đen. Phím trắng ngay bên trái là Đô. Thử Đô thấp, rồi Đô cao.',tip:'Hai nốt cùng tên nhưng ở hai quãng khác nhau.',steps:line([60,72,60,72]),demonstration:'keys' },
    { id:'learn-4',title:'Ba bạn Đô, Rê, Mi',subtitle:'Ba bước chân nhỏ',icon:'🐾',instruction:'Đô, Rê, Mi… rồi mình cùng đi ngược lại.',tip:'Nhìn tên trên phím và lắng nghe từng nốt.',steps:line([60,62,64,64,62,60]) },
    { id:'learn-5',title:'Bảy sắc âm thanh',subtitle:'Làm quen Fa, Sol, La, Si',icon:'🌈',instruction:'Chơi Fa, Sol, La, Si. Sau đó cùng gặp đủ bảy bạn nhé.',tip:'Giữa Mi–Fa và Si–Đô không có phím đen.',steps:line([65,67,69,71,60,62,64,65,67,69,71,72]) },
    { id:'learn-6',title:'Lên đồi, xuống đồi',subtitle:'Nghe âm thấp và âm cao',icon:'⛰️',instruction:'Đi sang phải để nghe âm cao hơn, rồi trở về với âm thấp.',tip:'Âm cao và thấp khác với âm to và nhỏ.',steps:line([60,64,67,72,67,64,60]) },
    { id:'learn-7',title:'Giọt mưa và cầu vồng',subtitle:'Nốt ngắn, nốt dài',icon:'🌦️',instruction:'Hai nốt ngắn, rồi giữ nốt Sol dài hơn một chút. Nhả tay để kết thúc nốt dài.',tip:'Nghe mẫu trước để cảm nhận sự khác nhau.',steps:[{pitches:[64],beats:.5},{pitches:[64],beats:.5},{pitches:[67],beats:2,holdMs:900},{pitches:[62],beats:.5},{pitches:[62],beats:.5},{pitches:[60],beats:2,holdMs:900}] },
    { id:'learn-8',title:'Âm nhạc cũng nghỉ',subtitle:'Một khoảng lặng nhỏ',icon:'☁️',instruction:'Chơi một nốt, nhả tay và chờ đám mây nghỉ trôi qua rồi chơi nốt tiếp theo.',tip:'Khoảng nghỉ là một phần của âm nhạc. Cứ thong thả nhé.',steps:[{pitches:[60],beats:1,gapBeats:1},{pitches:[64],beats:1,gapBeats:1},{pitches:[67],beats:1,gapBeats:1},{pitches:[72],beats:2}] },
    { id:'learn-9',title:'Hai bạn cùng hát',subtitle:'Thử một hợp âm nhỏ',icon:'🤝',instruction:'Chạm và giữ Đô cùng Mi bằng hai ngón. Sau đó thử Rê cùng Fa.',tip:'Trên bàn phím máy tính: giữ A + D, rồi S + F. Không cần dùng sức.',steps:[{pitches:[60,64],beats:2},{pitches:[62,65],beats:2},{pitches:[60,67],beats:2}],demonstration:'hand' },
    { id:'learn-10',title:'Giai điệu đầu tiên',subtitle:'Một bài nhạc của em',icon:'🌟',instruction:'Ghép những điều vừa học thành một giai điệu nhỏ. Em sẵn sàng rồi!',tip:'Tiếp theo, ghé Tập theo bài nhạc để chọn một bài nhé.',steps:line([60,62,64,60,64,65,67,67,65,64,62,60]) },
];
