import React from 'react';
import { ArrowRight, Sword, Trophy, Wind } from 'lucide-react';
import { Event, Session } from './model';
import { attemptKey, finished, medalOf, nodeOf, questionOf, recordOf } from './engine';
import { missionOf } from './content';
import { BuffType } from '../engine/types';
import { getBuffDescription, getBuffName } from '../engine/buffs';
import { QuestionView } from './QuestionView';
import { EncounterQuestion } from './EncounterQuestion';
import { Modal } from './Modal';
import { portraitArt } from './art';
type Command=Event extends infer T?T extends Event?Omit<T,'sessionId'>:never:never;
export function RoundPanel({s,worldReady,reduced,send,onRead,onReady,home,replay,next,commit,reward,saveError,panelRef,pause}:{pause:()=>void;s:Session;worldReady:boolean;reduced:boolean;send:(e:Command)=>void;onRead:()=>void;onReady:()=>void;home:()=>void;replay:()=>void;next:()=>void;commit:()=>void;reward:{ok:boolean;earned:number;bonusStars?:number}|null;saveError:boolean;panelRef:React.RefObject<HTMLElement|null>}){
 const node=nodeOf(s),q=questionOf(s);
 if(s.paused||['readyToRoll','rolling','moving','landing'].includes(s.phase))return null;
 return <Modal title={finished(s)?'Kết thúc hành trình':node.kind==='boss'?'Thử thách Rồng Thần':node.kind==='buff'?'Món quà của nàng tiên':s.phase==='teleport'?'Cổng phép thuật':'Thử thách trên đường'} onClose={finished(s)?home:pause} dismissOnBackdrop={false} className={`dq-encounter-modal ${['intro','question','feedback'].includes(s.phase)?'dq-question-modal':''}`}><section ref={panelRef} className="dq-play-panel" aria-label="Điều khiển hành trình">
  {['intro','question','feedback'].includes(s.phase)&&q&&<EncounterQuestion key={s.id+':'+attemptKey(s)} s={s} worldReady={worldReady} reduced={reduced} send={send} onRead={onRead} onReady={onReady}/>}
  {s.phase==='teleport'&&s.teleport&&<div className="dq-encounter dq-portal-panel"><Wind size={56}/><h2>{s.teleport.protected?'Áo Choàng Bay bảo vệ em!':s.teleport.distance<0?'Cạm bẫy kéo em lùi lại!':s.teleport.distance>0?'Cổng phép thuật đưa em tiến lên!':'Cánh cổng vẫn yên lặng'}</h2><p>{s.teleport.protected?`Chặn dịch chuyển lùi ${Math.abs(s.teleport.distance)} ô. Em giữ vị trí hiện tại.`:s.teleport.newPosition===node.index?'Em đứng tại ô này và được gieo tiếp.':`${s.teleport.distance<0?'Lùi':'Tiến'} ${Math.abs(s.teleport.distance)} ô → tới ô ${s.teleport.newPosition+1}. Sự kiện ở ô mới sẽ được xử lý.`}</p><button className="dq-primary dq-wide" onClick={()=>send({type:'continue'})}>{s.teleport.protected||s.teleport.newPosition===node.index?'Tiếp tục gieo xúc xắc':`Đến ô ${s.teleport.newPosition+1}`}<ArrowRight size={18}/></button></div>}
  {finished(s)&&<div className="dq-result"><img className="dq-result-art" src={portraitArt('dragon')} alt="Rồng Thần và viên ngọc phép thuật"/><h2>{s.phase==='won'?'Chiến thắng Rồng Thần!':'Hết máu rồi, thử lại nhé!'}</h2><p>{s.phase==='won'?`Em đã vượt qua bàn 50 ô và mang ${missionOf(s.config.missionId).gift.toLocaleLowerCase('vi')} về.`:'Hãy tìm Chén Thánh để hồi máu và Kiếm Thánh để giảm câu hỏi boss trong lượt sau.'}</p>{s.phase==='won'&&<div className="dq-medal"><Trophy size={30}/>{medalOf(s)==='gold'?'Huy chương Vàng':medalOf(s)==='silver'?'Huy chương Bạc':'Huy chương Đồng'}</div>}<div className="dq-result-stats"><span><strong>{s.score}</strong>Điểm trận đấu</span><span><strong>{recordOf(s).independent}/{recordOf(s).total}</strong>Tự giải đúng</span><span><strong>{s.turn}</strong>Lượt gieo</span></div>{s.phase==='won'&&<p role="status">{saveError?'Chưa lưu được phần thưởng. Hãy thử lưu lại.':s.rewardCommitted?reward?.earned?`Đã lưu · +${reward.earned} sao`:'Đã lưu chặng này. Chơi lại không cộng trùng sao.':'Đang lưu phần thưởng…'}</p>}{saveError&&<button className="dq-primary dq-wide" onClick={commit}>Lưu lại phần thưởng</button>}{s.phase==='won'&&s.rewardCommitted&&missionOf(s.config.missionId).index<19&&<button className="dq-primary dq-wide" onClick={next}>Chặng tiếp theo<ArrowRight size={18}/></button>}<div className="dq-button-row"><button className="dq-secondary" disabled={s.phase==='won'&&!s.rewardCommitted} onClick={replay}>Chơi lại</button><button className="dq-secondary" onClick={home}>Về bản đồ</button></div></div>}
  {!finished(s)&&<div className="dq-original-buffs" aria-label="Buff đang có">{[BuffType.HolySword,BuffType.HolyGrail,BuffType.FlyingCloak].map(b=><div key={b} title={getBuffDescription(b)}>{b===BuffType.HolySword?<Sword size={19}/>:b===BuffType.HolyGrail?<Trophy size={19}/>:<Wind size={19}/>}<span>{getBuffName(b)}<small>{b===BuffType.FlyingCloak?s.buffs.flyingCloak?'Đang bảo vệ':'Chưa có':`${s.buffs[b]} / ${b===BuffType.HolySword?2:3}`}</small></span></div>)}</div>}
 </section></Modal>;
}

