import React from 'react';
import { ArrowRight, Crown, Heart, Sparkles, Sword, Trophy, Wind } from 'lucide-react';
import { Event, Session } from './model';
import { attemptKey, finished, medalOf, nodeOf, questionOf, recordOf } from './engine';
import { missionOf, NODE_COPY, regionOf } from './content';
import { BuffType } from '../engine/types';
import { getBuffDescription, getBuffName } from '../engine/buffs';
import { QuestionView } from './QuestionView';
import { DragonPortrait } from './World2D';
import fairyPortrait from '../assets/fairy.png';
import goblinPortrait from '../assets/demon.png';
type Command=Event extends infer T?T extends Event?Omit<T,'sessionId'>:never:never;
const PIPS:Record<number,number[]>={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};
export function RoundPanel({s,worldReady,send,onRead,onReady,home,replay,next,commit,reward,saveError,panelRef}:{s:Session;worldReady:boolean;send:(e:Command)=>void;onRead:()=>void;onReady:()=>void;home:()=>void;replay:()=>void;next:()=>void;commit:()=>void;reward:{ok:boolean;earned:number;bonusStars?:number}|null;saveError:boolean;panelRef:React.RefObject<HTMLElement|null>}){
 const node=nodeOf(s),q=questionOf(s),region=regionOf(s.config.missionId),rolling=s.phase==='rolling',face=rolling?Math.floor(s.phaseMs/160)%6+1:s.dice||1;
 return <section ref={panelRef} className="dq-play-panel" aria-label="Điều khiển hành trình">
  <div className="dq-round-heading"><span className="dq-eyebrow">Ô {node.index+1} / 50 · {node.title}</span><strong className="dq-score">{s.score} điểm</strong></div>
  <div className="dq-board-progress" aria-label={`Đang ở ô ${node.index+1} trên 50`}><span style={{width:`${(node.index+1)*2}%`}}/></div>
  {['readyToRoll','rolling','moving','landing'].includes(s.phase)&&<div className="dq-roll-panel">
   <h2>{rolling?'Xúc xắc đang quay…':s.phase==='moving'?'Tiến từng ô nào!':s.phase==='landing'?'Đã tới ô dừng':s.turn===0?'Gieo xúc xắc, lên đường!':'Đến lượt gieo tiếp theo'}</h2>
   <p>{s.phase==='moving'||s.phase==='landing'?`Xúc xắc ${s.dice} · Ô đích ${s.target+1}`:s.turn?`Lượt trước: ${s.dice} điểm. Sự kiện chỉ xảy ra tại ô dừng.`:'Cả 50 ô đã hiện trên bản đồ. Quay xúc xắc để biết em tiến bao nhiêu ô.'}</p>
   <div className={`dq-die ${rolling?'is-rolling':''}`} role="img" aria-label={rolling?'Xúc xắc đang quay':`Xúc xắc ${s.dice||'chưa gieo'}`}><div>{Array.from({length:9},(_,i)=><span key={i} className={PIPS[face].includes(i)?'pip':''}/>)}</div></div>
   <button className="dq-primary dq-wide" disabled={!worldReady||s.phase!=='readyToRoll'} onClick={()=>send({type:'roll'})}>{rolling?'Đang quay…':s.phase==='moving'||s.phase==='landing'?`Đang tới ô ${s.target+1}`:'Gieo xúc xắc'}<ArrowRight size={18}/></button>
   <small>Lượt {s.turn} · Kết quả từ 1 đến 6</small>
  </div>}
  {node.kind==='boss'&&!finished(s)&&<div className="dq-seals"><span>Còn {s.bossTotal-s.bossPhase} / {s.bossTotal} câu boss</span><span><Sword size={16}/> {s.buffs.holySword} kiếm</span></div>}
  {s.phase==='intro'&&<div className="dq-encounter">{node.kind==='boss'?<DragonPortrait className="dq-modal-dragon" color={region.color}/>:<img className="dq-encounter-character" src={node.kind==='buff'?fairyPortrait:goblinPortrait} alt={node.kind==='buff'?'Nàng tiên':'Quái vật'}/>}<h2>{NODE_COPY[node.kind].title}</h2><p>{NODE_COPY[node.kind].line}</p>{s.pendingBuff&&<p className="dq-hint">Quà tại ô này: {getBuffName(s.pendingBuff)} — {getBuffDescription(s.pendingBuff)}.</p>}<button className="dq-primary dq-wide" disabled={!worldReady} onClick={()=>send({type:'continue'})}>{NODE_COPY[node.kind].action}<ArrowRight size={18}/></button></div>}
  {(s.phase==='question'||s.phase==='feedback')&&q&&<><QuestionView key={attemptKey(s)} session={s} onAnswer={value=>send({type:'answer',slotId:q.slotId,encounter:s.encounter,value})} onHint={()=>send({type:'hint'})} onRead={onRead} onReady={onReady}/>{s.phase==='feedback'&&<><p className="dq-outcome" role="status">{s.feedback?.correct?`+${s.feedback.score} điểm${s.feedback.buff?' · Nhận '+getBuffName(s.feedback.buff):''}`:node.kind==='buff'?'Không nhận buff. Em vẫn giữ nguyên máu.':'Mất 1 tim.'}</p><button className="dq-primary dq-wide" onClick={()=>send({type:'continue'})}>{s.energy===0?'Xem kết quả':node.kind==='boss'?s.bossPhase+1===s.bossTotal?'Hoàn thành trận đấu':'Câu boss tiếp theo':'Tiếp tục gieo xúc xắc'}<ArrowRight size={18}/></button></>}</>}
  {s.phase==='teleport'&&s.teleport&&<div className="dq-encounter dq-portal-panel"><Wind size={56}/><h2>{s.teleport.protected?'Áo Choàng Bay bảo vệ em!':s.teleport.distance<0?'Cạm bẫy kéo em lùi lại!':s.teleport.distance>0?'Cổng phép thuật đưa em tiến lên!':'Cánh cổng vẫn yên lặng'}</h2><p>{s.teleport.protected?`Chặn dịch chuyển lùi ${Math.abs(s.teleport.distance)} ô. Em giữ vị trí hiện tại.`:s.teleport.newPosition===node.index?'Em đứng tại ô này và được gieo tiếp.':`${s.teleport.distance<0?'Lùi':'Tiến'} ${Math.abs(s.teleport.distance)} ô → tới ô ${s.teleport.newPosition+1}. Sự kiện ở ô mới sẽ được xử lý.`}</p><button className="dq-primary dq-wide" onClick={()=>send({type:'continue'})}>{s.teleport.protected||s.teleport.newPosition===node.index?'Tiếp tục gieo xúc xắc':`Đến ô ${s.teleport.newPosition+1}`}<ArrowRight size={18}/></button></div>}
  {finished(s)&&<div className="dq-result"><DragonPortrait color={region.color}/><h2>{s.phase==='won'?'Chiến thắng Rồng Thần!':'Hết máu rồi, thử lại nhé!'}</h2><p>{s.phase==='won'?`Em đã vượt qua bàn 50 ô và mang ${missionOf(s.config.missionId).gift.toLocaleLowerCase('vi')} về.`:'Hãy tìm Chén Thánh để hồi máu và Kiếm Thánh để giảm câu hỏi boss trong lượt sau.'}</p>{s.phase==='won'&&<div className="dq-medal"><Trophy size={30}/>{medalOf(s)==='gold'?'Huy chương Vàng':medalOf(s)==='silver'?'Huy chương Bạc':'Huy chương Đồng'}</div>}<div className="dq-result-stats"><span><strong>{s.score}</strong>Điểm trận đấu</span><span><strong>{recordOf(s).independent}/{recordOf(s).total}</strong>Tự giải đúng</span><span><strong>{s.turn}</strong>Lượt gieo</span></div>{s.phase==='won'&&<p role="status">{saveError?'Chưa lưu được phần thưởng. Hãy thử lưu lại.':s.rewardCommitted?reward?.earned?`Đã lưu · +${reward.earned} sao`:'Đã lưu chặng này. Chơi lại không cộng trùng sao.':'Đang lưu phần thưởng…'}</p>}{saveError&&<button className="dq-primary dq-wide" onClick={commit}>Lưu lại phần thưởng</button>}{s.phase==='won'&&s.rewardCommitted&&missionOf(s.config.missionId).index<19&&<button className="dq-primary dq-wide" onClick={next}>Chặng tiếp theo<ArrowRight size={18}/></button>}<div className="dq-button-row"><button className="dq-secondary" disabled={s.phase==='won'&&!s.rewardCommitted} onClick={replay}>Chơi lại</button><button className="dq-secondary" onClick={home}>Về bản đồ</button></div></div>}
  {!finished(s)&&<div className="dq-original-buffs" aria-label="Buff đang có">{[BuffType.HolySword,BuffType.HolyGrail,BuffType.FlyingCloak].map(b=><div key={b} title={getBuffDescription(b)}>{b===BuffType.HolySword?<Sword size={19}/>:b===BuffType.HolyGrail?<Trophy size={19}/>:<Wind size={19}/>}<span>{getBuffName(b)}<small>{b===BuffType.FlyingCloak?s.buffs.flyingCloak?'Đang bảo vệ':'Chưa có':`${s.buffs[b]} / ${b===BuffType.HolySword?2:3}`}</small></span></div>)}</div>}
 </section>;
}

