// Bài học — Mầm non: bài ngắn "xem – nghe – chạm" (tự đọc to) cho kỹ năng chưa có hoạt động Mầm non.
// Kỹ năng đã có hoạt động thì "Học bài" mở hoạt động đó (services/study/lessons/preschool.ts).
import { know, lesson, pic, text } from '../build';
import type { LessonBook } from '../types';

export default {
    'mn.ordinal': lesson('mn.ordinal', {
        v: 2, autoRead: true,
        goal: 'đếm được vị trí: thứ nhất, thứ hai, thứ ba.',
        hook: { md: 'Các bạn đang xếp hàng. Bạn nào đứng thứ nhất?' },
        know: [
            know('Đếm từ lá cờ',
                pic('rowSVG', ['🐶', '🐱', '🐰', '🐻'], { flag: true }),
                text('Bắt đầu đếm từ lá cờ.'),
                text('Bạn chó đứng thứ nhất. Bạn mèo đứng thứ hai.'),
            ),
            know('Bé đếm tiếp nhé',
                pic('rowSVG', ['🐶', '🐱', '🐰', '🐻'], { flag: true }),
                text('Bạn thỏ đứng thứ ba. Bạn gấu đứng thứ tư.'),
            ),
        ],
        remember: ['Đếm từ lá cờ: thứ nhất, thứ hai, thứ ba, thứ tư.'],
    }),
    'mn.combine': lesson('mn.combine', {
        v: 2, autoRead: true,
        goal: 'gộp hai nhóm lại và tách một nhóm thành hai nhóm.',
        hook: { md: 'Có ba chú gà con, thêm hai chú gà con nữa. Có tất cả mấy chú?' },
        know: [
            know('Gộp lại',
                pic('groupsSVG', [{ emoji: '🐥', n: 3 }, { emoji: '🐥', n: 2 }]),
                text('Ba chú gà và hai chú gà.'),
                text('Gộp lại được năm chú gà.'),
            ),
            know('Tách ra',
                pic('groupsSVG', [{ emoji: '🌸', n: 2 }, { emoji: '🌸', n: 1 }]),
                text('Có ba bông hoa.'),
                text('Tách thành hai bông và một bông.'),
            ),
        ],
        remember: ['Gộp lại thì được nhiều hơn.', 'Tách ra thì mỗi nhóm ít hơn.'],
    }),
    'mn.pattern': lesson('mn.pattern', {
        v: 2, autoRead: true,
        goal: 'tìm ra quy luật lặp lại và đoán hình tiếp theo.',
        hook: { md: 'Dâu, chó, dâu, chó… Tiếp theo là gì?' },
        know: [
            know('Hai hình lặp lại',
                pic('rowSVG', ['🍓', '🐶', '🍓', '🐶', '🍓', null]),
                text('Quả dâu, bạn chó, cứ lặp lại.'),
                text('Sau quả dâu là bạn chó.'),
            ),
            know('Ba hình lặp lại',
                pic('rowSVG', ['🦋', '🦋', '🐶', '🦋', '🦋', null]),
                text('Hai bướm, một chó, cứ lặp lại.'),
                text('Tiếp theo là bạn chó.'),
            ),
        ],
        remember: ['Tìm nhóm hình lặp lại, rồi đoán hình tiếp theo.'],
    }),
    'mn.shapes3d': lesson('mn.shapes3d', {
        v: 2, autoRead: true,
        goal: 'nhận biết khối cầu, khối vuông, khối trụ, khối chữ nhật.',
        hook: { md: 'Quả bóng và con xúc xắc có dạng khối gì?' },
        know: [
            know('Khối cầu, khối vuông',
                pic('solidSVG', 'sphere'),
                text('Quả bóng có dạng khối cầu. Khối cầu lăn được.'),
                pic('solidSVG', 'cube', 'orange'),
                text('Con xúc xắc có dạng khối vuông.'),
            ),
            know('Khối trụ, khối chữ nhật',
                pic('solidSVG', 'cylinder', 'green'),
                text('Lon nước có dạng khối trụ.'),
                pic('solidSVG', 'box', 'purple'),
                text('Hộp sữa có dạng khối chữ nhật.'),
            ),
        ],
        remember: ['Khối cầu, khối vuông, khối trụ, khối chữ nhật.'],
    }),
    'mn.position': lesson('mn.position', {
        v: 2, autoRead: true,
        goal: 'nói được vị trí của đồ vật và các bạn.',
        hook: { md: 'Hộp quà ở trên hay ở dưới cái bàn?' },
        know: [
            know('Trên và dưới',
                pic('positionSceneSVG', '🎁', 'above'),
                text('Hộp quà ở trên cái bàn.'),
                pic('positionSceneSVG', '🐱', 'below'),
                text('Chú mèo ở dưới cái bàn.'),
            ),
            know('Các bạn xếp hàng',
                pic('rowSVG', ['🐶', '🐱', '🐰'], { flag: true }),
                text('Hàng đi về lá cờ. Chó đứng trước mèo.'),
                text('Thỏ đứng sau mèo. Mèo đứng ở giữa.'),
                text('Nhìn hình: chó bên trái, thỏ bên phải mèo.'),
            ),
        ],
        remember: ['Trên, dưới, trái, phải: bé nhìn từ chỗ mình ngồi.', 'Xếp hàng về lá cờ: chó trước mèo, thỏ sau mèo.'],
    }),
    'mn.daytime': lesson('mn.daytime', {
        v: 2, autoRead: true,
        goal: 'biết các buổi trong ngày và hôm qua, hôm nay, ngày mai.',
        hook: { md: 'Mặt trời mọc là buổi nào nhỉ?' },
        know: [
            know('Buổi trong ngày',
                pic('dayPartSVG', 'morning'),
                text('Mặt trời mọc: buổi sáng.'),
                pic('dayPartSVG', 'night'),
                text('Có trăng và sao: buổi tối.'),
            ),
            know('Hôm qua, hôm nay, ngày mai',
                text('Hôm qua là ngày trước hôm nay. Việc hôm qua đã xảy ra rồi.'),
                text('Ngày mai là ngày sau hôm nay. Việc ngày mai chưa xảy ra.'),
            ),
        ],
        remember: ['Sáng, trưa, chiều, tối.', 'Hôm qua, hôm nay, ngày mai.'],
    }),
} satisfies LessonBook;
