import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Clock3, Flag, Flower2, Heart, HelpCircle, House, LockKeyhole, Pause, Play, RotateCcw, Settings2, Shuffle, Sparkles, Star, Volume2 } from 'lucide-react';
import type { StudentProfile } from '../../types';
import { useStudent, useStudentActions } from '../../src/contexts/StudentContext';
import { useMusicControls } from '../../src/contexts/MusicContext';
import { cancelSpeech, speak } from '../../src/utils/speech';
import { REGION_GIFTS, MISSIONS, PICTURES, ZONES, missionConfig } from './content/catalog';
import { MemoryConfig, MemorySession, PAIR_COUNTS, ZoneId, columnsFor, resultOf } from './engine/model';
import { createSession } from './engine/game';
import { readMemoryDraft, readMemoryProgress, presetKey } from './progress/progress';
import { useMemorySession } from './session/useMemorySession';
import { closeMemoryAudio, memorySound } from './session/sound';
import { Island } from './components/Island';
import { Picture } from './components/Picture';
import { MemoryModal } from './components/MemoryModal';
import { MemoryTile } from './components/MemoryTile';
import './memory.css';

interface Preferences {sound:boolean;reduced:boolean;clock:boolean;relaxed:boolean;decoration:'flowers'|'stars'|'shells'}
function preferences(id:string):Preferences{
    const fallback:Preferences={sound:true,reduced:window.matchMedia('(prefers-reduced-motion: reduce)').matches,clock:false,relaxed:false,decoration:'flowers'};
    try{const p=JSON.parse(localStorage.getItem(`memory-prefs:${id}`)||'{}');return {...fallback,...Object.fromEntries(['sound','reduced','clock','relaxed'].filter(k=>typeof p[k]==='boolean').map(k=>[k,p[k]])),decoration:['flowers','stars','shells'].includes(p.decoration)?p.decoration:'flowers'};}catch{return fallback;}
}
const fresh=(config:MemoryConfig,seed=crypto.getRandomValues(new Uint32Array(1))[0],columns=columnsFor(config.pairs,window.innerWidth))=>createSession(config,seed,crypto.randomUUID(),columns);
const formatTime=(ms:number)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
function Stars({count=0}:{count?:number}){return <span className="mm-stars" aria-label={`${count} trên 3 sao`}>{[1,2,3].map(n=><Star key={n} size={15} fill={n<=count?'currentColor':'none'} className={n<=count?'earned':''}/>)}</span>;}

export default function ConnectedMemory({onExit,onLegacy,initialPairs=6}:{onExit:()=>void;onLegacy:()=>void;initialPairs?:number}){
    const {currentStudent}=useStudent(),{completeMemoryGame}=useStudentActions();
    const audio=useMusicControls();
    if(!currentStudent)return null;
    return <MemoryAdventure key={currentStudent.id} student={currentStudent} onExit={onExit} onLegacy={onLegacy} initialPairs={initialPairs} complete={completeMemoryGame} audio={audio}/>;
}
export interface AdventureProps {student:StudentProfile;onExit:()=>void;onLegacy:()=>void;initialPairs?:number;audio?:{soundEnabled:boolean;musicEnabled:boolean;toggleSound:()=>void;toggleMusic:()=>void};complete:(studentId:string,s:MemorySession)=>{ok:boolean;earned:number;bonusStars?:number;achievementNames?:string[]}}
export function MemoryAdventure({student,onExit,onLegacy,initialPairs=6,complete,audio}:AdventureProps){
    const progress=readMemoryProgress(student.memoryMatch),done=Object.keys(progress.missions).length,next=MISSIONS.find(m=>!progress.missions[m.id]);
    const [localPrefs,setPrefs]=useState(()=>preferences(student.id)),[zone,setZone]=useState<ZoneId>(next?.zone||'festival');
    const prefs=useMemo(()=>({...localPrefs,sound:audio?.soundEnabled??localPrefs.sound}),[localPrefs,audio?.soundEnabled]);
    const [draft,setDraft]=useState(()=>readMemoryDraft(student.id)),[round,setRound]=useState<MemorySession|null>(null);
    const [panel,setPanel]=useState<'quick'|'settings'|'book'|null>(null),[pending,setPending]=useState<MemoryConfig|null>(null);
    const [quickZone,setQuickZone]=useState<ZoneId>('garden'),[pairs,setPairs]=useState(initialPairs),[preview,setPreview]=useState(0),[shadow,setShadow]=useState(false);
    const z=ZONES.find(z=>z.id===zone)!,count=MISSIONS.filter(m=>m.zone===zone&&progress.missions[m.id]).length;
    const exitRound=useRef<(()=>void)|null>(null),pauseRound=useRef<(()=>void)|null>(null);
    useEffect(()=>{try{localStorage.setItem(`memory-prefs:${student.id}`,JSON.stringify(prefs));}catch{}},[prefs,student.id]);
    useEffect(()=>()=>{cancelSpeech();closeMemoryAudio();},[]);
    function start(config:MemoryConfig){setPanel(null);if(draft.session){setPending(config);return;}setRound(fresh(config));}
    function playNext(){if(!next){setPanel('book');return;}const config=missionConfig(next,prefs.relaxed);setZone(config.zone);start(config);}
    function leave(s:MemorySession,saved:boolean){setDraft({session:saved?null:{...s,paused:true},corrupt:false});setRound(null);}
    function again(config:MemoryConfig,seed?:number,columns?:number){setDraft({session:null,corrupt:false});setRound(fresh(config,seed,columns));}
    function following(s:MemorySession){
        const i=MISSIONS.findIndex(m=>m.id===s.config.missionId),upcoming=MISSIONS[i+1];
        if(!s.config.missionId){again(s.config);return;}
        setDraft({session:null,corrupt:false});
        if(upcoming){setZone(upcoming.zone);setRound(fresh(missionConfig(upcoming,prefs.relaxed)));}
        else{setRound(null);setPanel('book');}
    }
    function show(p:typeof panel){if(round)pauseRound.current?.();setPanel(p);}
    const unlocked=(id:string)=>{const index=MISSIONS.findIndex(m=>m.id===id);return index===0||!!progress.missions[id]||!!progress.missions[MISSIONS[index-1]?.id];};
    return <div className={`memory-adventure ${prefs.reduced?'mm-reduce-motion':''}`} style={{'--mm-accent':(round?ZONES.find(z=>z.id===round.config.zone)!:z).color} as React.CSSProperties}>
        <header className="mm-topbar"><button className="mm-icon" aria-label={round?'Về đảo ký ức':'Về danh sách trò chơi'} onClick={()=>round?exitRound.current?.():onExit()}><ArrowLeft size={20}/></button><button className="mm-brand" onClick={()=>round?exitRound.current?.():setPanel(null)}><span className="mm-brand-mark"><Flower2 size={23}/></span><span>Đảo Ký Ức<small>LẬT THẺ · TÌM NIỀM VUI</small></span></button><div className="mm-top-actions"><span className="mm-wallet"><Star size={17} fill="currentColor"/>{student.stars}</span><button className="mm-icon" aria-label="Sổ khám phá" onClick={()=>show('book')}><BookOpen size={19}/></button><button className="mm-icon" aria-label="Tùy chọn" onClick={()=>show('settings')}><Settings2 size={19}/></button></div></header>
        {round?<MemoryRound key={round.id} initial={round} student={student} prefs={prefs} complete={complete} onLeave={leave} onAgain={again} onNext={following} onPrefs={()=>show('settings')} exitRef={exitRound} pauseRef={pauseRound} suspended={!!panel}/>:
        <main className="mm-home"><section className="mm-hero"><div className="mm-hero-copy"><span className="mm-eyebrow"><span/> MỘT CHUYẾN ĐI DÀNH CHO {student.name.toLocaleUpperCase('vi')}</span><h1>Lật một chiếc thẻ.<br/><em>Mở một niềm vui.</em></h1><p>Những người bạn nhỏ đang đợi em.<br/>Tìm các cặp hình, khám phá hòn đảo của riêng mình.</p>
            <div className="mm-hero-buttons"><button className="mm-primary" onClick={()=>draft.session?setRound(draft.session):playNext()}><Play size={18} fill="currentColor"/>{draft.session?'Chơi tiếp ván dở':done===0?'Bắt đầu khám phá':done===30?'Ghé lại hòn đảo':'Tiếp tục hành trình'}<ArrowRight size={18}/></button><button className="mm-secondary" onClick={()=>show('quick')}><Shuffle size={17}/>Chơi nhanh</button></div>
            <div className="mm-journey-progress"><span>{done}/30 bài đã khám phá</span><div><i style={{width:`${done/30*100}%`}}/></div><small>{done===30?'Một hòn đảo đầy những kỷ niệm!':'Mỗi bài hoàn thành, đảo thêm một điều mới.'}</small></div>
            {draft.corrupt&&<p className="mm-draft-warning" role="status">Ván dở chưa đọc được. Thành tích đã lưu vẫn ở đây; em có thể bắt đầu một ván mới.</p>}
        </div><div className="mm-hero-island"><Island zone={zone} completed={count} decoration={prefs.decoration}/><div className="mm-island-caption"><span className="mm-live-dot"/>{count===6?'Hòn đảo đã hoàn thiện!':count===0?'Một hòn đảo đang chờ em':`${count}/6 điều mới trên đảo`}</div></div></section>
        <nav className="mm-zones" aria-label="Các vùng khám phá">{ZONES.map((item,i)=>{const open=i===0||!!progress.missions[MISSIONS[i*6-1].id],n=MISSIONS.filter(m=>m.zone===item.id&&progress.missions[m.id]).length;return <button key={item.id} className={zone===item.id?'active':''} aria-pressed={zone===item.id} disabled={!open} onClick={()=>setZone(item.id)}><Picture id={item.icon}/><span><strong>{item.name}</strong><small>{open?`${n}/6 bài`:'Hoàn thành vùng trước'}</small></span>{!open&&<LockKeyhole size={13}/>}</button>;})}</nav>
        <section className="mm-missions"><div className="mm-section-title"><div><span className="mm-eyebrow">CHỌN MỘT NIỀM VUI</span><h2>{z.name}</h2><p>{z.subtitle}</p></div><span className="mm-gift-preview"><Flag size={16}/>{count===6?'Đã mở đủ 6 món trang trí':`Sắp mở: ${REGION_GIFTS[zone][count]}`}</span></div><div className="mm-mission-grid">{MISSIONS.filter(m=>m.zone===zone).map(m=>{const record=progress.missions[m.id],open=unlocked(m.id),current=next?.id===m.id;return <button key={m.id} className={`mm-mission ${current?'current':''} ${record?'complete':''}`} disabled={!open} onClick={()=>start(missionConfig(m,prefs.relaxed))}><div className="mm-mission-top"><span>{record?<Check size={18}/>:open?`0${m.number}`:<LockKeyhole size={17}/>}</span><Stars count={record?.stars}/></div><h3>{m.title}</h3><p>{m.pairs} cặp · {m.rule==='shadow'?'Hình và bóng':m.preview?'Có xem trước':'Tìm hình giống nhau'}</p><div className="mm-mission-gift"><Flower2 size={14}/>{m.gift}</div><div className="mm-mission-cta">{current?'Cùng khám phá':record?'Thử thêm lần nữa':open?'Sẵn sàng':'Đang chờ em'}{open&&<ChevronRight size={17}/>}</div></button>;})}</div></section>
        <footer className="mm-home-footer"><span><Heart size={15}/> Nhớ được một chút cũng là một bước tiến.</span><button onClick={onLegacy}>Mở phiên bản cũ</button></footer></main>}

        {panel==='quick'&&<MemoryModal title="Chơi nhanh" onClose={()=>setPanel(null)}><span className="mm-eyebrow">MỘT VÁN THEO Ý EM</span><h2>Hôm nay em thích gì?</h2><p className="mm-muted">Chơi tự do, lưu kỷ lục riêng. Sao và trang trí được mở trong hành trình.</p><div className="mm-theme-picker">{ZONES.map(item=><button key={item.id} aria-pressed={quickZone===item.id} className={quickZone===item.id?'selected':''} onClick={()=>{setQuickZone(item.id);setShadow(false);}}><Picture id={item.icon}/><span>{item.name}</span></button>)}</div><label className="mm-field-label">Bao nhiêu cặp hình?</label><div className="mm-pair-picker">{PAIR_COUNTS.map(n=><button key={n} aria-pressed={pairs===n} disabled={shadow&&n>12} onClick={()=>setPairs(n)}>{n}</button>)}</div>{pairs===15&&<p className="mm-fine-print">Bộ mở rộng có thêm bạn từ các vùng khác.</p>}<div className="mm-settings-row"><label htmlFor="mm-preview">Xem trước các thẻ</label><select id="mm-preview" value={prefs.relaxed?-1:preview} disabled={prefs.relaxed} onChange={e=>setPreview(Number(e.target.value))}><option value={0}>Không xem trước</option><option value={3}>3 giây</option><option value={5}>5 giây</option><option value={8}>8 giây</option><option value={-1}>Xem rồi tự bắt đầu</option></select></div>{quickZone==='shapes'&&<label className="mm-toggle">Ghép hình với bóng<input type="checkbox" checked={shadow} onChange={e=>{setShadow(e.target.checked);if(e.target.checked&&pairs>12)setPairs(12);}}/></label>}<button className="mm-primary mm-wide" onClick={()=>start({zone:quickZone,pairs,rule:shadow?'shadow':'same',preview:prefs.relaxed?-1:preview,relaxed:prefs.relaxed})}>Bày thẻ thôi! <ArrowRight size={18}/></button></MemoryModal>}
        {panel==='settings'&&<MemoryModal title="Tùy chọn" onClose={()=>setPanel(null)}><span className="mm-eyebrow">CHƠI THẬT THOẢI MÁI</span><h2>Theo nhịp của em</h2><div className="mm-settings">{audio&&<label className="mm-toggle"><span>Nhạc nền<small>Âm nhạc của ứng dụng</small></span><input type="checkbox" checked={audio.musicEnabled} onChange={audio.toggleMusic}/></label>}{([{key:'sound',title:'Âm thanh phản hồi',detail:'Tiếng lật và tìm đúng cặp'},{key:'reduced',title:'Giảm chuyển động',detail:'Đổi mặt thẻ nhẹ nhàng'},{key:'clock',title:'Hiện đồng hồ',detail:'Thời gian không quyết định số sao'},{key:'relaxed',title:'Chế độ thư giãn',detail:'Ván sau: xem trước tự kết thúc, giữ hình lâu hơn'}] as const).map(item=><label key={item.key} className="mm-toggle"><span>{item.title}<small>{item.detail}</small></span><input type="checkbox" checked={prefs[item.key]} onChange={e=>{if(item.key==='sound'){if(!e.target.checked)cancelSpeech();audio?.toggleSound();}setPrefs(p=>({...p,[item.key]:e.target.checked}));}}/></label>)}</div><p className="mm-fine-print">Có thể gọi gợi ý trong ván. Gợi ý không trừ sao.</p></MemoryModal>}
        {panel==='book'&&<MemoryModal title="Sổ khám phá" onClose={()=>setPanel(null)}><span className="mm-eyebrow">NHỮNG ĐIỀU EM ĐÃ TÌM THẤY</span><h2>{done===30?'Hòn đảo của nhà khám phá!':'Sổ khám phá của em'}</h2><p className="mm-muted">{done} bài · {Object.values(progress.missions).reduce((sum,m)=>sum+m.stars,0)} sao hành trình</p><div className="mm-book-zones">{ZONES.map(item=>{const n=MISSIONS.filter(m=>m.zone===item.id&&progress.missions[m.id]).length;return <article key={item.id}><Picture id={item.icon}/><div><h3>{item.name}<small>{n}/6</small></h3><p>{n?REGION_GIFTS[item.id].slice(0,n).join(' · '):'Những điều mới đang chờ em.'}</p></div></article>;})}</div><div className="mm-decoration"><h3>Một màu sắc riêng cho đảo</h3><div>{[{id:'flowers',name:'Hoa nhỏ',at:0},{id:'stars',name:'Nắng vàng',at:6},{id:'shells',name:'Biển xanh',at:12}].map(d=><button key={d.id} disabled={done<d.at} aria-pressed={prefs.decoration===d.id} onClick={()=>setPrefs(p=>({...p,decoration:d.id as Preferences['decoration']}))}>{done<d.at?<LockKeyhole size={13}/>:<Flower2 size={14}/>} {d.name}{done<d.at&&<small>{d.at} bài</small>}</button>)}</div></div><details className="mm-picture-book"><summary>Xem các bạn trong bộ thẻ</summary><div>{ZONES.filter(item=>MISSIONS.some(m=>m.zone===item.id&&progress.missions[m.id])).flatMap(item=>item.pool.slice(0,12)).filter((id,i,a)=>a.indexOf(id)===i).map(id=><div key={id}><Picture id={id}/><span>{PICTURES[id]}</span></div>)}</div>{done===0&&<p>Hoàn thành bài đầu để mở trang bộ thẻ nhé.</p>}</details></MemoryModal>}
        {pending&&<MemoryModal title="Em có một ván đang chơi" onClose={()=>setPending(null)}><Picture id="fox" className="mm-modal-friend"/><h2>Mình còn một ván dở</h2><p className="mm-muted">Em có thể chơi tiếp, hoặc thay ván dở bằng một ván mới. Thành tích đã lưu vẫn được giữ.</p><button className="mm-primary mm-wide" onClick={()=>{if(draft.session)setRound(draft.session);setPending(null);}}>Chơi tiếp ván dở <Play size={17}/></button><button className="mm-text-button mm-wide" onClick={()=>{setDraft({session:null,corrupt:false});setRound(fresh(pending));setPending(null);}}>Bắt đầu ván mới</button></MemoryModal>}
    </div>;
}

interface RoundProps {initial:MemorySession;student:StudentProfile;prefs:Preferences;complete:AdventureProps['complete'];onLeave:(s:MemorySession,saved:boolean)=>void;onAgain:(c:MemoryConfig,seed?:number,columns?:number)=>void;onNext:(s:MemorySession)=>void;onPrefs:()=>void;exitRef:React.MutableRefObject<(()=>void)|null>;pauseRef:React.MutableRefObject<(()=>void)|null>;suspended:boolean}
function MemoryRound({initial,student,prefs,complete,onLeave,onAgain,onNext,onPrefs,exitRef,pauseRef,suspended}:RoundProps){
    const session=useMemorySession(initial,student.id),{state:s,send}=session,mission=MISSIONS.find(m=>m.id===s.config.missionId),z=ZONES.find(z=>z.id===s.config.zone)!;
    const [result,setResult]=useState<ReturnType<AdventureProps['complete']>|null>(null),[help,setHelp]=useState(false),[restart,setRestart]=useState(false),[focus,setFocus]=useState(0),[feedback,setFeedback]=useState('');
    const completion=useRef<string|null>(null),saveFn=useRef(complete);saveFn.current=complete;
    const lastMatched=useRef(s.matched.length),lastAttempts=useRef(s.attempts),board=useRef<HTMLDivElement>(null);
    const previousPhase=useRef(s.phase),previousPause=useRef(s.paused);
    const prior=useRef(readMemoryProgress(student.memoryMatch)),wasComplete=useRef(!!(mission&&prior.current.missions[mission.id]));
    const [viewport,setViewport]=useState(()=>({width:window.innerWidth,height:window.innerHeight}));
    const cols=s.columns;
    useEffect(()=>{
        const enter=(!s.paused&&previousPause.current)||(['ready','preview'].includes(previousPhase.current)&&s.phase==='first');
        previousPhase.current=s.phase;previousPause.current=s.paused;
        if(!enter||s.phase==='complete')return;
        const frame=requestAnimationFrame(()=>board.current?.querySelector<HTMLElement>(`[data-memory-index="${focus}"]`)?.focus());
        return()=>cancelAnimationFrame(frame);
    },[s.phase,s.paused,focus]);
    useEffect(()=>{let portrait=window.innerHeight>window.innerWidth;const resize=()=>{const next=window.innerHeight>window.innerWidth;if(next!==portrait){send({type:'pause'});portrait=next;}setViewport({width:window.innerWidth,height:window.innerHeight});};window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[send]);
    const rows=Math.ceil(s.deck.length/cols),gap=viewport.width<600?8:12,availableWidth=Math.min(820,viewport.width-40);
    const size=Math.max(44,Math.min(130,(availableWidth-gap*(cols-1))/cols,(viewport.height-245-gap*(rows-1))/rows));
    const boardWidth=cols*size+gap*(cols-1);
    const earned=resultOf(s),preset=presetKey(s),oldBest=mission?prior.current.missions[mission.id]?.best[preset]:prior.current.practiceBest[preset];
    const pause=()=>{cancelSpeech();send({type:'pause'});};pauseRef.current=pause;
    const leave=()=>{if(s.phase==='complete'&&!result?.ok)return;pause();session.save();onLeave(s,s.phase==='complete'&&!!result?.ok);};exitRef.current=leave;
    useEffect(()=>{if(suspended)send({type:'pause'});},[suspended,send]);
    useEffect(()=>{
        if(s.phase!=='complete'||completion.current===s.id)return;completion.current=s.id;
        const saved=saveFn.current(student.id,s);setResult(saved);if(saved.ok)session.finish();memorySound('win',prefs.sound);
    },[s.phase,s.id,student.id]);
    useEffect(()=>{
        if(s.matched.length>lastMatched.current){memorySound('match',prefs.sound);setFeedback(s.matched.length===s.config.pairs?'Em tìm đủ các cặp rồi!':'Một cặp đã tìm thấy. Tiếp tục nhé!');lastMatched.current=s.matched.length;}
        else if(s.phase==='first'&&s.attempts>lastAttempts.current)setFeedback('Chưa thành cặp. Mình đã biết thêm hai vị trí rồi!');
        if(s.phase==='first')lastAttempts.current=s.attempts;
    },[s.matched.length,s.phase,s.attempts,prefs.sound]);
    const flip=useCallback((id:string)=>{cancelSpeech();send({type:'flip',id});memorySound('flip',prefs.sound);},[send,prefs.sound]);
    const keyboard=useCallback((e:React.KeyboardEvent,index:number)=>{
        const offset:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-cols,ArrowDown:cols};let target:number|undefined;
        if(e.key in offset)target=Math.max(0,Math.min(s.deck.length-1,index+offset[e.key]));else if(e.key==='Home')target=0;else if(e.key==='End')target=s.deck.length-1;
        if(target!==undefined){e.preventDefault();board.current?.querySelector<HTMLElement>(`[data-memory-index="${target}"]`)?.focus();setFocus(target);}
    },[cols,s.deck.length]);
    const progressCount=Object.keys(readMemoryProgress(student.memoryMatch).missions).filter(id=>id.startsWith(s.config.zone+'-')).length;
    const nextMission=mission&&MISSIONS[MISSIONS.indexOf(mission)+1];
    const caption=s.phase==='preview'?(s.config.preview<0?'Ngắm các thẻ theo nhịp của em':`Cùng ghi nhớ · ${Math.ceil(s.waitMs/1000)} giây`):s.phase==='second'?'Em nhớ hình này ở đâu không?':s.hintMs?'Vị trí sáng lên là một gợi ý nhỏ.':feedback||(s.config.rule==='shadow'?'Tìm một hình và chiếc bóng giống nó.':'Chạm hai thẻ để tìm một cặp giống nhau.');
    return <main className="mm-round"><div className="mm-round-heading"><div><span className="mm-eyebrow">{z.name} <ChevronRight size={12}/>{mission?`BÀI ${mission.number}/6`:'CHƠI TỰ DO'}</span><h1>{mission?.title||'Một ván theo ý em'}</h1></div><div className="mm-round-tools"><button className="mm-icon" aria-label="Hướng dẫn chơi" onClick={()=>{pause();setHelp(true);}}><HelpCircle size={19}/></button><button className="mm-icon" aria-label="Chơi lại hoặc đổi bàn" onClick={()=>{pause();setRestart(true);}} disabled={s.phase==='complete'}><RotateCcw size={18}/></button><button className="mm-icon" aria-label="Tạm dừng ván" onClick={pause} disabled={s.phase==='complete'}><Pause size={18}/></button></div></div>
        <div className="mm-round-score"><span><span className="mm-pair-icon"><Flower2 size={18}/></span><strong>{s.matched.length}<small>/{s.config.pairs} cặp</small></strong></span><div className="mm-round-track"><i style={{width:`${s.matched.length/s.config.pairs*100}%`}}/></div><span className="mm-attempts">{s.attempts} lượt thử</span>{prefs.clock&&<span className="mm-clock"><Clock3 size={14}/>{formatTime(s.elapsedMs)}</span>}</div>
        <div className="mm-board-wrap"><div ref={board} className={`mm-board ${s.paused?'mm-board-hidden':''}`} role="group" aria-label="Bàn lật thẻ" aria-hidden={s.paused||s.phase==='ready'} inert={s.paused||s.phase==='ready'} style={{gridTemplateColumns:`repeat(${cols},1fr)`,width:boardWidth,gap} as React.CSSProperties}>{s.deck.map((tile,i)=><MemoryTile key={tile.id} tile={tile} index={i} cols={cols} revealed={s.selected.includes(tile.id)||s.matched.includes(tile.picture)||s.phase==='preview'} matched={s.matched.includes(tile.picture)} hinted={s.hintIds.includes(tile.id)} blocked={!['first','second'].includes(s.phase)||s.paused} tabStop={focus===i} onFlip={flip} onFocus={setFocus} onKey={keyboard}/>)}</div></div>
        <div className="mm-round-bottom"><div className="mm-buddy-message"><Picture id={z.icon}/><p role="status" aria-live="polite">{s.paused?'Ván chơi đang nghỉ một chút.':caption}</p></div>{s.phase==='preview'?<button className="mm-primary" onClick={()=>send({type:'endPreview'})}>Em sẵn sàng <ArrowRight size={16}/></button>:<button className="mm-secondary mm-hint" onClick={()=>send({type:'hint'})} disabled={!['first','second'].includes(s.phase)||s.paused||s.hintMs>0}><Sparkles size={16}/>Gợi ý{ s.hints>0&&<small>{s.hints}</small>}</button>}</div>
        <p className={`mm-save-status ${session.saved?'':'error'}`} role={session.saved?undefined:'status'}>{session.saved?'Ván chơi tự lưu trên thiết bị':<button onClick={session.save}>Chưa lưu được ván · bấm để thử lại</button>}</p>
        {s.phase==='ready'&&!s.paused&&<MemoryModal title="Sẵn sàng lật thẻ"><Picture id={z.icon} className="mm-modal-friend"/><span className="mm-eyebrow">{s.config.pairs} CẶP · {s.config.rule==='shadow'?'HÌNH VÀ BÓNG':'HAI HÌNH GIỐNG NHAU'}</span><h2>{mission?.title||'Cùng bày một bàn mới!'}</h2><p className="mm-muted">{mission?.tip||(s.config.rule==='shadow'?'Tìm hình màu và chiếc bóng cùng đường nét.':'Chạm hai thẻ. Nếu hình giống nhau, em tìm được một cặp!')}</p>{s.config.preview!==0&&<div className="mm-soft-note"><BookOpen size={18}/>{s.config.preview<0?'Em được xem trước đến khi sẵn sàng.':`Em có ${s.config.preview} giây xem trước sau khi bắt đầu.`}</div>}<div className="mm-modal-actions"><button className="mm-primary" onClick={()=>{cancelSpeech();send({type:'begin'});}}>Sẵn sàng! <Play size={17}/></button><button className="mm-icon" aria-label="Nghe hướng dẫn" disabled={!prefs.sound} onClick={()=>speak(mission?.tip||'Chạm hai thẻ để tìm một cặp giống nhau.',{rate:.85})}><Volume2 size={18}/></button></div><button className="mm-text-button mm-wide" onClick={leave}>Để sau, về đảo</button></MemoryModal>}
        {s.paused&&s.phase!=='complete'&&!help&&!restart&&!suspended&&<MemoryModal title="Ván chơi đã tạm dừng"><div className="mm-pause-art"><Picture id="bear"/></div><span className="mm-eyebrow">NGHỈ MỘT CHÚT CŨNG ĐƯỢC</span><h2>Những chiếc thẻ vẫn ở đây</h2><p className="mm-muted">{s.matched.length}/{s.config.pairs} cặp đã tìm thấy. Đồng hồ và thời gian xem thẻ đang dừng.</p><button className="mm-primary mm-wide" onClick={()=>send({type:'resume'})}>Chơi tiếp <Play size={17}/></button><div className="mm-pause-links"><button onClick={onPrefs}>Tùy chọn</button><button onClick={leave}>Lưu ván & về đảo</button></div></MemoryModal>}
        {help&&<MemoryModal title="Cách chơi" onClose={()=>setHelp(false)}><span className="mm-eyebrow">MỘT CHIẾC THẺ, MỘT GỢI NHỚ</span><h2>Mình tìm cặp như thế nào?</h2><div className="mm-howto"><div><b>1</b><p>Lật một thẻ và nhìn kỹ hình của nó.</p></div><div><b>2</b><p>{s.config.rule==='shadow'?'Tìm chiếc bóng có cùng đường nét, hoặc hình màu tương ứng.':'Lật thẻ thứ hai. Hai hình giống nhau sẽ thành một cặp.'}</p></div><div><b>3</b><p>Chưa đúng cũng không sao. Nhớ hai vị trí vừa thấy rồi thử tiếp!</p></div></div><p className="mm-soft-note">Gợi ý không trừ sao. Dùng phím mũi tên để chọn thẻ, Enter hoặc Space để lật.</p><button className="mm-primary mm-wide" onClick={()=>{setHelp(false);send({type:'resume'});}}>Em thử nhé <ArrowRight size={17}/></button></MemoryModal>}
        {restart&&<MemoryModal title="Chơi lại bàn thẻ" onClose={()=>setRestart(false)}><h2>Một khởi đầu mới?</h2><p className="mm-muted">Bắt đầu lại sẽ thay ván đang chơi. Em có thể giữ vị trí để luyện, hoặc bày thẻ theo cách mới.</p><button className="mm-primary mm-wide" onClick={()=>{session.finish();onAgain(s.config,s.seed,s.columns);}}>Giữ vị trí, chơi lại</button><button className="mm-secondary mm-wide" onClick={()=>{session.finish();onAgain(s.config);}}><Shuffle size={17}/>Bày bàn mới</button><button className="mm-text-button mm-wide" onClick={()=>{setRestart(false);send({type:'resume'});}}>Tiếp tục ván hiện tại</button></MemoryModal>}
        {s.phase==='complete'&&<MemoryModal title="Hoàn thành ván thẻ"><div className="mm-result-art"><Picture id={z.icon}/><span>✦</span><i>✧</i></div><span className="mm-eyebrow">MỘT KHÁM PHÁ THẬT ĐÁNG NHỚ</span><h2>{mission?.number===6?'Hòn đảo thêm rực rỡ!':'Em tìm thấy tất cả rồi!'}</h2><div className="mm-result-stars"><Stars count={earned.stars}/></div><div className="mm-result-stats"><div><strong>{s.attempts}</strong><span>lượt thử</span></div><div><strong>{s.config.pairs}</strong><span>cặp hình</span></div><div><strong>{s.hints}</strong><span>gợi ý</span></div></div>
            <p className="mm-result-rule">3 sao: tối đa {Math.floor(s.config.pairs*1.5)} lượt · 2 sao: tối đa {s.config.pairs*2} lượt</p>
            {oldBest&&s.attempts<oldBest.attempts&&<p className="mm-new-best"><Sparkles size={16}/>Ít hơn kỷ lục cùng chế độ {oldBest.attempts-s.attempts} lượt!</p>}
            {!!result?.bonusStars&&<p className="mm-new-best"><Star size={16}/>+{result.bonusStars} sao thành tích · {result.achievementNames?.join(', ')}</p>}
            {mission&&!wasComplete.current&&result?.ok&&<div className="mm-gift-earned"><Flower2 size={24}/><div><small>MỘT ĐIỀU MỚI TRÊN ĐẢO</small><strong>{mission.gift}</strong></div><Check size={18}/></div>}
            {mission?.number===6&&result?.ok&&<div className="mm-result-island"><Island zone={s.config.zone} completed={progressCount} decoration={prefs.decoration}/></div>}
            <p className={`mm-result-saved ${result?.ok?'':'error'}`} role="status">{result?.ok?(mission?(result.earned?`Đã lưu · +${result.earned} sao mới`:'Đã lưu · sao này đã được nhận trước đó'):'Đã lưu kỷ lục chơi tự do · không cộng sao'):'Kết quả chưa lưu được. Em có thể thử lưu lại.'}</p>
            {result?.ok?<button className="mm-primary mm-wide" onClick={()=>onNext(s)}>{mission?(nextMission?'Khám phá bài tiếp theo':'Xem hòn đảo của em'):'Chơi một bàn mới'}<ArrowRight size={18}/></button>:<button className="mm-primary mm-wide" onClick={()=>{const r=complete(student.id,s);setResult(r);if(r.ok)session.finish();}}>Thử lưu lại</button>}
            {result?.ok&&s.attempts>s.config.pairs*2&&!s.config.relaxed&&<button className="mm-secondary mm-wide" onClick={()=>onAgain({...s.config,relaxed:true,preview:-1},s.seed,s.columns)}><BookOpen size={16}/>Thử lại có xem trước</button>}
            <div className="mm-result-links">{result?.ok&&<button onClick={()=>onAgain(s.config,s.seed,s.columns)}>Thử ít lượt hơn</button>}<button onClick={()=>{if(!result?.ok)session.finish();onLeave(s,true);}}>{result?.ok?'Về đảo, nghỉ một chút':'Rời ván, bỏ kết quả chưa lưu'}</button></div>
        </MemoryModal>}
    </main>;
}
