import { describe, expect, it } from 'vitest';
import * as THREE from 'three';
import { Building, BUILDINGS, buildingDemand, createRegion, FLOOR_LIMITS, floorsOf, footprint, placeBuilding, RegionHistory, roadLine, simulate, validateRegion } from './region';
import { pedestrianRoutes, routePosition } from './traffic';
import { buildingInstances } from '../rendering/architecture';
import { shapeGeometry } from '../rendering/Instances';

const flat = () => { const r = createRegion('meadow', 42); r.height.fill(1); r.trees = []; return r; };
const draft = (type: Building['type'] = 'home', floors = 1) => ({ type, x: 10, z: 10, yaw: 0, color: BUILDINGS[type].color, roof: 0, floors, style: 0 });
describe('building floors and compatibility', () => {
    it('treats pre-upgrade saves as one floor and classic architecture', () => { const r = flat(), b = placeBuilding(r, draft())!; delete b.floors; delete b.style; expect(floorsOf(b)).toBe(1); expect(buildingDemand(b)).toEqual({ power: 1, water: 2 }); expect(() => validateRegion(r)).not.toThrow(); expect(buildingInstances(b)).toEqual(buildingInstances({ ...b, floors: 1, style: 0 })); });
    it('enforces per-type limits at creation and save validation', () => { for (const type of Object.keys(BUILDINGS) as Building['type'][]) { const r = flat(); expect(placeBuilding(r, draft(type, FLOOR_LIMITS[type] + 1))).toBeNull(); const b = placeBuilding(r, draft(type, FLOOR_LIMITS[type]))!; expect(b).toBeTruthy(); b.floors = 1.5; expect(() => validateRegion(r)).toThrow(); } });
    it('rejects negative floors and unknown architectural styles', () => { const r = flat(); expect(placeBuilding(r, draft('home', -1))).toBeNull(); expect(placeBuilding(r, { ...draft(), style: 3 })).toBeNull(); });
    it('increases resources and occupants with floors, and undo restores both', () => { const r = flat(), b = placeBuilding(r, draft())!; placeBuilding(r, { ...draft('solar'), x: 15 }); placeBuilding(r, { ...draft('water'), x: 20 }); roadLine(r, 11, 12, 21, 12); const h = new RegionHistory(); expect(simulate(r).residents).toBe(4); h.begin(r); b.floors = 4; h.commit(r, 'floors'); expect(buildingDemand(b)).toEqual({ power: 4, water: 8 }); expect(simulate(r).residents).toBe(16); h.travel(r); expect(simulate(r).residents).toBe(4); h.travel(r, true); expect(simulate(r).residents).toBe(16); });
    it('keeps floors and style when a building moves or is duplicated', () => { const r = flat(), b = placeBuilding(r, { ...draft('home', 3), style: 2 })!; const moved = placeBuilding(r, { ...b, x: 20 }, b.id)!; const copy = placeBuilding(r, { ...moved, x: 25 })!; expect([moved.floors, copy.floors, moved.style, copy.style]).toEqual([3, 3, 2, 2]); expect(copy.id).not.toBe(b.id); });
});
describe('roof alignment and architecture', () => {
    it('keeps a rectangular gable aligned with the footprint at all four rotations', () => { const geo = shapeGeometry('gable'); for (let yaw = 0; yaw < 4; yaw++) { const b: Building = { ...draft('school', 3), yaw, id: 'test', foundation: 1 }; const roof = buildingInstances(b).gable[0]; const matrix = new THREE.Matrix4().compose(new THREE.Vector3(...roof.position), new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), roof.yaw!), new THREE.Vector3(...roof.scale)); const box = new THREE.Box3(); const p = new THREE.Vector3(); for (let i = 0; i < geo.getAttribute('position').count; i++) box.expandByPoint(p.fromBufferAttribute(geo.getAttribute('position'), i).applyMatrix4(matrix)); const [w, d] = footprint(b.type, yaw); expect(box.max.x - box.min.x).toBeCloseTo(w - .04); expect(box.max.z - box.min.z).toBeCloseTo(d - .04); expect((box.min.x + box.max.x) / 2).toBeCloseTo(b.x + w / 2 - 32); expect((box.min.z + box.max.z) / 2).toBeCloseTo(b.z + d / 2 - 32); } geo.dispose(); });
    it('adds complete floors below the roof instead of scaling windows', () => { const b: Building = { ...draft(), id: 'test', foundation: 1 }; const one = buildingInstances(b), four = buildingInstances({ ...b, floors: 4 }); expect(four.gable[0].position[1] - one.gable[0].position[1]).toBeCloseTo(BUILDINGS.home.h * 3); expect(four.box.length).toBeGreaterThan(one.box.length * 2); });
    it('provides distinct architecture for each style and building type', () => { for (const type of Object.keys(BUILDINGS) as Building['type'][]) { const b: Building = { ...draft(type), id: type, foundation: 1 }; const styles = [0, 1, 2].map(style => JSON.stringify(buildingInstances({ ...b, style }))); expect(new Set(styles).size).toBe(3); } });
});
describe('moving pedestrians', () => {
    it('spawns only on dry roads connected to a home', () => { const r = flat(); expect(pedestrianRoutes(r)).toHaveLength(0); placeBuilding(r, draft()); expect(pedestrianRoutes(r)).toHaveLength(0); roadLine(r, 11, 12, 30, 12); expect(pedestrianRoutes(r).length).toBeGreaterThan(0); r.seaLevel = 2; expect(pedestrianRoutes(r)).toHaveLength(0); });
    it('moves continuously and stays on its connected roads', () => { const r = flat(); placeBuilding(r, draft()); roadLine(r, 11, 12, 22, 12); roadLine(r, 22, 12, 22, 25); const routes = pedestrianRoutes(r); for (const route of routes) for (let t = 0; t < 120; t += .1) { const p = routePosition(route, t); expect(r.roads[Math.floor(p.z) * 64 + Math.floor(p.x)]).toBe(1); const next = routePosition(route, t + .01); expect(Math.hypot(next.x - p.x, next.z - p.z)).toBeLessThan(.02); } });
    it('caps decoration count and removes paths after roads are erased', () => { const r = flat(); placeBuilding(r, draft('home', 6)); roadLine(r, 11, 12, 20, 12); expect(pedestrianRoutes(r, 2)).toHaveLength(2); r.roads.fill(0); expect(pedestrianRoutes(r)).toHaveLength(0); });
});
